### ISSUE TITLE
Does captum support multi-output regression models?

### ISSUE THREAD

**Issue by survivebycoding** [pytorch/captum#1039]
I dont see multi-class classification or multi output regression tutorials. Can someone tell me if captum supports multi output?

**Comment by aobo-y** [comment]
Which algorithm are you using? Both `FeatureAblation` and `FeaturePermutation` support multiple outputs. For example, if the forward returns in shape `(batch_size, num_of_output)`, both algorithms will return attr in shape `(batch_size * num_of_output, *input_feature_shape)`. Please note currently the 1st dim is the total number of elements in the output. You may need to reshape it back to `(batch_size, num_of_output, ...)` to access the feature attribution of each output
