### ISSUE TITLE
Does Captum support Image Regression as well?

### ISSUE THREAD

**Issue by MaxPolak97** [pytorch/captum#1051]
## ❓ Feature attribution for image regression
From what I have seen is that Captum is mainly used to understand model interpretability for image classification. I wonder whether it would still work for image regression. Only the latest fully-connected layer is different (1 continues output) instead of number of classes.

**Comment by aobo-y** [comment]
Yes, Captum support regression as well. For example, if your model output in shape `(batch_size)`, feature attribution will return attr in shape `(batch_size, *input_feature_shape)`.

**Comment by csqray** [comment]
@aobo-y Hello. Does Captum support multivariate regression? I have multiple continues outputs to predict and want to figure out the relationship between input and each variable in the output.

**Comment by aobo-y** [comment]
@csqray I have replied in https://github.com/pytorch/captum/issues/1126
