### ISSUE TITLE
When I use integratedGradients for wide&deep model，use torch.autograd.grad，find that the grad for wide and deep variables is None

### ISSUE THREAD

**Issue by YuCheng-Qi** [pytorch/captum#1063]
When I use the integral gradient algorithm to do gradient attribution to the wide and deep variables of the wide&deep algorithm, the error is as follows: AttributeError: 'NoneType' object has no attribute 'contiguous', when I print the calculated grads, I find the wide and deep variables The corresponding grads is None，：grads:  (None, None, tensor([[ 8.0624e-04,  1.1005e-02, -4.7557e-04, -4.0584e-03],
        [ 7.7517e-04,  1.0581e-02, -4.5724e-04, -3.9020e-03],
        [ 8.0306e-04,  1.0961e-02, -4.7369e-04, -4.0424e-03],
        ...,
        [ 1.3596e-04,  1.8558e-03, -8.0198e-05, -6.8440e-04],
        [ 4.3581e-04,  5.9485e-03, -2.5706e-04, -2.1937e-03],
        [ 8.8242e-04,  1.2044e-02, -5.2050e-04, -4.4419e-03]]))

where is the problem? Can anyone help me out, thanks ：）

**Comment by aobo-y** [comment]
Could you post your code to provide more context?

**Comment by YuCheng-Qi** [comment]
@aobo-y hi, thank you for your reply,this is my code:
step 1: Train and save a model:

import warnings
import torch
import torch.nn as nn

from captum.attr import IntegratedGradients
from torch.nn import CrossEntropyLoss
from torch.utils.tensorboard import  SummaryWriter
summaryWriter = SummaryWriter('./log')
from torch.utils.data import DataLoader
import logging


class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.embedding = nn.Embedding(1000, 8)
        self.fc = nn.Linear(100, 2)

    def forward(self, x_wide, x_deep, x_dense):
        x_wide = self.embedding(x_wide.long())
        x_wide = x_wide.view(-1, 64)
        x_deep = self.embedding(x_deep.long())
        x_deep = x_deep.view(-1, 32)

        X = torch.cat([x_wide,x_deep,x_dense], dim=1)
        logits = self.fc(X)
        target_classes = torch.argmax(logits, dim=1, keepdim=True)
        probabilites = torch.nn.functional.softmax(logits, dim=1)

        return {"logits":logits,
                "target_classes": target_classes,
                "probabilites": probabilites}


def train(epoch, model, train_loader, optimizer, early_stop_step, log_interval):
    model.train()
    running_loss = 0.0
    for current_step, sample in enumerate(train_loader):
        if current_step==0:
            logging.info(sample)
        logging.info(f"current_step: {current_step}")
        if current_step >5:
            break
        wide = sample[:, 0:8].long()
        deep = sample[:, 8:12].long()
        dense = sample[:, 12:-1]
        loss_fct = CrossEntropyLoss()

        pred = model(wide, deep, dense)
        pred = pred['logits']

        label = torch.round(sample[:, -1]).long()
        loss = loss_fct(pred.view(-1, 2), label.view(-1))
        optimizer.zero_grad()
        running_loss += loss.item()
        if current_step % log_interval ==0:
            loss = loss.item()
            pred = pred.view(-1,2).argmax(dim=1, keepdims=True)
            correct = pred.eq(label.view(-1).data).sum()
            logging.info(f"loss: {loss:.4f}  acc_train: {correct/len(train_loader.dataset):.4f}")
            logging.info(f"current epoch : [{epoch}]  current_step: {current_step}")
            if current_step == early_stop_step:
                break


def val(model, eval_loader):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for current_step, sample in enumerate(eval_loader):
            logging.info(f"current_step: {current_step}")
            if current_step >5:
                break

            loss_fct = CrossEntropyLoss()
            wide = sample[:,0:8]
            deep = sample[:, 8:12]
            dense = sample[:,12:-1]
            pred = model(wide, deep, dense)
            pred = pred['logits']
            label = torch.round(sample[:,-1]).long()

            test_loss += loss_fct(pred.view(-1, 2), label.view(-1))
            pred = pred.view(-1,2).argmax(dim=1, keepdims=True)
            correct += pred.eq(label.view_as(pred)).sum().item()
    test_loss = test_loss / len(eval_loader)
    logging.info(f"Val set: Average loss: {test_loss:.4f}")
    logging.info(f"Val set: correct: {correct}")
    logging.info(f"Val set: sample numbers: {len(eval_loader.dataset)}")
    logging.info(f"Val set: acc: {100*correct/len(eval_loader.dataset): .4f}")


if __name__ == '__main__':
    epoch = 1
    early_stop_step = 2000
    log_interval = 1
    lr = 1e-3
    torch.manual_seed(1)
    model = Net()
    X_dense = torch.rand(2000, 4)
    X_wide = torch.randint(0,9,(2000, 8))
    X_deep = torch.randint(0, 9, (2000, 4))
    y_label = torch.rand(2000, 1)

    training_data = torch.cat((X_wide, X_deep, X_dense, y_label), 1)
    test_data = torch.cat((X_wide, X_deep, X_dense, y_label), 1)
    train_dataloader = DataLoader(training_data, batch_size=128, shuffle=True)
    test_dataloader = DataLoader(test_data, batch_size=128, shuffle=True)

    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10,15])

    for epoch in range(1, epoch + 1):
        train(epoch, model, train_dataloader, optimizer, early_stop_step, log_interval)
        val(model, test_dataloader)
        scheduler.step()

    logging.info("save model")
    checkpoint_path = "torchapi_ig_wnd_20221118.pt"
    torch.save(model.state_dict(), checkpoint_path)
    print("Trianing is finished!")

step 2: use the model and explain by captum

import warnings
import torch
import torch.nn as nn

from captum.attr import IntegratedGradients, configure_interpretable_embedding_layer
from torch.nn import CrossEntropyLoss
from torch.utils.tensorboard import  SummaryWriter
summaryWriter = SummaryWriter('./log')
from torch.utils.data import DataLoader
import logging


class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.embedding = nn.Embedding(1000, 8)
        self.fc = nn.Linear(100, 2)

    def forward(self, x_wide, x_deep, x_dense):
        x_wide = self.embedding(x_wide.long())
        x_wide = x_wide.view(-1, 64)
        x_deep = self.embedding(x_deep.long())
        x_deep = x_deep.view(-1, 32)

        X = torch.cat([x_wide,x_deep,x_dense], dim=1)
        logits = self.fc(X)
        target_classes = torch.argmax(logits, dim=1, keepdim=True)
        probabilites = torch.nn.functional.softmax(logits, dim=1)

        return {"logits":logits,
                "target_classes": target_classes,
                "probabilites": probabilites}


# def sequential_forward(X_wide, X_deep, X_dense):
#     return model.forward(X_wide, X_deep, X_dense)
#
#
# def sal(X_wide, X_deep, X_dense, node_index):
#     sal = IntegratedGradients(sequential_forward)
#     grads = sal.attribute((X_wide, X_deep, X_dense), target=node_index)
#     return grads


class Explain_IntegratedGradients(object):
    def __init__(self, node_index):
        super(Explain_IntegratedGradients, self).__init__()
        self.model = Net().to(gpu)
        self.node_index = node_index

    def sequential_forward(self,X_wide, X_deep, X_dense):
        return self.model.forward(X_wide, X_deep, X_dense)['probabilites']

    def sal(self, X_wide, X_deep, X_dense, node_index, n_steps):
        sal = IntegratedGradients(self.sequential_forward)
        grads = sal.attribute((X_wide, X_deep, X_dense), target=node_index, n_steps=n_steps, return_convergence_delta=True)
        return grads


if __name__ == '__main__':
    gpu = torch.device('cpu')
    epchos = 1
    early_stop_step = 2000
    log_interval = 1
    lr = 1e-3
    n_steps = 50
    torch.manual_seed(1)
    model = Net()
    exp_ig = Explain_IntegratedGradients(1)

    model_path = 'torchapi_ig_wnd_20221118.pt'
    wnd_model = torch.load(model_path)

    exp_ig.model.load_state_dict(wnd_model)
    exp_ig.model = exp_ig.model.to(gpu)

    X_dense = torch.rand(2000, 4)
    X_wide = torch.randint(0, 9, (2000, 8))
    X_deep = torch.randint(0, 9, (2000, 4))
    y_label = torch.rand(2000, 1)
    test_data = torch.cat((X_wide, X_deep, X_dense, y_label),1)
    test_dataloader = DataLoader(test_data, batch_size=128, shuffle=True)

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        emb_net = configure_interpretable_embedding_layer(model)

    for current_step, sample in enumerate(test_dataloader):
        X_wide = sample[:,0:8]
        X_deep = sample[:, 8:12]
        X_dense = sample[:,12:-1]
        attr = exp_ig.sal(X_wide, X_deep, X_dense, 0,50)


After executing the above code, an error is reported as follows:
Traceback (most recent call last):
  File "/Users/qiyucheng/PycharmProjects/explain_ai/pytorch/explain_model/explain_ig_runner.py", line 92, in <module>
    attr = exp_ig.sal(X_wide, X_deep, X_dense, 0,50)
  File "/Users/qiyucheng/PycharmProjects/explain_ai/pytorch/explain_model/explain_ig_runner.py", line 56, in sal
    grads = sal.attribute((X_wide, X_deep, X_dense), target=node_index, n_steps=n_steps, return_convergence_delta=True)
  File "/Users/liyarong/opt/anaconda3/envs/py38/lib/python3.8/site-packages/captum/log/__init__.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/Users/liyarong/opt/anaconda3/envs/py38/lib/python3.8/site-packages/captum/attr/_core/integrated_gradients.py", line 285, in attribute
    attributions = self._attribute(
  File "/Users/liyarong/opt/anaconda3/envs/py38/lib/python3.8/site-packages/captum/attr/_core/integrated_gradients.py", line 350, in _attribute
    grads = self.gradient_func(
  File "/Users/liyarong/opt/anaconda3/envs/py38/lib/python3.8/site-packages/captum/_utils/gradient.py", line 119, in compute_gradients
    grads = torch.autograd.grad(torch.unbind(outputs), inputs)
  File "/Users/liyarong/opt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 202, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

where is the problem? Can you help me out, thanks ：）

**Comment by YuCheng-Qi** [comment]
step 2: use the model and explain by captum

import warnings
import torch
import torch.nn as nn

from captum.attr import IntegratedGradients, configure_interpretable_embedding_layer
from torch.nn import CrossEntropyLoss
from torch.utils.tensorboard import  SummaryWriter
summaryWriter = SummaryWriter('./log')
from torch.utils.data import DataLoader
import logging


class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.embedding = nn.Embedding(1000, 8)
        self.fc = nn.Linear(100, 2)

    def forward(self, x_wide, x_deep, x_dense):
        x_wide = self.embedding(x_wide.long())
        x_wide = x_wide.view(-1, 64)
        x_deep = self.embedding(x_deep.long())
        x_deep = x_deep.view(-1, 32)

        X = torch.cat([x_wide,x_deep,x_dense], dim=1)
        logits = self.fc(X)
        target_classes = torch.argmax(logits, dim=1, keepdim=True)
        probabilites = torch.nn.functional.softmax(logits, dim=1)

        return {"logits":logits,
                "target_classes": target_classes,
                "probabilites": probabilites}





class Explain_IntegratedGradients(object):
    def __init__(self, node_index):
        super(Explain_IntegratedGradients, self).__init__()
        self.model = Net().to(gpu)
        self.node_index = node_index

    def sequential_forward(self,X_wide, X_deep, X_dense):
        return self.model.forward(X_wide, X_deep, X_dense)['probabilites']

    def sal(self, X_wide, X_deep, X_dense, node_index, n_steps):
        sal = IntegratedGradients(self.sequential_forward)
        grads = sal.attribute((X_wide, X_deep, X_dense), target=node_index, n_steps=n_steps, return_convergence_delta=True)
        return grads


if __name__ == '__main__':
    gpu = torch.device('cpu')
    epchos = 1
    early_stop_step = 2000
    log_interval = 1
    lr = 1e-3
    n_steps = 50
    torch.manual_seed(1)
    model = Net()
    exp_ig = Explain_IntegratedGradients(1)

    model_path = 'torchapi_ig_wnd_20221118.pt'
    wnd_model = torch.load(model_path)

    exp_ig.model.load_state_dict(wnd_model)
    exp_ig.model = exp_ig.model.to(gpu)

    X_dense = torch.rand(2000, 4)
    X_wide = torch.randint(0, 9, (2000, 8))
    X_deep = torch.randint(0, 9, (2000, 4))
    y_label = torch.rand(2000, 1)
    test_data = torch.cat((X_wide, X_deep, X_dense, y_label),1)
    test_dataloader = DataLoader(test_data, batch_size=128, shuffle=True)

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        emb_net = configure_interpretable_embedding_layer(model)

    for current_step, sample in enumerate(test_dataloader):
        X_wide = sample[:,0:8]
        X_deep = sample[:, 8:12]
        X_dense = sample[:,12:-1]
        attr = exp_ig.sal(X_wide, X_deep, X_dense, 0,50)

**Comment by YuCheng-Qi** [comment]
After executing the above code, an error is reported as follows:
Traceback (most recent call last):
  File "/Users/qiyucheng/PycharmProjects/explain_ai/pytorch/explain_model/explain_ig_runner.py", line 92, in <module>
    attr = exp_ig.sal(X_wide, X_deep, X_dense, 0,50)
  File "/Users/qiyucheng/PycharmProjects/explain_ai/pytorch/explain_model/explain_ig_runner.py", line 56, in sal
    grads = sal.attribute((X_wide, X_deep, X_dense), target=node_index, n_steps=n_steps, return_convergence_delta=True)
  File "/Users/liyarong/opt/anaconda3/envs/py38/lib/python3.8/site-packages/captum/log/__init__.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/Users/liyarong/opt/anaconda3/envs/py38/lib/python3.8/site-packages/captum/attr/_core/integrated_gradients.py", line 285, in attribute
    attributions = self._attribute(
  File "/Users/liyarong/opt/anaconda3/envs/py38/lib/python3.8/site-packages/captum/attr/_core/integrated_gradients.py", line 350, in _attribute
    grads = self.gradient_func(
  File "/Users/liyarong/opt/anaconda3/envs/py38/lib/python3.8/site-packages/captum/_utils/gradient.py", line 119, in compute_gradients
    grads = torch.autograd.grad(torch.unbind(outputs), inputs)
  File "/Users/liyarong/opt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 202, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

where is the problem? Can you help me out, thanks ：）

**Comment by YuCheng-Qi** [comment]
@aobo-y this is my git address:
git@github.com:YuCheng-Qi/explain_xai.git

**Comment by YuCheng-Qi** [comment]
I have solved this problem。
