### ISSUE TITLE
A peer-reviewed citation version 

### ISSUE THREAD

**Issue by luyang-ai4med** [pytorch/captum#1079]
Do you have a peer-reviewed citation version that we could use (workshops, conference)? For some journals, preprints are not allowed. Thank you.

_Originally posted by @luyang-ai4med in https://github.com/pytorch/captum/issues/474#issuecomment-1321066854_

**Comment by NarineK** [comment]
Responded per email. Link to peer reviewed comments on open review: https://openreview.net/forum?id=xHH6t1iNEP-

**Comment by gonconist** [comment]
I would also like to have one for my phd thesis! Thank you.

**Comment by NarineK** [comment]
@gonconist, you can site our paper on ArXiv: https://arxiv.org/abs/2009.07896

The paper was accepted to the RAI workshop at ICLR 2021 and unfortunately workshop papers do not get published in the proceedings. 
https://openreview.net/forum?id=xHH6t1iNEP-

**Comment by NarineK** [comment]
closing this issue since it is addressed.
