### ISSUE TITLE
How to use captum for BERT interpretability when using long sequence?

### ISSUE THREAD

**Issue by psj1997** [pytorch/captum#1109]
Dear developers

Thanks for developing this.

I am trying to use captum to explain BERT when using long sequence (length: 4096).

The basic idea of our model is:
(1) split the long sequence to 8 short sequences (512) 
(2) get the embeddings for every short sequence using BERT
(3) concatenate the embeddings together (768 * 8)
(4) using a linear layer to output the prediction

Now, I have tried to use `FeatureAblation` to calculate the attribution score. If this function is used correctly in this situation?

And which way is the best to calculate the attribution score in this situation?

Thanks for your any comments and suggestions.

Best
Shaojun

**Comment by NarineK** [comment]
Hi @psj1997, feature ablation and other algorithms are model agnostic. They can be used for any type of model to attribute selected model outputs to the inputs. In your case it looks like you are trying to get token level feature importance ? You should be able to apply any of those algorithms to your use case. Did you see any issues when you applied `FeatureAblation` ? I was wondering if you could describe more the concern or the question that you have for your use case.

**Comment by psj1997** [comment]
Thanks! 
 
I have calculated the attribution score successfully using `FeatureAblation`. I just want to ask if this function can be used in this situation (I do not find information about this in the docs).

Sincerely
Shaojun

**Comment by NarineK** [comment]
yes, feature ablation is used for text applications. We have NLP tutorials. You can see that we also used integrated gradients for Bert Models.

**Comment by psj1997** [comment]
Thanks! I will check it again.

Sincerely
Shaojun
