### ISSUE TITLE
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

### ISSUE THREAD

**Issue by BhbatBristol** [pytorch/captum#1116]
I am currently using IntegratedGradients with dgl to explain heterogeneous GNN. 

Here is my code for explaining edges. But I got a runtime error.  I do not know why there will be an error.

```
import dgl
import dgl.nn as dglnn
import torch

import torch.nn.functional as F
from captum.attr import IntegratedGradients
from functools import partial

dataset = dgl.data.MUTAGDataset()

g = dataset[0]

# Some synthetic node features - replace it with your own.
for ntype in g.ntypes:
    g.nodes[ntype].data['x'] = torch.randn(g.num_nodes(ntype), 10)


# Your model...
class Model(torch.nn.Module):
    def __init__(self, etypes):
        super().__init__()
        self.conv1 = dglnn.HeteroGraphConv({etype: dglnn.SAGEConv(10, 10, 'mean') for _, etype, _ in etypes})
        self.w = dglnn.EdgeWeightNorm()
        self.l = torch.nn.Linear(10,1)
    def forward(self, blocks, h_dict, eweight = None):
        if eweight is None:
            h_dict = self.conv1(blocks[0], h_dict)
        else:
            h_dict = self.conv1(blocks[0], h_dict, mod_kwargs={
            c_etype: {'edge_weight': self.w(blocks[0][c_etype], eweight[c_etype])} for c_etype in blocks[0].canonical_etypes
            })
        return self.l(h_dict['SCHEMA'])


m = Model(g.canonical_etypes)

# Minibatch sampling stuff...
sampler = dgl.dataloading.as_edge_prediction_sampler(
    dgl.dataloading.NeighborSampler([2, 2]), negative_sampler=dgl.dataloading.negative_sampler.Uniform(2))
eid = {g.canonical_etypes[0]: torch.arange(g.num_edges(g.canonical_etypes[0]))}
# Let's iterate over and explain one edge at a time.
dl = dgl.dataloading.DataLoader(g, eid, sampler, batch_size=1)


# Define a function that takes in a single tensor as the first argument and also returns a
# single tensor.

def forward_model(edge_masks, c_etype,  blocks, x_dict, eweight):
    # eweight = eweight.copy()
    # eweight[c_etype] = x
    eweight[c_etype] = edge_masks
    return m(blocks, x_dict, eweight=eweight).squeeze()


for input_nodes, pair_graph, neg_pair_graph, blocks in dl:
    input_dict = blocks[0].ndata['x']

    output = m(blocks, input_dict)

    loss = F.mse_loss(
        input=output,
        target=torch.randn(output.size()).float(),
    )
    loss.backward()

    m.zero_grad()

    edge_masks = {}
    for c_etype in blocks[0].canonical_etypes:
        edge_masks[c_etype] = torch.ones(blocks[0].num_edges(c_etype))
        edge_masks[c_etype].requires_grad = True
    for c_etype in blocks[0].canonical_etypes:
        # ig = IntegratedGradients(partial(forward_model,
        #                                  c_etype=c_etype,  blocks=blocks, x_dict=input_dict, eweight=edge_masks))
        # print(ig.attribute(edge_masks[c_etype], internal_batch_size=edge_masks[c_etype].size(0), n_steps=50))
        ig = IntegratedGradients(forward_model)
        print(ig.attribute(edge_masks[c_etype], additional_forward_args=(c_etype, blocks, input_dict, edge_masks),
                            internal_batch_size=edge_masks[c_etype].size(0), n_steps=50))
        break
```

And the error is:

Traceback (most recent call last):
  File "test2.py", line 78, in <module>
    internal_batch_size=edge_masks[c_etype].size(0), n_steps=50, method='riemann_right'))
  File "/home/hongbo/anaconda3/envs/mumin/lib/python3.7/site-packages/captum/log/__init__.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/home/hongbo/anaconda3/envs/mumin/lib/python3.7/site-packages/captum/attr/_core/integrated_gradients.py", line 283, in attribute
    method=method,
  File "/home/hongbo/anaconda3/envs/mumin/lib/python3.7/site-packages/captum/attr/_utils/batching.py", line 79, in _batch_attribution
    **kwargs, n_steps=batch_steps, step_sizes_and_alphas=(step_sizes, alphas)
  File "/home/hongbo/anaconda3/envs/mumin/lib/python3.7/site-packages/captum/attr/_core/integrated_gradients.py", line 355, in _attribute
    additional_forward_args=input_additional_args,
  File "/home/hongbo/anaconda3/envs/mumin/lib/python3.7/site-packages/captum/_utils/gradient.py", line 119, in compute_gradients
    grads = torch.autograd.grad(torch.unbind(outputs), inputs)
  File "/home/hongbo/anaconda3/envs/mumin/lib/python3.7/site-packages/torch/autograd/__init__.py", line 302, in grad
    allow_unused, accumulate_grad=False)  # Calls into the C++ engine to run the backward pass
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

**Comment by vivekmig** [comment]
Hi @BhbatBristol , from the stack trace, the message seems to suggest that the input tensor edge_masks[c_etype] is not actually used in the computation of the output for which Integrated Gradients is being computed. 

I ran the model provided with FeatureAblation, and the attributions are 0.0, which suggests there may not be a dependence. Additionally, adding an explicit dependence on these input tensors (such as the below code), does also allow integrated gradients to work:
```
            output_sum = sum(torch.sum(self.w(blocks[0][c_etype], eweight[c_etype])) for c_etype in blocks[0].canonical_etypes)
        return self.l(h_dict['SCHEMA']) + output_sum
```

Can you confirm that the model output does depend on this input tensor?

**Comment by BhbatBristol** [comment]
Thank you  @vivekmig so much. Then I now know where the problem is.

**Comment by vivekmig** [comment]
No problem, glad it's resolved!

**Comment by BhbatBristol** [comment]
Hi @Luckick,

I guess the problem with my code is there seems no dependency between the input of the attribute function and the output of the mode. The input is the edge weight which is not used when I trained the model. So I did as @vivekmig suggested, and it works.
