### ISSUE TITLE
cannot import name 'ExpansionTypes' from 'captum.attr._utils.common'

### ISSUE THREAD

**Issue by LongchaoDa** [pytorch/captum#1139]
## To Reproduce

1. I was using this repo:https://github.com/divelab/DIG
2. when I installed all the requirements, and run the file here: https://github.com/divelab/DIG/blob/fb4979fee1fb01fbec3768d81ce810b900389b2e/examples/xgraph/subgraphx.ipynb
3. I face the problem: `cannot import name 'ExpansionTypes' from 'captum.attr._utils.common'`
4. I searched the keyword in the common.py file, and did not find any, I suppose the developer updated version and removed this variable or somewhat.
5. However, I need to use the old version of the code, is that possible anyone point me to the previous version that has this feature and I could directly use? 

Thanks a lot!

## Environment
Describe the environment used for Captum

```

 - Captum / PyTorch Version (e.g.,  0.6.0/1.12 ):
 - OS (e.g., Linux):
 - How you installed Captum / PyTorch (`conda`, `pip`, I tried both):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by vivekmig** [comment]
Hi @LongchaoDa , apologies for the delay in looking into this! This functionality of ExpansionTypes was available previously, particularly in Captum version 0.2.0. If necessary, you can explicitly install this version using `pip install captum==0.2.0`.
