### ISSUE TITLE
在code summarization任务上使用LayerIntegratedGradients进行可解释性分析

### ISSUE THREAD

**Issue by Thekulun** [pytorch/captum#1148]
使用微调好的'Salesforce/codet5-base'模型在code summarization任务上使用LayerIntegratedGradients进行可解释性分析，有没有参考代码

**Comment by aobo-y** [comment]
We offers many tutorials using `LayerIntegratedGradients` https://captum.ai/tutorials/IMDB_TorchText_Interpret
But we don't use `Salesforce/codet5-base`. The exact model does not matter much as you can always write a `forward_func` wrapper with expected the input and output to make it work.

Feel free to create another issue if you did encounter any specific issues.
