### ISSUE TITLE
IG can not work in such model

### ISSUE THREAD

**Issue by 20032303092** [pytorch/captum#1156]
## 🚀 Feature
IG can not work in such model

## Motivation

if I use bert as an embedding layer and then use other pytorch modules just like cnn, lstm and dense to construct my prediction model, however, IG can not work in such model.
In your doc, just make a simple example for transfomer, it is not enough in real situation.

## Pitch

to make it work

**Comment by Z4K4RI4** [comment]
Hi,
I use a Bert model to provide embeddings to other pytorch modules. I did not encounter this problem.  
Can you provide some code samples to better understand where the problem is ?

**Comment by aobo-y** [comment]
@20032303092 Did you read the documentation? We provides many examples to show how to work with transformer or embedding layers

https://captum.ai/tutorials/Bert_SQUAD_Interpret
https://captum.ai/tutorials/IMDB_TorchText_Interpret

transfomer does not make much of differences than other embedding modules in term of attribution.
