### ISSUE TITLE
RuntimeError: cudnn RNN backward can only be called in training mode

### ISSUE THREAD

**Issue by LiuJeremy** [pytorch/captum#1159]
Hello, I encountered a problem while using captum in the LSTM model，and it looks like this：RuntimeError: cudnn RNN backward can only be called in training mode. When I changed model. eval() to model. train(), it did run, but I think the result should be non repeatable.

**Comment by LiuJeremy** [comment]
I have resolved this issue by setting 
'''
torch.backends.cudnn.enabled=False
'''
This method comes from Integrated gradient for LSTM shows 'cudnn RNN backward can only be called in training mode' #564 [564](https://github.com/pytorch/captum/issues/564)

**Comment by LiuJeremy** [comment]
I have resolved this issue by setting `torch.backends.cudnn.enabled=False`

This method comes from Integrated gradient for LSTM shows 'cudnn RNN backward can only be called in training mode' https://github.com/pytorch/captum/issues/564

**Comment by aobo-y** [comment]
Yes, this is a known issue out of Captum's control.
