### ISSUE TITLE
Can I use captum in semantic segmentation tasks?

### ISSUE THREAD

**Issue by Miracle1991** [pytorch/captum#119]
Can I use captum in semantic segmentation tasks?

**Comment by NarineK** [comment]
Hi @Miracle1991, thank you for bringing this up. 
Are you talking about semantic segmentation models such as `models.segmentation.fcn_resnet101` models from torchvision or do you have any specific ones your mind ?

We should be able to get an attribution for each image pixel for `models.segmentation.fcn_resnet101`

**Comment by Miracle1991** [comment]
I am confused with the target in ig.attribute. the target in semantic segmentation models is a tensor with 3 dimensions. 
here is my code

`    input = torch.rand(1, 3, 320, 672)
    baseline = torch.zeros(1, 3, 320, 672)

    ig = IntegratedGradients(model)
    attributions, delta = ig.attribute(input, baseline, target=### **?,** return_convergence_delta=True)
    print('IG Attributions: ', attributions, ' Convergence Delta: ', delta)`

my model's target is a tensor with shape(1, 80, 168)

**Comment by Miracle1991** [comment]
here is my code, i asume my target is a zero tensor with shape (80, 168), and i got an error

`    # build model
    model = build_detection_model(cfg)
    model.eval()
    # device = torch.device(cfg.MODEL.DEVICE)
    # model.to(device)

    # load weight
    save_dir = cfg.OUTPUT_DIR
    checkpointer = DetectronCheckpointer(cfg, model, save_dir=save_dir)
    _ = checkpointer.load(cfg.MODEL.WEIGHT)

    torch.manual_seed(123)
    np.random.seed(123)

    input = torch.rand(1, 3, 320, 672)
    baseline = torch.zeros(1, 3, 320, 672)

    ig = IntegratedGradients(model)
    attributions, delta = ig.attribute(input, baseline, target=torch.zeros(80, 168), return_convergence_delta=True)
    print('IG Attributions: ', attributions, ' Convergence Delta: ', delta)`
`/home/w/anaconda3/lib/python3.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "/home/w/workspace/freespace/py3/perception-tnt/apps/freespace/tools/tnt_captum.py", line 91, in <module>
    attributions, delta = ig.attribute(input, baseline, target=torch.zeros(80, 168), return_convergence_delta=True)
  File "/home/w/anaconda3/lib/python3.7/site-packages/captum/attr/_core/integrated_gradients.py", line 200, in attribute
    target_ind=expanded_target,
  File "/home/w/anaconda3/lib/python3.7/site-packages/captum/attr/_utils/batching.py", line 125, in _batched_operator
    inputs, additional_forward_args, target_ind, internal_batch_size
  File "/home/w/anaconda3/lib/python3.7/site-packages/captum/attr/_utils/batching.py", line 124, in <listcomp>
    for input, additional, target in _batched_generator(
  File "/home/w/anaconda3/lib/python3.7/site-packages/captum/attr/_utils/gradient.py", line 85, in compute_gradients
    output = _run_forward(forward_fn, inputs, target_ind, additional_forward_args)
  File "/home/w/anaconda3/lib/python3.7/site-packages/captum/attr/_utils/common.py", line 209, in _run_forward
    return _select_targets(output, target)
  File "/home/w/anaconda3/lib/python3.7/site-packages/captum/attr/_utils/common.py", line 181, in _select_targets
    "Tensor target dimension %r is not valid." % (target.shape,)
AssertionError: Tensor target dimension torch.Size([4000, 168]) is not valid.
`

**Comment by NarineK** [comment]
Hi @Miracle1991, target refers to output index in model's output  (in this case to the dimensions of model(input)) and it should point to a scalar for each input example(for instance index: (1, 2, 1)). You could potentially call IG in a loop for specific target output points.

**Comment by bilalsal** [comment]
Hi @Miracle1991 

Again thank you for bringing up your question! It triggered good discussion on how Captum can be used to inspect segmentation models.
As @NarineK explained, currently the attribution target supported by Captum algorithms should be a scalar (e.g. a class probability). In semantic segmentation, the output is a 2D image which is a challenging and interesting case, not addressed in the literature AFAIS. It would probably be less useful to compute attribution for a single pixel.
However, it could be interesting to analyze which parts of the input image have influence on a semantic label in the segmentation output. 
We created an example of a similar kind of analysis using Captum which you might find inspiring: https://github.com/pytorch/captum/blob/master/tutorials/Resnet_TorchVision_Ablation.ipynb

Hope this helps a bit further
