### ISSUE TITLE
ImportError for 'TextTemplateFeature' and 'TextTokenFeature' from 'captum.attr'

### ISSUE THREAD

**Issue by MSingh-CSE** [pytorch/captum#1242]
### Issue Summary:
Encountering import errors with `TextTemplateFeature` and `TextTokenFeature` from the `captum.attr` module while following the code example provided in the paper: [Using Captum to Explain Generative Language Models](https://arxiv.org/pdf/2312.05491.pdf).

### Steps to Reproduce:
I attempted to use `LayerIntegratedGradients` to get attributions for Llama 2 7B using the code snippet from the mentioned paper. However, I encountered import errors for both `TextTemplateFeature` and `TextTokenFeature`.

#### Code Snippets:
```python
from captum.attr import LayerIntegratedGradients, TextTokenFeature
ig = LayerIntegratedGradients(model, "model.embed_tokens")
llm_attr = LLMGradientAttribution(ig, tokenizer)
inp = TextTokenFeature(" Dave lives in Palm Coast, FL and is a lawyer. His personal interests include ", tokenizer)
llm_attr.attribute(inp)
```
```python
from captum.attr import ShapleyValueSampling, LLMAttribution, TextTemplateFeature, ProductBaselines
svs = ShapleyValueSampling(model)
baselines = ProductBaselines({
    ("name", "pronoun"): [("Sarah", "Her"), ("John", "His")],
    "city": ["Seattle", "Boston"],
    "state": ["WA", "MA"],
    "occupation": ["doctor", "engineer", "teacher", "technician", "plumber"],
})
llm_attr = LLMAttribution(svs, tokenizer)
inp = TextTemplateFeature(
    "{name} lives in {city}, {state} and is a {occupation}. {pronoun} personal interests include ",
    {"name": "Dave", "city": "Palm Beach", "state": "FL", "occupation": "lawyer", "pronoun": "His"},
    baselines=baselines,
)
attr_result = llm_attr.attribute(inp, target="playing golf, hiking, and cooking.")
```

**Comment by vivekmig** [comment]
Hi @MSingh-CSE , thanks for flagging the issue, the classes were renamed to TextTemplateInput and TextTokenInput instead. We will look into updating the paper code snippets. 

You can instead follow the examples provided in the tutorial here https://captum.ai/tutorials/Llama2_LLM_Attribution, which works with the latest codebase.

**Comment by MSingh-CSE** [comment]
Hi @vivekmig,

Thank you for the quick response and clarification. I'll follow the updated examples in the provided tutorial. Closing this issue now.
