### ISSUE TITLE
Docs(minor) - Hyperlink not pointing to the correct webpage

### ISSUE THREAD

**Issue by euler16** [pytorch/captum#128]
The hyperlink "Getting Started with Captum" on [this](https://captum.ai/tutorials/) page is pointing to pytorch.org rather than the correct tutorial page.

**Comment by euler16** [comment]
If you tell me the procedure to make the require changes I can do it and submit a PR

**Comment by vivekmig** [comment]
Hi @euler16, thanks for bringing this to our attention! I've updated the link in this [PR](https://github.com/pytorch/captum/pull/130), it will be fixed when we next update the site.
