### ISSUE TITLE
captum insights port?

### ISSUE THREAD

**Issue by Data-drone** [pytorch/captum#129]
I am running the example application and wanted to ask if it's possible to set a particular port for the app?

Thanks

**Comment by vivekmig** [comment]
Hi @Data-drone, for now, you can set a particular port by changing [this line](https://github.com/pytorch/captum/blob/fc51145bbea7df65fb1fcadb1e5798f8f9833298/captum/insights/api.py#L111) 111 in captum/insights/api.py to add the port option, e.g. "port = start_server(self, blocking, debug, _port=1234)", with the desired port. We will also look into adding this as an option to the render call directly. Thanks!

**Comment by vivekmig** [comment]
This has now also been added as a parameter to render, so if you use master, you can also just add the port= parameter to the visualizer.render() call [here](https://github.com/pytorch/captum/blob/41886dcabeb4f8a4a51dc8e063a7e9c1e0bd53d0/captum/insights/example.py#L94)
