### ISSUE TITLE
Incorrect parameters for _run_forward

### ISSUE THREAD

**Issue by tu-artem** [pytorch/captum#133]
Looks like `additional_forward_args` are passed to `target` parameter

https://github.com/pytorch/captum/blob/d65be282fa1a30ab7aa7645ca4865797266bd603/captum/insights/api.py#L227

https://github.com/pytorch/captum/blob/d65be282fa1a30ab7aa7645ca4865797266bd603/captum/attr/_utils/common.py#L214

**Comment by vivekmig** [comment]
Thanks so much for catching this! I've created a PR with the fix.
