### ISSUE TITLE
is this a typo?

### ISSUE THREAD

**Issue by vainaijr** [pytorch/captum#136]
in readme,
```
Next we will use IntegratedGradients algorithms to assign attribution scores to each input feature with respect to the second target output.
```
and then target=0, is set, should it be first target output?

**Comment by orionr** [comment]
@NarineK or @vivekmig , what are your thoughts on this? Thanks.

**Comment by vivekmig** [comment]
Hi @vainaijr, yes this does look like a typo, thanks for catching it! We will fix it soon.

**Comment by NarineK** [comment]
https://github.com/pytorch/captum/pull/140
