### ISSUE TITLE
With the release of Detectron2 will we see an example on that code base?

### ISSUE THREAD

**Issue by RaymondKirk** [pytorch/captum#139]
Detectron2 has been released https://github.com/facebookresearch/detectron2. It would be very nice to see an example using the default models there.

**Comment by NarineK** [comment]
Thank you for the questions, @RaymondKirk ! Do you want to understand the predictions or do you want to use attributions as an edge detector, how do you see it be used with Detectron2 ?

**Comment by RaymondKirk** [comment]
@NarineK Detectron2 provides a simple way to run popular detection and segmentation models, the forward pass is generally wrapped in a general trainer function, so isn't too trivially used with this package. I think it would help a lot of people understand how to use this package if an example was made with a Detecron2 model (or even a standard PyTorch model), and would really enhance this repo! So my question was mostly wondering if there's any plans for including more advanced deep detectors RCNNs etc in the examples?

**Comment by fmassa** [comment]
@RaymondKirk if the abstractions around detectron2 makes it harder to use with Captum, you could try considering using the detection models in torchvision, which can be imported and used without a trainer / config system.

**Comment by RaymondKirk** [comment]
@fmassa Thank you for your input, I'll close this issue as it was merely a sugestion for enhancement.
