### ISSUE TITLE
BibTeX for citation

### ISSUE THREAD

**Issue by kmario23** [pytorch/captum#161]
Hi folks,
   Is there a proper .bib format available for Captum for the purposes of citation in research papers?

Thanks!

**Comment by NarineK** [comment]
Thank you for asking, @kmario23 !  We don't have a paper out yet. @orionr will propose one.

**Comment by orionr** [comment]
Thanks for asking, @kmario23! For now please use

```
@misc{captum2019github,
  author = {Kokhlikyan, Narine and Miglani, Vivek and Martin, Miguel and Wang, Edward and Reynolds, Jonathan and Reblitz-Richardson, Orion},
  title = {PyTorch Captum},
  year = {2019},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/pytorch/captum}},
}
```
I'll be adding a `CITATION` file shortly as well.

**Comment by haofanwang** [comment]
@orionr Will this paper include other contributors who contributed 100 lines of code as one of its authors (just like tensorflow/cleverhans package)? That would motivate more contributions.

**Comment by orionr** [comment]
Thanks for asking, @haofanwang. Right now the plan (similar to PyTorch) is to have it reference papers and workshops as we have them. However, if people make significant contributions we could definitely talk about it. Closing since we now have the CITATION file.
