### ISSUE TITLE
Cannot install the latest version

### ISSUE THREAD

**Issue by gorogoroyasu** [pytorch/captum#192]
When I tried to install the latest version, I got errors below.

```

    error: can't copy 'captum/insights/frontend/widget/static/extension.js': doesn't exist or not a regular file
    ----------------------------------------

ERROR: Command errored out with exit status 1: /root//.pyenv/versions/3.7.4/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-xijz5fxd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-xijz5fxd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-lcp60r6o/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

It seems to be caused by the wrong js path, `captum/insights/frontend/widget/static/extension.js`.

**Comment by gorogoroyasu** [comment]
I have additional information.
By executing `pip install git+https://github.com/pytorch/captum.git`, I get the above errors.  

But no errors occurred when I execute the commands below.

```
git clone repo && cd repo
pip install -e .
```

I hope this information will help you.

**Comment by NarineK** [comment]
Thank you @gorogoroyasu, for bringing this up. This can be related to one of our recent changes:
https://github.com/pytorch/captum/commit/3a6034a29cea2304e8e948e9b380e0dc3d331dd6#diff-2eeaed663bd0d25b7e608891384b7298R153
https://github.com/pytorch/captum/pull/124
Can you try to install without insights ? We will fix it shortly.

cc: @J0Nreynolds

**Comment by orionr** [comment]
It's likely that this install doesn't run setup.py and so won't build the Captum Insights UI. We'll update the README.md to remove this section.  Thanks for the heads up, @gorogoroyasu.

**Comment by NarineK** [comment]
Thank you, @J0Nreynolds for originally pointing out to it!

**Comment by gorogoroyasu** [comment]
Thank you very much!
