### ISSUE TITLE
DeepLIFT fails when reusing MaxPool2d layer

### ISSUE THREAD

**Issue by EricSpeidel** [pytorch/captum#200]
Using Captum v0.1, so I'm not sure whether this happens with current master.

Something I have noticed when trying out DeepLIFT with CNNs is that reusing MaxPool2d layers instead of explicitly defining one per usage results in RuntimeErrors. Maybe this is related to #199 

For example, consider the [CIFAR10 tutorial](https://captum.ai/tutorials/CIFAR_TorchVision_Interpret). 
If we were to change the network structure to just reuse the **self.pool1** as follows:
```
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool1 = nn.MaxPool2d(2, 2)
        # self.pool2 = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        self.relu1 = nn.ReLU()
        self.relu2 = nn.ReLU()
        self.relu3 = nn.ReLU()
        self.relu4 = nn.ReLU()

    def forward(self, x):
        x = self.pool1(self.relu1(self.conv1(x)))
        x = self.pool1(self.relu2(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = self.relu3(self.fc1(x))
        x = self.relu4(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()
```
Training works just fine, but attributing with DeepLIFT should fail due to size mismatch, such as (unfortunately I can't download the dataset right now, using a local version):
```
~\envs\lib\site-packages\captum\attr\_core\deep_lift.py in <genexpr>(.0)
    282          """
    283         delta_in = tuple(
--> 284             inp - inp_ref for inp, inp_ref in zip(module.input, module.input_ref)
    285         )
    286         delta_out = tuple(

RuntimeError: The size of tensor a (10) must match the size of tensor b (28) at non-singleton dimension 3

```

Is this a bug or necessary convention? Note that reusing pooling layers [actually occurs in official PyTorch tutorials](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#define-a-convolution-neural-network).

**Comment by NarineK** [comment]
Hi @EricSpeidel! Yes, currently we cannot reuse them. If we set hooks on the modules and reuse them it messes things up. I think it would be the best to redefine those.

**Comment by EricSpeidel** [comment]
@NarineK I see, thanks! By the way, is using the modular API necessary for getting correct results? I figure using `torch.nn.functional.max_pool2d` or `torch.nn.functional.relu` would save the hassle of defining lots of modules. It does not error for me, at least.

**Comment by NarineK** [comment]
@EricSpeidel , if you use `torch.nn.functional.relu` it won't apply deeplift rules to it. 
The reason it that since relu is constructed in the forward pass we won't be able to access it while traversing the network.
Here is is small network to play with:
If I define Relu explicitly and traverse, I'll reach Relu but if I use `torch.nn.functional.relu` I won't reach it.
```
import torch.nn as nn
class MyToyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.relu = nn.ReLU()

    def forward(self, x1):
        return self.relu(x1)


def module_func(module):
    print('Hello from ', module)

model = MyToyModel()
model.apply(module_func)

output: Hello from  ReLU()
```
but if I do this, I won't see `Hello from  ReLU()` printout 
```
import torch.nn as nn
class MyToyModel(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x1):
        return torch.nn.functional.relu(x1)


def module_func(module):
    print('Hello from ', module)

model = MyToyModel()
model.apply(module_func)
```

**Comment by NarineK** [comment]
This can change in the future since PyTorch will most probably allow to hook functions and operators as well.

**Comment by NarineK** [comment]
@EricSpeidel, does this answer your question ? If so, can we close the issue ?

**Comment by EricSpeidel** [comment]
@NarineK Yes, thank you for taking the time!
