### ISSUE TITLE
Captum for regression problem

### ISSUE THREAD

**Issue by Hailey-Liu** [pytorch/captum#206]
Hi all,

I am wondering if there are examples that I could learn to use Captum for regression problem as well as using volume data. My problem setting is feeding volume data with WxHxD (64x64x64) to a 3D convnet which has only one neuron in the top layer that output a real number. Thanks.

**Comment by NarineK** [comment]
Hi @Hailey-Liu , if you leave `target=None`, you should be able to attribute the output, a real value, to the inputs and layers( in case of layer algorithms) to the network. We don't have tutorials but we have test models which aren't classification models: 
https://github.com/pytorch/captum/blob/master/tests/attr/helpers/basic_models.py#L16

Have you tried to do attribution and encountered any problems ?

**Comment by Hailey-Liu** [comment]
I see. Thanks for your reply @NarineK . I haven't tried the attribution, still working on familiarizing myself with the Captum.
