### ISSUE TITLE
"RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor "

### ISSUE THREAD

**Issue by giannisginis** [pytorch/captum#212]
Hi, i am trying to interpret my intent classification model by using your "IMDB tutorial" and im facing the following error "RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor
". This error raises during the forward pass of an RNN (lstm) which takes as input a pack sequence (pack_padded_sequence library).

**Comment by NarineK** [comment]
@giannisginis, it depends how you re-defined and trained the model. It looks like failing in the forward pass. Did you retrain it on a different dataset ?

**Comment by NarineK** [comment]
@giannisginis, closing this since we haven't heard from you. Feel free to open a new issue if you have any further questions.
