### ISSUE TITLE
ImportError: cannot import name 'LayerIntegratedGradients'

### ISSUE THREAD

**Issue by rgib37190** [pytorch/captum#231]
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-23-c294f461b5a8> in <module>
     13 
     14 from captum.attr import visualization as viz
---> 15 from captum.attr import IntegratedGradients, LayerConductance, LayerIntegratedGradients
     16 from captum.attr import configure_interpretable_embedding_layer, remove_interpretable_embedding_layer

ImportError: cannot import name 'LayerIntegratedGradients'`

**Comment by NarineK** [comment]
Hi @rgib37190 ! We added LayerIntegratedGradients recently. Do you have the latest version of `captum` library ?

**Comment by rgib37190** [comment]
I use pip install captum yesterday. I don't know whether my version is lastest.

**Comment by rgib37190** [comment]
> Hi @rgib37190 ! We added LayerIntegratedGradients recently. Do you have the latest version of `captum` library ?

I use pip install captum yesterday. I don't know whether my version is lastest.

**Comment by NarineK** [comment]
@rgib37190, we haven't released an new version yet, I think it would be good to follow the instructions under `Manual / Dev Install`. Let us know how it goes.

**Comment by rgib37190** [comment]
> @rgib37190, we haven't released a new version yet, I think it would be good to follow the instructions under `Manual / Dev Install`. Let us know how it goes.
> https://github.com/pytorch/captum

Ok !!! Thanks.

**Comment by NarineK** [comment]
@rgib37190 ! Feel free to close the issue if it fixed the problem! Thank you!
