### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by DecentMakeover** [pytorch/captum#308]
Hello, Thanks for sharing your work.

When trying to run 

        integrated_gradients = IntegratedGradients(model)
        attributions_ig = integrated_gradients.attribute(input, target=pred_label_idx, n_steps=200)

I get the following,

    File "interpret_model.py", line 141, in <module>
        target=torch.tensor(0))
    File "/media/bubbles/ai/ryan/CVPR19-Face-Anti-spoofing/captum/captum/attr/_core/gradient_shap.py", line 262, in attribute
        return_convergence_delta=return_convergence_delta,
    File "/media/bubbles/ai/ryan/CVPR19-Face-Anti-spoofing/captum/captum/attr/_core/noise_tunnel.py", line 282, in attribute
        inputs_with_noise if is_inputs_tuple else inputs_with_noise[0], **kwargs
    File "/media/bubbles/ai/ryan/CVPR19-Face-Anti-spoofing/captum/captum/attr/_core/gradient_shap.py", line 330, in attribute
        self.forward_func, input_baseline_scaled, target, additional_forward_args
    File "/media/bubbles/ai/ryan/CVPR19-Face-Anti-spoofing/captum/captum/attr/_utils/gradient.py", line 103, in compute_gradients
        outputs = _run_forward(forward_fn, inputs, target_ind, additional_forward_args)
    File "/media/bubbles/ai/ryan/CVPR19-Face-Anti-spoofing/captum/captum/attr/_utils/common.py", line 515, in _run_forward
        return _select_targets(output, target)
    File "/media/bubbles/ai/ryan/CVPR19-Face-Anti-spoofing/captum/captum/attr/_utils/common.py", line 461, in _select_targets
        num_examples = output.shape[0]
    AttributeError: 'tuple' object has no attribute 'shape'

The model i use here is not the default resnet but a custom model,whose final layers look like this.

        (1): SEResNeXtBottleneck(
            (conv1): Conv2d(2048, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn1): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (conv2): Conv2d(1024, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
            (bn2): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (conv3): Conv2d(1024, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (relu): ReLU(inplace=True)
            (se_module): SEModule(
            (avg_pool): AdaptiveAvgPool2d(output_size=1)
            (fc1): Conv2d(2048, 128, kernel_size=(1, 1), stride=(1, 1))
            (relu): ReLU(inplace=True)
            (fc2): Conv2d(128, 2048, kernel_size=(1, 1), stride=(1, 1))
            (sigmoid): Sigmoid()
            )
        )
        )
        (fc): Sequential(
        (0): Linear(in_features=2048, out_features=2, bias=True)
        )
        (id_fc): Sequential(
        (0): Linear(in_features=2048, out_features=300, bias=True)
        )
    )
    )

Any ideas as to why this might be happening? 

Thanks in advance.

**Comment by vivekmig** [comment]
Hi @DecentMakeover, from the error, it seems like your model is returning a tuple of output tensors. Our methods generally require a single tensor output for the model and use target as an index to select from this tensor and compute attributions with respect to a single scalar per input example. If the provided targets correspond to indices for one of the output tensors (e.g. index 1 of the output tuple of tensors), you can simply wrap your model in a function as follows, e.g.:
```
def wrapped_model(inp):
    return model(inp)[1]
``` 
Passing this model as the forward_func to IntegratedGradients would then have a single tensor output.

**Comment by DecentMakeover** [comment]
Thanks for the response, ill check this out.

**Comment by DecentMakeover** [comment]
Thanks this works well.
