### ISSUE TITLE
Support for SmoothGrad and Extremal Perturbations

### ISSUE THREAD

**Issue by vinutah** [pytorch/captum#322]
Hi, 

Is there a plan to add support for [SmoothGrad](https://arxiv.org/abs/1706.03825) and [Extremal Perturbations](https://arxiv.org/abs/1910.08485).

Thanks

**Comment by NarineK** [comment]
Hi @vinutah , Thank you for the question!

Smoothgrad is available under Noisetunnel
https://github.com/pytorch/captum/blob/master/captum/attr/_core/noise_tunnel.py#L151

We do not have the implementation of extremal perturbations yet but you can find an implementation of it in:
https://github.com/facebookresearch/TorchRay
