### ISSUE TITLE
Perturbation based attribution for language models

### ISSUE THREAD

**Issue by apepa** [pytorch/captum#327]
Hi, 

Do you consider perturbation-based approaches appropriate for language models, where the input for the model is a sequence of word ids? I'd be particularly happy to hear about Shapley values where the input is supposed to be a feature vector. 

Thank you!

**Comment by NarineK** [comment]
Hi @apepa , That's a good questions. 

With respect to perturbation approaches, I think that for example feature ablation would make sense. In case you can replace the ablated tokens with a padding or any other uninformative token.

In terms of Shapley Values, there is a paper that applied shapely value on text. The paper proposes an optimal computation of the shapely values by taking the structure of the text into consideration.
https://arxiv.org/pdf/1808.02610.pdf

Potentially, you could use shapely sampling and provide your `permutaion_generator` that performs smart / meaningful permutations of word tokens.
https://github.com/pytorch/captum/blob/master/captum/attr/_core/shapley_value.py#L73

Let us know what do you think.

**Comment by NarineK** [comment]
I'll close this for now. Feel free to open a new issue if there are more questions.

**Comment by shaoweiwang2010** [comment]
@NarineK I wonder how the difference of generated text between the original prompt and  perturbated prompt is measured in perturbation-based approach?

**Comment by NarineK** [comment]
@shaoweiwang2010 in the new API for LLM's you can specify what you want your input to be perturbed with. Those are the baselines. You can find more about it in this tutorial: https://github.com/pytorch/captum/blob/master/tutorials/Llama2_LLM_Attribution.ipynb
