### ISSUE TITLE
Unable to use LayerIntegratedGradients when embedding multiple sentences via BERT at once

### ISSUE THREAD

**Issue by ngillani** [pytorch/captum#329]
Hi!  I have a model I've trained to take as input 100 sentences together (max 30 words each), embed them separately using BERT, then take the mean embedding and feed through a feedforward network to make a prediction for a regression task.  Each group of 100 sentences belongs to a document that we are trying to predict some values based on.  

I am trying to use Captum's layer integrated gradients with this model, but unfortunately, seem unable to get it to work.  I run out of memory even when I lower n_steps to be the same as the batch size I used for training (16 — i.e., 16 groups of 100 sentences at once).  When I try to use the internal_batch_size argument (e.g. setting n_steps to 48 and internal_batch_size to 12), I get dimension mismatch error:

RuntimeError: The size of tensor a (12) must match the size of tensor b (1200) at non-singleton dimension 0

I was able to get layer integrated gradients to work for just one sentence (without lowering the default n_steps) ... though unfortunately, this is does not capture the context from a document that we used during training.

Any guidance or ideas would be much appreciated.  Please let me know if I can help clarify or add details anywhere.  Thank you!

**Comment by ngillani** [comment]
Nevermind — I think I figured it out — my underlying model was operating with inputs containing one extra dimension.  I created a wrapper class to remove this and it seems to work.  Sorry for the false alarm!

**Comment by clintonlau** [comment]
@ngillani Looking for some guidance. I have a model very similar to yours that takes multiple sentences as inputs to do classification on one instance using BERT. 

Assuming that you used `LayerIntegratedGradients(forward_func=..., layer=...)`, can I ask what your `forward_func` and `layer` look like? Currently, my `forward_func` takes in batch-wise tensors (BERT's inputs_ids, token_type_ids, and attention_mask), while the layer is `mode.bert.embeddings`. However, I get the error:

RuntimeError: The size of tensor a (530) must match the size of tensor b (53) at non-singleton dimension 0

where n_steps=10 and this one instance has 53 sentences. tensor a is for some reason n_steps*n_sentences.

My attribute function is as followed, where input_ids, token_type_ids, attention_masks, ref_input_ids all have shape(1, 53, max_n_tokens). num_interview_rounds denotes a list of n_sentences for this batch, in this case [53].

`attr, delta = lig.attribute(inputs=input_ids,
                                baselines=ref_input_ids,
                                additional_forward_args=(token_type_ids, attention_masks, num_interview_rounds.to(device)), #.unsqueeze(0).to(device),
                                n_steps=10,
                                return_convergence_delta=True)`

Any insights would be very much appreciated! @NarineK if you have any tips, that would be very helpful too :)
