### ISSUE TITLE
How to try out different interpretation methods for interpretation of BertForSequenceClassification?

### ISSUE THREAD

**Issue by davidefiocco** [pytorch/captum#354]
Hello!

I am looking for other ways to intepret a binary sentiment BertForSequenceClassification model beyond the `LayerIntegratedGradients` model used in @NarineK code at https://github.com/pytorch/captum/issues/311#issuecomment-612460705 adapted from the demo https://captum.ai/tutorials/Bert_SQUAD_Interpret 
I am looking for more as `LayerIntegratedGradients` doesn't seem entirely satisfactory (see https://github.com/pytorch/captum/issues/311 for more background on this).

Can someone point me to resources to
- What methods among those in https://captum.ai/docs/algorithms_comparison_matrix are expected to be apt/most promising for interpretation? From https://github.com/pytorch/captum/issues/347, looks like `LayerDeepLift` could be one.
- What parts of the code are expected to be modified to try out different methods?

Thanks!

**Comment by NarineK** [comment]
Hi @davidefiocco, we have similar issue opened here #347. Maybe we can consolidate these two ?

**Comment by davidefiocco** [comment]
Sure! Feel free to close, even though I meant this issue as a way to collect more high-level tips and not necessarily tied to `LayerDeepLift`, and in particular: 
- How can one switch from one method to another in captum (is it easy, or does it require substantial code changes), when using BERT
- What's worth trying out with BERT trusting what's currently known in terms of "BERTology".
Thanks!

**Comment by NarineK** [comment]
Provided an answer here: https://github.com/pytorch/captum/issues/347#issuecomment-616864035

**Comment by davidefiocco** [comment]
OK @NarineK ! From what I understand, switching from one interpretation method to another can well need reworking of the code (trying out different methods is not as simple as changing a couple of lines of code).
