### ISSUE TITLE
Sequence to Sequence models

### ISSUE THREAD

**Issue by pjvalla** [pytorch/captum#356]
Do you have examples for sequence to sequence models?

**Comment by NarineK** [comment]
@pjvalla, we had an initial example of seq2seq here: https://github.com/pytorch/captum/pull/100
This was very long time ago. Our API has changed only a bit, so you should still be able to implement it.

**Comment by pjvalla** [comment]
Thanks so much!

**Comment by vivekmig** [comment]
Closing this issue, but feel free to create another issue if you have further questions on Sequence to Sequence models!
