### ISSUE TITLE
How to interpret BERTSequenceClassification?

### ISSUE THREAD

**Issue by jiajinghu19** [pytorch/captum#373]
I'm using Captum to interpret a BERT sequence classification model and I'm referring to the tutorial here:
https://captum.ai/tutorials/Bert_SQUAD_Interpret

I made minor modifications as below:

```
encoded_dict = tokenizer.encode_plus(
                          text,           
                          add_special_tokens = True, # Add '[CLS]' and '[SEP]'
                          max_length = 512,         
                          pad_to_max_length = True,
                          return_attention_mask = True,   
                          return_tensors = 'pt',   
                     )

input_ids = encoded_dict['input_ids'].to(device)
attention_mask = encoded_dict['attention_mask'].to(device)

def custom_forward(inputs, token_type_ids=None, attention_mask=None):
    outputs = model_load(input_ids=input_ids, token_type_ids=None, attention_mask=attention_mask)
    preds = outputs[0]
    return torch.softmax(preds, dim = 1)[0]

lig = LayerIntegratedGradients(custom_forward, model.bert.embeddings)
attributions, delta = lig.attribute(inputs=input_ids,
                                  additional_forward_args=(token_type_ids, attention_mask), # revise this
                                  return_convergence_delta=True)
```

I got this error after running the code:
```
RuntimeError: forward hooks should never return any values, but '<function LayerIntegratedGradients.attribute.<locals>.gradient_func.<locals>.layer_forward_hook at 0x7fc0f6338378>'didn't return None
```

Does anyone have an idea of why? Thank you!

**Comment by jiajinghu19** [comment]
Also when I run the demo code and didn't change anything, I got the following error:

```

lig = LayerIntegratedGradients(squad_pos_forward_func, model.bert.embeddings)

attributions_start, delta_start = lig.attribute(inputs=input_ids,
                                  baselines=ref_input_ids,
                                  additional_forward_args=(token_type_ids, position_ids, attention_mask, 0),
                                  return_convergence_delta=True)
attributions_end, delta_end = lig.attribute(inputs=input_ids, baselines=ref_input_ids,
                                additional_forward_args=(token_type_ids, position_ids, attention_mask, 1),
                                return_convergence_delta=True)


RuntimeError: forward hooks should never return any values, but '<function LayerIntegratedGradients.attribute.<locals>.gradient_func.<locals>.layer_forward_hook at 0x7fd11ea22378>'didn't return None
```

**Comment by vivekmig** [comment]
Hi @jiajinghu19 , it seems this issue might be related to using an older version of PyTorch, which didn't support hooks. Can you add `print(torch.__version__)` to your code to check what version you are using? Captum requires at least PyTorch version 1.2, so you may need to upgrade it.

**Comment by jiajinghu19** [comment]
Thank you @vivekmig . That problem was solved after I updated pytorch version. But I got all 0s for the output attention and delta. Have you seen this before? Thanks!

**Comment by vivekmig** [comment]
Hi @jiajinghu19 , that seems odd, can you double-check if the model output of custom_forward seems appropriate (non-zero)? Are you seeing this with just the tutorial code or only after the modification?

**Comment by jiajinghu19** [comment]
@vivekmig Yes the custom forward outputs a non-zero tensor, just like the tutorial code. The tutorial code runs fine.

Here's the output of the tutorial forward function:

```
squad_pos_forward_func(input_ids, token_type_ids, position_ids, attention_mask)

Out[196]: tensor([0.1571], device='cuda:0', grad_fn=<MaxBackward0>)
```

And here is the output of the custom_forward:

```
custom_forward(input_ids, attention_mask)

Out[198]: tensor([0.9908], device='cuda:0', grad_fn=<MaxBackward0>)
```

**Comment by jiajinghu19** [comment]
@vivekmig I found a typo. Sorry for the dumb question. Problems solved. Thank you!!!

**Comment by vivekmig** [comment]
Great, I'm glad the problem is resolved!

**Comment by sajjadriaj** [comment]
Hello @jiajinghu19 I am having the same issue with having all 0  attributions. How did you resolve this?

**Comment by jiajinghu19** [comment]
@sajjadriaj I got all 0 attributions because my function was referring to a data outside of the function, not the one passed in from attributes. It was a typo.

**Comment by sajjadriaj** [comment]
Not sure what I am doing wrong :( this is what I am doing at the moment. 

```python
from transformers import RobertaTokenizer, RobertaConfig, RobertaForSequenceClassification, RobertaModel
import torch
import torch.nn as nn
import torch.nn.functional as F

# Imports from our module
import data_science.utility_functions as utilities

# import from Captum library
from captum.attr import visualization as viz
from captum.attr import IntegratedGradients, LayerConductance, LayerIntegratedGradients, TokenReferenceBase
from captum.attr import configure_interpretable_embedding_layer, remove_interpretable_embedding_layer

#load model
model = RobertaForSequenceClassification.from_pretrained(model_path)
tokenizer = RobertaTokenizer.from_pretrained(model_path)
model.eval()
model.zero_grad()

def custom_forward_func(input_ids, masks):
    out = model(input_ids, token_type_ids=None, attention_mask = masks)[0]
    out = F.softmax(out, dim=1)[0]
    return out

article = "Manchester United is one of the most successful English football club in the history. The club has been performing poorely since their stark manager Alex Ferguson retired. However recently appointed manager, Ole is showing signs of promise in the rebuilding process."
evidence= "Ole is doing a great job at Manchester United"

input_ids, masks = utilities.encode_sentences(tokenizer, [article], [evidence])

lig = LayerIntegratedGradients(custom_forward_func, model.roberta.embeddings)
#token_reference = TokenReferenceBase(reference_token_idx=tokenizer.pad_token_id)
#reference_indices = token_reference.generate_reference(sequence_length = 512, device = device).unsqueeze(0)

def summarize_attributions(attributions):
    attributions = attributions.sum(dim=-1).squeeze(0)
    attributions = attributions / torch.norm(attributions)
    return attributions

def visualize(attributions, delta, evidence, article, pred):
    attributions_summary = summarize_attributions(attributions)
#     all_tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(evidence))+ tokenizer.convert_ids_to_tokens(tokenizer.encode(article))
    all_tokens = tokenizer.encode(evidence) + tokenizer.encode(article)
    all_tokens = [tokenizer.decode(x) for x in all_tokens]
    
    print("Predictions:", pred.detach().tolist())
    print('\n')
    prediction_val = pred.max(0).values
    class_idx = pred.max(0).indices
    true_label = label_mapper[class_idx.item()]
    
    vis_data = viz.VisualizationDataRecord(attributions_summary,
                                            prediction_val,
                                            class_idx,
                                            true_label,
                                            "2",
                                            attributions_summary.sum(),
                                            all_tokens,
                                            delta)

    viz.visualize_text([vis_data])

attr, delta = lig.attribute(inputs=input_ids, additional_forward_args=(masks), return_convergence_delta=True, n_steps=20)

out = custom_forward_func(input_ids, masks)[0]
visualize(attr, delta, evidence, article, out)


```

**Comment by jiajinghu19** [comment]
Have you checked the output of ```custom_forward_func``` is appropriate? Otherwise, check the pytorch version and Captum version

**Comment by sajjadriaj** [comment]
I did, here is the output of the forward function:

`tensor([9.9981e-01, 1.5888e-04, 3.1226e-05, 2.8697e-06], grad_fn=<SelectBackward>)`

This is what I get in the attributions:

`tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [-0., 0., -0.,  ..., 0., 0., -0.],
         [-0., 0., -0.,  ..., 0., -0., -0.],
         ...,
         [-0., 0., -0.,  ..., -0., -0., -0.],
         [-0., 0., -0.,  ..., -0., -0., -0.],
         [-0., -0., -0.,  ..., 0., -0., -0.]]], grad_fn=<MulBackward0>)`

**Comment by jiajinghu19** [comment]
For me the forward function only returns a single value, and so does the output of tutorial. Yours has 4 values. I don't know if that's why

**Comment by sajjadriaj** [comment]
Cool, thanks for pointing it out!

**Comment by vivekmig** [comment]
Hi @sajjadriaj ,

I would also recommend double-checking this line:
`    out = F.softmax(out, dim=1)[0]
`
Make sure that if your input includes a batch of multiple examples (first dimension of input_ids is > 1), then the output of the forward function has the same first dimension. I think by indexing with 0 here, it might be selecting only the first example output. This is necessary because IntegratedGradients is internally creating a "batch" to compute scaled versions of the input.

The forward function should return values for each input example. If there are multiple values for each input, such as the 4 outputs in your case, you can use the targets argument to select the particular output for attribution. Hope this helps!

**Comment by sajjadriaj** [comment]
Thank you @vivekmig I understand the steps now!

**Comment by shanto-Rahman** [comment]
Hi, 
How did you fix the all zero gradients. I am also having the same issue.

**Comment by shanto-Rahman** [comment]
I am getting the zero for all the tokens except the first one. I dont understand why it happened. 

['<s>', '@', 'Test', 'Ċ', 'public', 'Ġvoid', 'Ġtest', 'Rec', 'over', 'Ex', 'pired', 'Mess', 'ages', '()', 'Ġthrows', 'ĠException', 'Ġ{', 'Ċ', 'Active', 'MQ', 'Connection', 'Factory', 'Ġfactory', 'Ġ=', 'Ġnew', 'ĠActive', 'MQ', 'Connection', 'Factory', '(', 'Ġ)', 'Ġ;', 'Ċ', 'connection', 'Ġ=', 'Ġfactory', '.', 'create', 'Connection', '();', 'Ċ', 'connection', '.', 'start', '();', 'Ċ', 'session', 'Ġ=', 'Ġconnection', '.', 'create', 'Session', '(', 'false', ',', 'ĠAUT', 'O', '_', 'ACK', 'NOW', 'LED', 'GE', ');', 'Ċ', 'produ', 'cer', 'Ġ=', 'Ġsession', '.', 'create', 'Produ', 'cer', '(', 'dest', 'ination', ');', 'Ċ', 'produ', 'cer', '.', 'set', 'Time', 'To', 'Live', '(', '2000', ');', 'Ċ', 'produ', 'cer', '.', 'set', 'Delivery', 'Mode', '(', 'P', 'ERS', 'IST', 'ENT', ');', 'Ċ', 'Thread', 'Ġproducing', 'Thread', 'Ġ=', 'Ġnew', 'ĠThread', '(""', 'Produ', 'cing', 'ĠThread', '"")', 'Ġ{', 'Ċ', 'public', 'Ġvoid', 'Ġrun', '()', 'Ġ{', 'Ċ', 'try', 'Ġ{', 'Ċ', 'int', 'Ġi', 'Ġ=', 'Ġ0', ';', 'Ċ', 'while', 'Ġ((', 'i', '++)', 'Ġ<', 'Ġ1000', ')', 'Ġ{', 'Ċ', 'Message', 'Ġmessage', 'Ġ=', 'Ġ(', 'use', 'Text', 'Message', ')', 'Ġ?', 'Ġsession', '.', 'create', 'Text', 'Message', '(""', 'test', '"")', 'Ġ:', 'Ġsession', '.', 'create', 'Object', 'Message', '(""', 'test', '"");', 'Ċ', 'produ', 'cer', '.', 'send', '(', 'message', ');', 'Ċ', '}', 'Ċ', 'produ', 'cer', '.', 'close', '();', 'Ċ', '}', 'Ġcatch', 'Ġ(', 'Throw', 'able', 'Ġex', ')', 'Ġ{', 'Ċ', 'ex', '.', 'print', 'Stack', 'Tr', 'ace', '();', 'Ċ', '}', 'Ċ', '}', 'Ċ', '};', 'Ċ', 'producing', 'Thread', '.', 'start', '();', 'Ċ', 'producing', 'Thread', '.', 'join', '();', 'Ċ', 'Dest', 'ination', 'View', 'M', 'Be', 'an', 'Ġview', 'Ġ=', 'Ġcreate', 'View', '(', 'dest', 'ination', ');', 'Ċ', 'LOG', '.', 'info', '((', '((', '((', '((', '((', '(""', 'Stats', ':', 'Ġsize', ':', 'Ġ""', 'Ġ+', 'Ġview', '.', 'get', 'Queue', 'Size', '())', 'Ġ+', 'Ġ"",', 'Ġen', 'que', 'ues', ':', 'Ġ""', ')', 'Ġ+', 'Ġview', '.', 'get', 'De', 'queue', 'Count', '())', 'Ġ+', 'Ġ"",', 'Ġde', 'que', 'ues', ':', 'Ġ""', ')', 'Ġ+', 'Ġview', '.', 'get', 'De', 'queue', 'Count', '())', 'Ġ+', 'Ġ"",', 'Ġdispatched', ':', 'Ġ""', ')', 'Ġ+', 'Ġview', '.', 'get', 'Dispatch', 'Count', '())', 'Ġ+', 'Ġ"",', 'Ġinf', 'light', ':', 'Ġ""', ')', 'Ġ+', 'Ġview', '.', 'get', 'In', 'Flight', 'Count', '())', 'Ġ+', 'Ġ"",', 'Ġexp', 'iries', ':', 'Ġ""', ')', 'Ġ+', 'Ġview', '.', 'get', 'Ex', 'pired', 'Count', '());', 'Ċ', 'LOG', '.', 'info', '(""', 'st', 'opping', 'Ġbroker', '"");', 'Ċ', 'bro', 'ker', '.', 'stop', '();', 'Ċ', 'bro', 'ker', '.', 'wait', 'Until', 'St', 'opped', '();', 'Ċ', 'Thread', '.', 'sleep', '(', '5000', ');', 'Ċ', 'LOG', '.', 'info', '(""', 're', 'cover', 'ing', 'Ġbroker', '"");', 'Ċ', 'final', 'Ġboolean', 'Ġdelete', 'All', 'Mess', 'ages', 'Ġ=', 'Ġfalse', ';', 'Ċ', 'bro', 'ker', 'Ġ=', 'Ġcreate', 'Bro', 'ker', '(', 'delete', 'All', 'Mess', 'ages', ',', 'Ġ5000', ');', 'Ċ', 'Wait', '.', 'wait', 'For', '(', 'new', 'ĠWait', '.', 'Condition', '()', 'Ġ{', 'Ċ', 'public', 'Ġboolean', 'Ġis', 'Sat', 'is', 'ified', '()', 'Ġthrows', 'ĠException', 'Ġ{', 'Ċ', 'bo', 'olean', 'Ġresult', 'Ġ=', 'Ġfalse', ';', 'Ċ', 'try', 'Ġ{', 'Ċ', 'Dest', 'ination', 'View', 'M', 'Be', 'an', 'Ġview', 'Ġ=', 'Ġcreate', 'View', '(', 'dest', 'ination', ');', 'Ċ', 'LOG', '.', 'info', '((', '((', '((', '((', '((', '(""', 'Stats', ':', 'Ġsize', ':', 'Ġ""', 'Ġ+', 'Ġview', '.', 'get', 'Queue', 'Size', '())', 'Ġ+', 'Ġ"",', 'Ġen', 'que', 'ues', ':', 'Ġ""', ')', 'Ġ+', 'Ġview', '.', 'get', 'De', 'queue', 'Count', '())', 'Ġ+', 'Ġ"",', 'Ġde', 'que', 'ues', ':', 'Ġ""', ')', 'Ġ+', 'Ġview', '.', 'get', 'De', 'queue', 'Count', '())', 'Ġ+', 'Ġ"",', 'Ġdispatched', ':', 'Ġ""', ')', 'Ġ+', 'Ġview', '.', 'get', 'Dispatch', 'Count', '())', 'Ġ+', 'Ġ"",', 'Ġinf', 'light', ':', 'Ġ""', ')', 'Ġ+', 'Ġview', '.', 'get', 'In', 'Flight', 'Count', '())', 'Ġ+', 'Ġ"",', 'Ġexp', 'iries', ':', 'Ġ""', ')', 'Ġ+', 'Ġview', '.', 'get', 'Ex', 'pired', 'Count', '());', 'Ċ', 'result', 'Ġ=', 'Ġview', '.', 'get', 'Queue', 'Size', '()', 'Ġ==', 'Ġ0', ';', 'Ċ', '}', 'Ġcatch', 'Ġ(', 'Exception', 'Ġnot', 'Found', 'Ex', 'pected', 'On', 'Slow', 'Mach', 'ines', ')', 'Ġ{', 'Ċ', '}', 'Ċ', 'return', 'Ġresult', ';', 'Ċ', '}', 'Ċ', '});', 'Ċ', 'view', 'Ġ=', 'Ġcreate', 'View', '(', 'dest', 'ination', ');', 'Ċ', 'assert', 'Equ', 'als', '(""', 'Ex', 'pect', 'Ġempty', 'Ġqueue', ',', 'ĠQue', 'ue', 'Size', ':', 'Ġ"",', 'Ġ0', ',', 'Ġview', '.', 'get', 'Queue', 'Size', '());', 'Ċ', 'assert', 'Equ', 'als', '(""', 'all', 'Ġde', 'que', 'ues', 'Ġwere', 'Ġexpired', '"",', 'Ġview', '.', 'get', 'De', 'queue', 'Count', '(),', 'Ġview', '.', 'get', 'Ex', 'pired', 'Count', '());', 'Ċ', '}', 'Ċ', 'while', '(', 'false', '){', 'Ċ', 'Ġint', 'Ġi', 'Ġ=', 'Ġ0', ';', 'Duration', 'Ġduration', 'Ġ=', 'ĠDuration', '.', 'between', '(', 'start', 'Time', ',', 'Ġend', 'Time', ');', 'Ċ', 'ĠDat', 'etime', 'Ġdate', '=', 'current', 'Date', ';', 'Ġ', 'Ċ', '}', 'Ċ', '</s>',]","[-1.2969460386345106, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
