### ISSUE TITLE
Captum_NeurIPS_2019_final.key

### ISSUE THREAD

**Issue by peter197321** [pytorch/captum#376]
How to see "Captum_NeurIPS_2019_final.key" ? What browser plugin or app used to view this material?

**Comment by bilalsal** [comment]
Hi Peter,
this file is created using KeyNote (the MacOS presentation maker, similar to PowerPoint).
Hope this helps,
Bilal

**Comment by peter197321** [comment]
if you can advise - on Win10 side - how to view?

**Comment by peter197321** [comment]
I got that converted to ppt and view via PowerPoint - thank you.
