### ISSUE TITLE
Target should identify a single element in the model output

### ISSUE THREAD

**Issue by MandySuperTT** [pytorch/captum#377]
Hello!
Thanks for sharing this awesome library!

When I was using `FeatureAblation` method in my code, I always got this error:

> attribution_map = ablator.attribute(img.unsqueeze(0), target=12,feature_mask=feature_mask)
AssertionError: Target should identify a single element in the model output

I have `13` different classes and my output size is `[1,13,756,1344]`, I followed tutorial of `Feature Ablation` but still got this error. I've put so much time trying to fix this problem but I had no clue how to deal with it.

Could anyone please help me?

Below is my code, I hope to compute the influence of each feature group in our image on the target responsible for the `class 12`:
```python
feature_mask = np.array(mask_img.getdata()).reshape(1, 1, mask_img.size[1], mask_img.size[0])
print(np.unique(feature_mask))
# [  0   1  2  4  5  9  10  12]
feature_mask[feature_mask == 4] = 3 
feature_mask[feature_mask == 5] = 4 
feature_mask[feature_mask == 9] = 5 
feature_mask[feature_mask == 10] = 6
feature_mask[feature_mask == 12] = 7

ablator = FeatureAblation(model)
# where the input of my model is [1,3,756,1344] and output is [1,13,756,1344]
attribution_map = ablator.attribute(img.unsqueeze(0),target=12,feature_mask=torch.tensor(feature_mask)) 
```

Any response will be appreciated!

**Comment by bilalsal** [comment]
Hi @MandySuperTT,

the model in the Feature Ablation tutorial is a simple classifier, whereas your model seems to be a segmentation model.
Currently, Captum expects you to specify one scalar output to compute attribution with respect to. This would be a single pixel in your output, which is probably less useful to attribute with respect to.
Other users have had similar situation (see #119 and #343).
We are considering providing a dedicated attribution scheme for segmentation models, an open problem that AFAIK is not covered by the literature.
Meanwhile you can consider simple solutions like defining a wrapper to your model that sums up the 2D map per class, yielding a truly 13-dimensional output. Then when you can specify target=12, Captum will be able to compute the attribution for it, e.g. using FeatureAblation or other suited algorithms such as Integrated Gradients or Occlusion (see https://captum.ai/tutorials/Resnet_TorchVision_Interpret for examples).
```
def wrapper(inp):
    return torch.sum(model(inp), axis = (2, 3))

ablator = FeatureAblation(wrapper)
occlusion = Occlusion(wrapper)
attribution_ab = ablator.attribute(img.unsqueeze(0),target=12,feature_mask=torch.tensor(feature_mask)) 
attributions_occ = occlusion.attribute(img.unsqueeze(0),
                                       strides = (3, 8, 8)
                                       target=12,
                                       sliding_window_shapes=(3,15, 15), # choose size suited to occlude your image objects
                                       baselines=0)
```

Hope this helps, let us know if you have further questions!
