### ISSUE TITLE
conda versioning?

### ISSUE THREAD

**Issue by Data-drone** [pytorch/captum#381]
when I install with the conda command, it downgrades to pytorch 1.4 with torchvision 0.5.0? but if I just conda install pytorch and torchvision I get pytorch 1.5 with torchvision 0.6.0

**Comment by vivekmig** [comment]
Hi @Data-drone, I tried reproducing this, but simply running `conda install captum -c pytorch` does seem to install pytorch 1.5 and torchvision 0.6.0 appropriately for me in a new conda environment. Can you share the output of the conda install command with the install / downgrade package list? That might be helpful to debug further.

**Comment by NarineK** [comment]
@Data-drone, do you have more questions regarding this issue ? If not, can we, please, close it?
