### ISSUE TITLE
Can I use Captum for pair of sentences in BertForSequenceClassification

### ISSUE THREAD

**Issue by vinidixit** [pytorch/captum#388]
Hi,

I am trying to interpret one of the GLUE based model for sentence pair similarity task. And, I need to see which features/words in each sentence are taking part in getting similarity score 0(no match) or 1(match). My model is trained using BertForSequenceClassification with MRPC dataset where Feature : (text1, text2) and Label: (0/1)

Could anyone please direct me to visualise this model?

Thanks in advance!

**Comment by NarineK** [comment]
Hi @vinidixit,

thank you for reaching out to us with your questions.
Yes, you should be able to attribute to each pair of the text in the sentence.
Here is a tutorial on: https://captum.ai/tutorials/Bert_SQUAD_Interpret 
and here you can also find an example of BertForSequenceClassification. https://github.com/pytorch/captum/issues/311
Let us know if you have any specific questions with that specific example.

Thank you,
Narine


Thank you,
Narine

**Comment by NarineK** [comment]
Closing this issue. We can reopen if necessary
