### ISSUE TITLE
IG with BiGRU on sentence embeddings

### ISSUE THREAD

**Issue by doppler21** [pytorch/captum#409]
Hi,
I am trying to use 2 layer BiGRU on the top of sentence embeddings and use Captum's IG method to get the attribution scores for these embeddings.
I am wondering whether it is possible to use integrated gradients to get the attribution for an embedding directly. Also as I don't have any kind of tokens, I am directly feeding the sentence embedding into the BiGRU, is it still possible (because I have seen most of the implementations require an embedding layer and a vocabulary).

**Comment by NarineK** [comment]
Hi @doppler21, I have never used  BiGRUs before but I assume that you can apply IntegratedGradients directly on the embedding layer without having to do any mappings for the tokens. It should be even easier with embeddings without having to map to the tokens. Have you tried that ?

**Comment by doppler21** [comment]
Okay I will try that and report back if I get into any issues. Thanks @NarineK

**Comment by NarineK** [comment]
Closing this issue! We can reopen it if there are open questions.
