### ISSUE TITLE
Example docs incorrect for DeepLiftShap

### ISSUE THREAD

**Issue by willprice** [pytorch/captum#420]
The [docs](https://captum.ai/api/deep_lift_shap.html) show an example for DeepLiftShap:
![image](https://user-images.githubusercontent.com/966205/86367220-9416bb00-bc73-11ea-9dd3-db8552c7d59e.png)
however, `attribute` needs to take a `baselines` arg which is non-optional.

**Comment by NarineK** [comment]
Thank you for catching it @willprice ! That's right, we need to pass baselines. Feel free to create a PR or we will fix it :) 

Thank you :)

**Comment by willprice** [comment]
No problem. I would put a PR in, but as I couldn't get DeepLiftShap or DeepLift working I wouldn't know what the example should be. Is it possible to feed a batch tensor of examples to DeepLift and a selection of baselines (where the batch sizes don't match, say I have 32 examples in my batch to explain and 100 baselines I want to use for each example)? This seems to work fine for IntegratedGradients. There's some inconsistency between the two in how they handle their baselines, but it's not clear to me if that's a bug, or a limitation of DeepLift

**Comment by NarineK** [comment]
Thank you, @willprice! For DeepLiftShap the dimensions for the input and baseline don't have to match. DeepLiftShap looks into each (baseline, input) pair and averages the attributions for each input example across all baselines.

For DeepLift the dimensions for input and baseline should match. DeepLift looks into one baseline only - in this case the dimensions should match. Integrated Gradients and DeepLift have the same concept of selecting baselines. For both cases the batch size for input and baseline should match.

If you provide an example I might be able to help more but that's the general idea.

**Comment by NarineK** [comment]
@willprice, do you have more questions regarding the documentation ? If not, can we, please, close it ?

**Comment by willprice** [comment]
Hi @NarineK,
Feel free to close, thanks for your help!

**Comment by RossDeVito** [comment]
The original docs are still unchanged
