### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0) on tutorial Interpreting text models: IMDB sentiment analysis

### ISSUE THREAD

**Issue by Seraphli** [pytorch/captum#422]
Got a `ValueError: not enough values to unpack (expected 2, got 0)` error on `test, _ = test.split(split_ratio = 0.04)`. 
Package version:
captum==0.2.0
spacy==2.3.0
torchtext==0.6.0
And:
en-core-web-sm-2.3.0

**Comment by bilalsal** [comment]
Hi @Seraphli,

It looks like test is already empty, hence split fails to return two values.
Maybe try to check how test is computed in your case and what makes it become empty?

**Comment by Seraphli** [comment]
Hi, @bilalsal I was just trying the tutorial `Interpreting text models: IMDB sentiment analysis` https://captum.ai/tutorials/IMDB_TorchText_Interpret
I download the python script and try to run this. I didn't modify anything. Here is the context.
```
train, test = torchtext.datasets.IMDB.splits(text_field=TEXT,
                                      label_field=Label,
                                      train='train',
                                      test='test',
                                      path='data/aclImdb')
test, _ = test.split(split_ratio = 0.04)
```

**Comment by bilalsal** [comment]
Hi @Seraphli ,

Did you download IMDB dataset under` 'data/aclImdb'`?

I also realize that PyText API now use `root` to specify this directory instead of `path`
https://pytorch.org/text/datasets.html#imdb

 Hope by that you get non-empty collections in `train` and `test`.

Hope this helps

**Comment by Seraphli** [comment]
Thanks for the advice. I will try that out.
