### ISSUE TITLE
Possibility to configure IG to support batch_first=False

### ISSUE THREAD

**Issue by heytitle** [pytorch/captum#427]
For text classification problems, the input typically has 3 dimensions (`batch_size x seq_length x emb_dim` or `B x S x E` ). 

In Pytorch, LSTMs can take the input with either
- `B x S x E` (`batch_first=True`)
- `S x B x E` (`batch_first=False`)

and, the latter is the default value.

For frameworks such as `TextAttack`, the pertained LSTMs they provide are trained with the latter convention. This causes problems  when using Captum's IG.

To illustrate, let's assume we have a LSTM trained with the `S x B x E` convention, and we explain it using IG with `50` steps. IG will expand the input tensor along the first dimension, yielding a new tensor with `(Sx50) x 1 x E` instead of `S x 50 x E`.

If I'm not mistaken, the code that is responsible for this expansion is https://github.com/pytorch/captum/blob/dfee772d943ba8c06a273345ef164801be66c244/captum/attr/_core/integrated_gradients.py#L326.

**Question:**  What would be the most convenient way to solve the issue?

**Comment by vivekmig** [comment]
Hi @heytitle , one possible workaround for this issue might be to create a wrapper function which converts the tensor shape from the second type to the first. An example of this would be something like this:

```
model # takes S x B x E embedding
def wrapper_forward(inp_embedding): # B x S x E embedding
    return model(inp_embedding.permute(1, 0, 2)) # transform input to S x B x E before inputting to model
ig = IntegratedGradients(wrapper_forward)
ig.attribute(embedding_input) # Shape of embedding_input B x S x E
```
Would this work for your use case?

**Comment by efatmae** [comment]
Hi all, 
I'm having hard time trying to use custom LSTM class with text classification but I'm facing a problem.

**Comment by heytitle** [comment]
@efatmae: the approach @vivekmig suggested approve works for me. Maybe you can try that?

**Comment by heytitle** [comment]
@vivekmig : thanks again for the suggestion; it worked. I'll close this issue for now.
