### ISSUE TITLE
autoencoder

### ISSUE THREAD

**Issue by rojinsafavi** [pytorch/captum#435]
Hello,
I was wondering if Captum can be used for autoencoder structures?

**Comment by heytitle** [comment]
I guess that's possible as long as you can trace the input and output. Depending on your input and output dimension, the visualization part might be a bit tricky. Would you mind sharing a bit about  that?

**Comment by rojinsafavi** [comment]
Sure, Basically I am trying to build a variational autoencoder and would like to interpret the latent space(like what input features contribute the most to each node in the latent space)

**Comment by heytitle** [comment]
In this case, you might need to intercept the latent output `enc(x)` somehow. iirc, `enc(x)` is in a form of `mu + sigma * epsilon`. I'm not sure whether you want to interpret `enc(x)` or `mu` and `sigma`; the latter case might also be interesting.

**Comment by rojinsafavi** [comment]
Thanks for the guidance, I will let you know if I have further questions!

**Comment by sandrasteyaert42** [comment]
Hi @rojinsafavi -- I am actually trying to do the same thing as what you were asking about. I was wondering if you might a notebook or some additional guidance on how you analyzed this using captum?
