### ISSUE TITLE
AssertionError: Attributions tensor and the end_point must match on the first dimension but found attribution: 4 and end_point: 1

### ISSUE THREAD

**Issue by mainulquraishi** [pytorch/captum#457]
Please, pardon me for my silly questions. 
I am doing regression on documents. So the input is a document and the output is a single digit. 
My input dimension  (to embedding layer) [1,4,41]. Here, 1=one example, 4=4 sentences and 41= 41 words per sentence (padded). After embedding, the dimension would be [1,4,41,300]. Token reference (reference_indices) dimention=[1,4,41].
Now, I got the mentioned error. Here is the complete error trace.

I don't understand, what is the end_point? Also, could you please explain the error a little bit. 

```
----> 2 interpret_sentence(model, doc)
      3 # for tv_batch in source_test_dataloader:
      4 #     xtv_batch=tv_batch[0]
      5 #     ytv_batch=tv_batch[1]

<ipython-input-30-177baed53bc3> in interpret_sentence(model, doc)
     42     reference_indices=reference_indices.to(device)
     43     print(reference_indices.shape)
---> 44     attributions_ig, delta = lig.attribute(b_input_ids, reference_indices, \
     45                                            n_steps=200, return_convergence_delta=True)
     46     print(attributions_ig.shape)

/opt/conda/lib/python3.8/site-packages/captum/attr/_core/layer/layer_integrated_gradients.py in attribute(self, inputs, baselines, target, additional_forward_args, n_steps, method, internal_batch_size, return_convergence_delta, attribute_to_layer_input)
    364             start_point, end_point = baselines, inps
    365             # computes approximation error based on the completeness axiom
--> 366             delta = self.compute_convergence_delta(
    367                 attributions,
    368                 start_point,

/opt/conda/lib/python3.8/site-packages/captum/attr/_utils/attribution.py in compute_convergence_delta(self, attributions, start_point, end_point, target, additional_forward_args)
    257         # verify that the attributions and end_point match on 1st dimension
    258         for attribution, end_point_tnsr in zip(attributions, end_point):
--> 259             assert end_point_tnsr.shape[0] == attribution.shape[0], (
    260                 "Attributions tensor and the end_point must match on the first"
    261                 " dimension but found attribution: {} and end_point: {}".format(

AssertionError: Attributions tensor and the end_point must match on the first dimension but found attribution: 4 and end_point: 1
```

**Comment by mainulquraishi** [comment]
Hi, Thanks for your reply. Because of the hierarchical structure of my model I have two CNN. One CNN runs on word vectors and output sentence vectors of each document. 
The second CNN runs on sentence vectors and output document vector. 

So, let's say, we have the input of the embedding layer [32,68,10]. Here 32=batch_size, 68=length of the padded documents (pad each document with the highest number of sentences), 10=length of the padded sentences (pad each document with the longest sentence in the whole batch). 

After the embedding layer, the shape will be [32,68,10,300]. Now, I run a loop to take each document and use the first CNN to create sentence vectors per document. 
In this case, the shape of the input of CNN will be [68,1,10,300] (1 is the depth dimension of the CNN input).
**In the error case, the input shape of the embedding layer was [1,4,41] and the output shape was [1,4,41,300] and the input shape of the first CNN is [4,1,41,300] , where 4 is the number of a sentence per document**
N.B. The shape of the token reference was also [1,4,41]

**Comment by NarineK** [comment]
@mainulquraishi, is this still an outstanding issue for you ?

**Comment by aobo-y** [comment]
Close the issue since it is no longer active. Please reopen if your question is unsolved
