### ISSUE TITLE
How is the figure visualizing the importance of each word created?

### ISSUE THREAD

**Issue by wmmxk** [pytorch/captum#464]
In the [tutorial notebook](https://captum.ai/tutorials/Bert_SQUAD_Interpret) for interpreting Bert model. This figure was mentioned in the middle of the notebook
```Image(filename='img/bert/visuals_of_start_end_predictions.png')```. I was wondering how this figure was generated.

I know it is easy to display the word importance in Jupyter notebook. Is there a way to save what I see?

**Comment by NarineK** [comment]
Hi @wmmxk , cell 15 should generate that output. You might not get exact same output if you have trained your model with different hyper-parameters and use a different version of Bert model. I took a screenshot. You can also try to write it into a file from jupyter notebook.

**Comment by NarineK** [comment]
Hi @wmmxk, do you still have any outstanding issues ? If not, perhaps we can close this issue ?
