### ISSUE TITLE
Visualisation of Attention in Transformers for Image Captioning

### ISSUE THREAD

**Issue by nilinykh** [pytorch/captum#465]
Hello,

I am trying to use Captum to visualise attention weights in my transformer that I use for image captioning task. Since I initially pass region features (extracted from bounding boxes of detected image objects) to the transformer, I find it quite hard to decide how to visualise attention over these boxes. There are some tutorials available, which visualise ResNet-based model behaviour, but those are not about transformers, which have more non-linear dependencies in its attention.

Maybe anyone knows of the way of how to use Captum (Integrated Gradients, in particular) to visualise attention over image regions from the image captioning transformer? Something similar to Fig.4 in. https://arxiv.org/pdf/1912.08226.pdf

Nikolai.

**Comment by NarineK** [comment]
Hi @nilinykh, couple questions:
1) Is your goal to use Integrated Gradients for the output of attention layer ?  If so, can you point out which layer exactly do you want to compute the attribution scores for ?
2) Currently we do not have sophisticated visualization tooling, we support only helper functionality for that. Can you describe an example what do you exactly want to visualize ? It would be helpful if you could share a notebook with us.

**Comment by nilinykh** [comment]
Hej @NarineK,
thank you for replying!

1. My goal is to use Integrated Gradients (IG) to visualise encoder attention. My encoder consists of N layers (let's say N=6 since it is standard for transformers). My understanding of attention visualisation is the following: each layer's attention outputs some kind of attention matrix/matrix. All of these matrices need to be jointly represented as a single matrix, which I can map onto an image to visualise attention from all N layers. I am not entirely sure if this method is correct, but that's how I see it.
Would you propose to visualise only a particular layer? For example, visualising the first layer would make some sense to me: it takes an image as an input, and its output can be named 'an attention map'.

2. > It would be helpful if you could share a notebook with us.
I am currently working on some examples, which would explain my perspective better. I was thinking that IG method can be used to visualise attention in a way which I have covered above, but it does not seem the case from your explanation...could IG visualise only a particular layer?

**Comment by NarineK** [comment]
Hi @nilinykh,
1. IG is not a visualization tool per se. It is an  approach to compute importance scores for neurons, layers and input features.
We can visualize those importance scores however we want. In your case, if you want to visualize the importance scores for attention layers, I'd recommend to do so one layer at a time. You can use LayerConductance and attribute the output prediction to the outputs or inputs of the encoder attention layer. Then you can use the interpolate function to interpolate the attribution scores of a layer to an input image and visualize it as an image: https://github.com/pytorch/captum/blob/master/captum/attr/_utils/attribution.py#L382

You can also visualize the importance of each neuron in the attention layer, one neuron at a time, using NeuronConductance algorithm. 
Here we have some examples for NeuronConductance and LayerConductance. In general you can use any neuron or layer technique.
Here you'll find examples how to use neuron and layer techniques.
https://captum.ai/tutorials/Titanic_Basic_Interpret

2. I think you can visualize one layer at a time. If you provide code snippets in colab notebook I will be able to help.

**Comment by NarineK** [comment]
@nilinykh, were you able to resolve this issue ? If so, can we, please, close this task ?

**Comment by nilinykh** [comment]
@NarineK hej! Yes, the issue has been resolved, it can be closed now =)
