### ISSUE TITLE
Tutorial Page is down

### ISSUE THREAD

**Issue by tshrjn** [pytorch/captum#471]
## 🐛 Bug

 The [tutorial website](https://captum.ai/tutorials/Titanic_Basic_Interpret) is down.

**Comment by orionr** [comment]
@vivekmig, @NarineK and @jlin27 any thoughts? Thanks.

**Comment by vivekmig** [comment]
This is fixed now, thanks for letting us know @tshrjn !

cc: @jlin27 The cause of this was a new version of nbconvert which broke the parse_tutorials script, fyi in case this affects other projects.
