### ISSUE TITLE
How to run occlusion on only some inputs

### ISSUE THREAD

**Issue by pedrob37** [pytorch/captum#476]
## ❓ Questions and Help

I currently have a model that is able to take 4 inputs: Two images (in the form of 3D Tensors) and two vectors (in the form of 1D Tensors). When I want to run occlusion on this model I am able to do something along the lines of:

imat1, vecat1, imat2, vecat2 = oc.attribute((im1, vec1, im2, vec2),
                                                                     sliding_window_shapes=((3, 10, 10), (1,), (3, 10, 10), (1,)),
                                                                     strides=((3, 5, 5), (1,),  (3, 5, 5), (1)), 
                                                                     target=None)

And this seems to work OK. However, due to the nature of the model I don't always pass images to it. In this case it receives an input of shape [batch_size, 0] for the images, and vectors of shape [batch_size, >1] and proceeds accordingly. I run into problems with the occlusion because the class expects the strides and window shapes to be at least greater than or equal to the second dimension of the input, which for the images in this scenario, are zero. I obviously only care about the occlusion attributions as they refer to the vectors, but the model still expects an input for the images, so I can't just omit them when calling the attributions method (as far as I know). Is there a way to therefore only run occlusion on some of the inputs to a model?

**Comment by vivekmig** [comment]
Hi @pedrob37 , yes, you should be able to do this with a wrapper function as follows:

```
def model_wrapper(vec1, vec2):
    return model(default_im1, vec1, default_im2, vec2)

oc = Occlusion(model_wrapper)
attr_vec1, attr_vec2 = oc.attribute((vec1, vec2), sliding_window_shapes=....)
```

Alternatively, if you can change the order of inputs to your model to (vec1, vec2, im1, im2) (or define a wrapper as shown above with this ordering), then you can use the additional forward args functionality, which allows you to only compute attributions with respect to some model inputs. Note that additional forward args are provided after inputs to the model.
```
# model_fn takes inputs vec1, vec2, im1, im2
oc = Occlusion(model_fn)
attr_vec1, attr_vec2 = oc.attribute(inputs=(vec1, vec2), 
                                    additional_forward_args=(im1, im2),
                                    sliding_window_shapes=....)
```
Hope this helps!
