### ISSUE TITLE
DeepLiftShap consumes a lot of memory when running attribute() function 

### ISSUE THREAD

**Issue by giangnguyen2412** [pytorch/captum#484]
## ❓ Questions and Help

I am now using DeepLiftShap to generate heatmaps on Imagenet dataset. The function `attribute()` works well when the number of background samples small. However, when I increase `n ` from `15 `to `100`, this function consumed  a lot of memory and caused Out of Memory! It takes around 30GB of RAM to run.

Although I use `with torch.no_grad()` when running the func `attribute()` , it still takes a large amount of memory.

I would appreciate if anyone can help!

**Comment by NarineK** [comment]
Hi @giangnguyen2412, thank you for posting this issue. DeepLiftShap computes DeepLift score for each input-baselines pair and averages them. Currently it does all at once but we can potentially slice the input-baseline pairs and compute DeepLift value for small-sized input-baseline pairs and keep track of the running mean. 
https://github.com/pytorch/captum/blob/730c9a2b686fe294d73218f4c91372f0a38a5991/captum/attr/_core/deep_lift.py#L851
This will effect runtime performs but will help to avoid OOM.
We can make this fix.

**Comment by giangnguyen2412** [comment]
Yeah, I hope you can add this feature in the near future 😄 as I see, IG has an argument called `internal_batch_size` to deal with this issue. I suppose we will have the same thing for DeepLiftShap and others. So I need go on with a workaround solution as I have to run the code of my CPU and make the swap space larger..

**Comment by giangnguyen2412** [comment]
It was my fault. Captum doesnt take that much memory (only aroung 14Gb in my setting). Gonna close it!

**Comment by saifullah3396** [comment]
> Hi @giangnguyen2412, thank you for posting this issue. DeepLiftShap computes DeepLift score for each input-baselines pair and averages them. Currently it does all at once but we can potentially slice the input-baseline pairs and compute DeepLift value for small-sized input-baseline pairs and keep track of the running mean.
> 
> https://github.com/pytorch/captum/blob/730c9a2b686fe294d73218f4c91372f0a38a5991/captum/attr/_core/deep_lift.py#L851
> 
> 
> This will effect runtime performance but will help to avoid OOM.
> We can make this fix.

Any update on this? i am facing a similar memory issue when running for higher batch size. Is there any plan to implement an internal batch-size for deeplift shap?
