### ISSUE TITLE
How to increase the size and save the plot of image_plot() function

### ISSUE THREAD

**Issue by giangnguyen2412** [pytorch/captum#486]
## ❓ Questions and Help

Although I changed the width, the size of the plot is very small (width > 20 will not increase the plot anymore).

Also, as this function return `None`, how can I save the plot?

Thank you.

**Comment by bilalsal** [comment]
Hi @giangnguyen2412 ,

I am unsure which function you are using, could you provide a code snippet?
Is it possible you are referring to image_plot provided by the SHAP authors? https://github.com/slundberg/shap?

**Comment by giangnguyen2412** [comment]
Yes, I am using the function `image_plot()` of SHAP authors. The function I mentioned is [here](https://shap.readthedocs.io/en/latest/generated/shap.image_plot.html#shap.image_plot)!

**Comment by giangnguyen2412** [comment]
And this is the code snippet I am using:

```python3
# SHAP
import shap
from utils import *
background = torch.cat(bg_inputs[:10])
background = background.detach()
test_images = torch.cat(test_inputs[:1])
test_images = test_images.detach()
print(len(test_images))

e = shap.DeepExplainer(model, background)

for i in range(len(test_images)):
    test_images_t = torch.cat(test_inputs[i:i+1])
    shap_values = e.shap_values(test_images_t, ranked_outputs=1, output_rank_order='max') # 2xranked_outputsx1x3x224x224
    print(shap_values[1])
    
    converted_id = convert_imagenet_label_to_id(label_map, key_list, val_list, shap_values[1][0].item())
    class_name = id_map.get(converted_id).split(',')[0]
    print(class_name)
    class_name = [class_name]
    
    ######## To plot input only ##########
    tranformed_img = transform_t(Image.open(test_image_paths[i]))
    tranformed_img = tranformed_img[None, :, :, :]
    test_images_t = tranformed_img
    #################################
    
    shap_numpy = [np.swapaxes(np.swapaxes(s, 1, -1), 1, 2) for s in shap_values[0]]
    test_numpy = np.swapaxes(np.swapaxes(test_images_t.to('cpu').numpy(), 1, -1), 1, 2)

    for i in range(len(test_numpy)):
        max_val = max(np.min(test_numpy[i]), np.max(test_numpy[i]), key=abs)
        test_numpy[i] = test_numpy[i]/max_val

        max_val = max(np.min(shap_numpy[0][i]), np.max(shap_numpy[0][i]), key=abs)
        shap_numpy[0][i] = shap_numpy[0][i]/max_val
    print(len(shap_numpy))
    print(len(class_name))
    shap.image_plot(shap_values=shap_numpy, pixel_values=test_numpy, width=20, labels=shap_values[1].to('cpu'), aspect=0.2, hspace=1.0, show=True)
```

Even changing `width` doesnt help me to increase the size of the plot. Also, I dont know how to save this figure..

**Comment by bilalsal** [comment]
Hi @giangnguyen2412 ,

it seems the SHAP authors are using the `width` parameter as an upper limit on the figure size:
 https://github.com/slundberg/shap/blob/491d46a540d16fb5a9868de6be2913599c850167/shap/plots/_image.py#L76

Based on the above code, if the computed `shap_values` need less space than the value specified (e.g. 20), the figure will be smaller.
You can discuss your case with the SHAP authors by creating an issue in https://github.com/slundberg/shap/issues 

We are planning to support the Kernel SHAP in Captum soon (see issue #467), you will learn about this in the release notes.

Hope this helps

**Comment by giangnguyen2412** [comment]
Thank you. Its my bad. I was posting to the wrong place! Sorry for it!
