### ISSUE TITLE
Batch-Processing for Noise Tunnel

### ISSUE THREAD

**Issue by yvesrychener** [pytorch/captum#497]
## 🚀 Feature
Batch-Processing for Noise Tunnel

## Motivation

Methods like IntegratedGradients, which perform multiple steps per input have an *internal_batch_size* argument. However, Noise Tunnel lacks this as far as I can see. I think it would be quite useful to have a similar argument for Noise Tunnel, since underlying methods like Saliency cannot do batch-processing. This means that OOM issues arise with NoiseGrad-Saliency (and others).

## Pitch

Add an argument *batch_size_nt*, controlling the noise-tunnel internal batch size.

## Alternatives

Add a *internal_batch_size* argument to all attribution methods, but this would be a lot of work.

## Additional context

None

**Comment by NarineK** [comment]
Hi @yvesrychener, that's a good feature. We thought about it but haven't implemented it yet. Feel free to submit a PR if you are interested. It would be good also to create test cases with IG, Saliency, etc and make sure that all tests pass.

**Comment by NarineK** [comment]
#555 got merged! Closing this issue.
Thank you bringing it up @yvesrychener !
