### ISSUE TITLE
Type / Casting Error in ShapleyValueSampling

### ISSUE THREAD

**Issue by rbtsbg** [pytorch/captum#498]
## 🐛 Bug

In the attribute method of ShapleyValueSampling, the variable total_attrib is derived from the input tensor and receives the input tensor's type: 

https://github.com/pytorch/captum/blob/b9d88a9f0b65c25f55337ab8b6617abffe87acc7/captum/attr/_core/shapley_value.py#L296 

This raises a RuntimeError here: 
https://github.com/pytorch/captum/blob/b9d88a9f0b65c25f55337ab8b6617abffe87acc7/captum/attr/_core/shapley_value.py#L355 
when a tensor of type Long is passed as input and Python tries to cast a Float into a Long. 

## To Reproduce

1. Pass to ShapleyValueSampling a forward_func which accepts tensors of type Long, i.e. token indices to a BERT model. 
1. Call `attribute` with input tensors of type Long.  
1. A RuntimeError is thrown: 
```
...
File "/lib/python3.8/site-packages/captum/attr/_core/shapley_value.py", line 350, in attribute
    total_attrib[j] += (
RuntimeError: result type Float can't be cast to the desired output type Long
```
## Expected behavior

ShapleyValueSampling should be able to handle input tensors of type Long, such as token indices to NLP models.

## Fix 

add `dtype=torch.float` to  the `zeros_like` constructor here: 

https://github.com/pytorch/captum/blob/b9d88a9f0b65c25f55337ab8b6617abffe87acc7/captum/attr/_core/shapley_value.py#L296 

Edit: This turned out to be insufficient. Maybe casting right away solves the issue. 

## Environment

```

 - Captum / PyTorch Version: 0.2.0 / 1.6.0
 - OS: Linux
 - How you installed Captum / PyTorch: pip
 - Python version: 3.8.5
 - CUDA/cuDNN version: 9.1.85

**Comment by bilalsal** [comment]
Thank you for proposing this fix, Robert!

**Comment by NarineK** [comment]
It looks like this issue got fixed with: https://github.com/pytorch/captum/pull/515
Closing ...
