### ISSUE TITLE
Clarification of occlusion values for 1D classification network

### ISSUE THREAD

**Issue by pedrob37** [pytorch/captum#522]
## ❓ Questions and Help

I have a binary classifier network with a 1D output (between zero and one). I was told in a previous question thread (https://github.com/pytorch/captum/issues/475#issue-706569110) that I should be setting my target to None when calculating occlusion maps, and that positive occlusion values indicate regions that pushed the prediction towards one, while negative occlusion values indicate regions that pushed the prediction towards zero.

I wanted to clarify this. Consider the following case: The network takes an image as input, outputting 0.4 (And therefore the image would normally be assigned to the zero class). In this case do positive attributions still lead to a higher output score (i.e. one) and NOT a score closer to the class that would be assigned to the particular image (zero in this case).

Hope I made myself understood.

**Comment by bilalsal** [comment]
Hi @pedrob37 ,

yes, positive attributions still correspond to a higher output score, serving as support for the one class in your case.

Hope this helps
