### ISSUE TITLE
Top Word Attribute Scores

### ISSUE THREAD

**Issue by mahadafzal** [pytorch/captum#539]
I was able to follow the tutorial here: https://captum.ai/tutorials/IMDB_TorchText_Interpret for my classification task using a CNN and reproduce the figure found at the end of it for sample inputs sentences. 

However, I want to find the scores for the top words that most contribute to the classification by the model. More specifically, top-10 words of each of the positive and negative class as distinguished by the model. 

Could someone point me in the right direction?

**Comment by bilalsal** [comment]
Hi @mahadafzal ,

what about computing the attribution of the + / - classes in every sentence in your dataset?
This gives you a list of attribution scores for each word, and hopefully help you decide the top words for each class over the dataset.

Hope this helps

**Comment by mahadafzal** [comment]
Hi @bilalsal , 

My understanding is that the attribution tensor returned is the same size as the input sentence, and each element is corresponding to the attribution score for each word. So, in accordance with your suggestion, if the scores are calculated across all test sentences, and attribution scores are accumulated for all occurrences of a word in all sentences, that would be representative of the word's overall score for each class over the dataset?

**Comment by bilalsal** [comment]
Hi @mahadafzal ,

yes pretty much what I meant. Hope you find the results useful for your analysis.

**Comment by mahadafzal** [comment]
@bilalsal great, thank you!
