### ISSUE TITLE
Passing hidden state through LayerIntegratedGradients

### ISSUE THREAD

**Issue by devpramod** [pytorch/captum#540]
I was trying to replicate the CNN text model interpretability example using an LSTM. But the LayerIntegratedGradients throws an error about the missing hidden state.

forward() missing 1 required positional argument: ‘hidden’

What would be the best way of handling this?

**Comment by bilalsal** [comment]
Hi @devpramod ,

in the `LayerIntegratedGradients.attribute(..) `you can pass `additional_forward_args` of any type. You can use a tuple to pass multiple arguments.
If this does not work for your model, or you need to use keyword arguments, you can define a wrapper:

```
def wrapper(inp):
    return forward_func(input, kw_arg1 = ..., kw_arg2 = ...)

lig = LayerIntegratedGradient(wrapper, ...)
attribution = lig.attribute(...) 

```

Hope this helps

**Comment by devpramod** [comment]
Thank you! This helped me.
