### ISSUE TITLE
Ability to return HTML object from visualize_text()

### ISSUE THREAD

**Issue by cdpierse** [pytorch/captum#544]
## 🚀 Feature

The visualization function `visualize_text()` currently displays an an IPython `HTML` object if the user is inside a notebook. I'd like to propose a feature that allows this function to return either the `HTML` object constructed from the fields in `dom` or even just to return the contents of `dom` itself. This would allow for outputs from the function to be saved easily as right now I finding it difficult to save the visualization if not inside a notebook. 

## Pitch

I think it could be implemented as something as simple as the example below, essentially just an additional flag parameter that returns the HTML object if true. 
```python
from captum.attr import visualization as viz
.... # get attributions and data record


html_obj = viz.visualize_text([score_viz], return_html=True)

```

If you think this would make sense I'd be happy to put a PR together for it.

**Comment by bilalsal** [comment]
Hi Charles,

that is a good proposal.
Yes, it would be great if you could draft a PR - Thank you!

**Comment by cdpierse** [comment]
No problem at all, put in a PR (#548) for this earlier.

**Comment by bilalsal** [comment]
PR merged into master

**Comment by heyCoke** [comment]
Returning an HTML object, how do I save this object?

**Comment by shanto-Rahman** [comment]
I am getting the error when adding return_html=True. It says, 
html_data = viz.visualize_text(vis_data_records_ig, return_html=True)
TypeError: visualize_text() got an unexpected keyword argument 'return_html'
