### ISSUE TITLE
n_perturb_samples on captum.metrics.sensitivity_max

### ISSUE THREAD

**Issue by gkakogeorgiou** [pytorch/captum#549]
The n_perturb_samples variable is also used in Lime definition. This means that you can not use n_perturb_samples to **kwargs on metrics.sensitivity_max, in case you want to use Sensitivity algorithm on Lime for specific n_perturb_samples. I propose to change the name of n_perturb_samples on sensitivity_max algorithm.

**Comment by NarineK** [comment]
Thank you for bringing this up, @gkakogeorgiou !
`n_perturb_samples` is used in both `sensitivity_max ` and `infidelity` metrics.
For Lime and KernelSHAP we can probably rename that variable to `n_surrogate_samples` ?
What do you think, @vivekmig ?

**Comment by vivekmig** [comment]
Yeah, this is a good point! We should avoid argument name overlaps with metrics. Could we possibly just use `n_samples` in Lime and KernelSHAP, which would match other attribution methods?

**Comment by NarineK** [comment]
`n_samples` sounds good. One thing only - `n_samples` is also used in noise tunnel. It is less likely that someone will use Lime and KernelSHAP w/noise tunnel but just in case ?

**Comment by NarineK** [comment]
This got resolved with #558 , @gkakogeorgiou !
We will create a patch release to reflect these changes. Thank you for bringing it up.
