### ISSUE TITLE
model with two inputs

### ISSUE THREAD

**Issue by rojinsafavi** [pytorch/captum#550]
My pytorch model takes 2 inputes.
Ex 
model(X1, X2)
I am interested to use NeuronGradient to see what features contribute to the activation of a specific neuron. I was wondering gif Captum supports such inputs?

**Comment by bilalsal** [comment]
Hi @rojinsafavi ,

yes you can do this using Captum by means of `additional_forward_args` parameter:
`attr_method.attribute(X1, additional_forward_args = X2)` 

Alternatively, if you `forward()` function is more complex, you can define a wrapper around it along these lines:

```
def wrapper(tuple_input):
    return model(tuple_input[0], tuple_input[1])

ig = rIntegratedGradient(wrapper, ...)
attribution = ig.attribute((X1, X2), ...) 

```

Hope this helps

**Comment by rojinsafavi** [comment]
thanks!
