### ISSUE TITLE
Some quesions

### ISSUE THREAD

**Issue by ppyt** [pytorch/captum#559]
When the attribution is negative, what does it mean?
And when the attribution is  positive?

**Comment by bilalsal** [comment]
Hi @ppyt ,

Visibly positive and negative attributions mean that the feature influences the target.
Roughly speaking, a positive value means that the feature makes the target higher while a negative value means the feature makes the target lower.
The exact mechanism of how the influence is computed depends on the attribution method, so does the exact meaning.

Hope this helps
