### ISSUE TITLE
rnn-captum

### ISSUE THREAD

**Issue by ppyt** [pytorch/captum#560]
Can captum be used to explain the RNN model?
I do not see an example.

**Comment by bilalsal** [comment]
Hi @ppyt,

yes generally Captum should be able to handle most PyTorch models regardless to the architecture.
Gradient=based methods should work as long as they can propagate the gradient to the input.
Ablation=based methods only need a forward pass, all you need is to define a meaningful ablation masks.
[Here](https://captum.ai/docs/algorithms_comparison_matrix) you find a comparison matrix of the algorithms to help you pick one that would make sense in your case.

Hope this helps

**Comment by ShihengDuan** [comment]
I tried the integrated gradient with LSTM but got an error showing 'cudnn RNN backward can only be called in training mode'. Any ideas or tutorials showing how to apply Captum to LSTM? 

Thanks.

**Comment by NarineK** [comment]
Related to https://github.com/pytorch/captum/issues/564
