### ISSUE TITLE
No module named 'captum.insights.features'

### ISSUE THREAD

**Issue by mantasbandonis** [pytorch/captum#561]
## 📚 Documentation

The tutorial from https://captum.ai/tutorials/Multimodal_VQA_Captum_Insights throws an error when importing the needed libraries.

`No module named 'captum.insights.features'`

my library versions:

captum == 0.3.0
pytorch == 1.4.0
torchvision == 0.5.0

**Comment by edward-io** [comment]
Thanks for reporting. You can replace `captum.insights.features` with `captum.insights.attr_vis.features` to get the tutorial to work. https://github.com/pytorch/captum/pull/556 will fix.
