### ISSUE TITLE
selections of layer-wise relevance propagation rules

### ISSUE THREAD

**Issue by ShihengDuan** [pytorch/captum#563]
Hi all,

I'm new to PyTorch and found captum as an excellent tool for interpretation. I'm trying the new LRP application and wonder how to select different rules for layers. 
As I found in this test file, should we specify the rules for each layer before the 'attribute' method? 

https://github.com/pytorch/captum/blob/174ecbdf926a312d07c0ef728540455b1c2c1edb/tests/attr/test_lrp.py#L102-L103

Thanks!

**Comment by NarineK** [comment]
@ShihengDuan, thank you for using Captum for you projects! You can specify the rules for specific layers or we will internally default them to default rules.
https://github.com/pytorch/captum/blob/master/captum/attr/_core/lrp.py#L36 
Here are default rules:
https://github.com/pytorch/captum/blob/master/captum/attr/_core/lrp.py#L365

**Comment by NarineK** [comment]
@ShihengDuan, if you have no other questions can we close this issue ?
