### ISSUE TITLE
Runtime Error computing Delta on CUDA: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by mahadafzal** [pytorch/captum#580]
I am running GradientSHAP on cuda and keep running into this Runtime error:

Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

I tried installing the latest version of Captum from the git repository but to no avail. Removing delta fixes the issue. Is there anything I may be missing in this issue?

**Comment by bilalsal** [comment]
Hi @mahadafzal ,

maybe try ensuring the model, the inputs, and the targets are all on the same device:

```python
model.to(torch.device("cuda:0"))
input.to(torch.device("cuda:0"))
target.to(torch.device("cuda:0"))
```

Hope this helps

**Comment by NarineK** [comment]
@mahadafzal, is this still an open issue for you ?

**Comment by mahadafzal** [comment]
No, I will go ahead and close the issue! Thank you so much!
