### ISSUE TITLE
Progressbar for time-intensive approaches

### ISSUE THREAD

**Issue by lukasfolle** [pytorch/captum#581]
## 🚀 Feature

Progressbar that indicates the time left to progress given input image (could be tqdm).
## Motivation

When using 3D data or large images, methods like `Occlusion` take a considerable amount of time to finish. Knowing the time left would help impatient users like me 😄

**Comment by bilalsal** [comment]
Hi @lukasfolle,

This is a thoughtful suggestion!
yes, we will consider possibilities to provide progress signals, either using `tqdm` or via an optional hook. 

@edward-io, @vivekmig, @miguelmartin75: what would you recommend?

**Comment by aobo-y** [comment]
@lukasfolle the option for displaying the progress bar has been implemented. We will close this issue.
Please refer to the parameter `show_progress` in the API doc for details https://captum.ai/api/occlusion.html

**Comment by lukasfolle** [comment]
Awesome! Thanks.
