### ISSUE TITLE
Neuron Conductance, BERT

### ISSUE THREAD

**Issue by ajhepburn** [pytorch/captum#584]
I was wondering how I would go about using the Neuron Conductance algorithm for a BERT-like model?

```
for i in range(model.model.bert.config.num_hidden_layers):
    nc = NeuronConductance(model.predict, model.model.bert.encoder.layer[i])
    neuron_cond_vals_10 = nc.attribute(inputs=input_embeddings, baselines=ref_input_embeddings, additional_forward_args=(token_type_ids, position_ids,attention_mask), neuron_selector=(1,18,768), target=1)
```
I am currently using the process above, which results in the error:
`AssertionError: Cannot select neuron index from layer with multiple tensors,consider providing a neuron selector function instead.`

I was wondering if my selection was wrong as I am passing the layer into the `NeuronConductance` function.

If I output the layer to console, I'm presented with the following structure:
```
BertLayer(
  (attention): BertAttention(
    (self): BertSelfAttention(
      (query): Linear(in_features=768, out_features=768, bias=True)
      (key): Linear(in_features=768, out_features=768, bias=True)
      (value): Linear(in_features=768, out_features=768, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (output): BertSelfOutput(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (intermediate): BertIntermediate(
    (dense): Linear(in_features=768, out_features=3072, bias=True)
  )
  (output): BertOutput(
    (dense): Linear(in_features=3072, out_features=768, bias=True)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
)
```
I have used `LayerConductance` in much the same way without issue, and my forward function returns a softmaxed output with dim 2.

To clarify, I am faced with a binary classification problem, hence the `target=1` for the positive class.

**Comment by NarineK** [comment]
Hi @ajhepburn, thank you for the question. 
I think in this case the error message is confusing since we do not support function type for neuron_selector. We do this for other Neuron methods but not for NeuronConductance. cc: @vivekmig 

It looks like the output of `model.model.bert.encoder.layer[i]` layer is not a tensor but tuple. Are you using `output_attentions=True` ? Could you try to set it false.  Also in `neuron_selector=(1,18,768)` you don't need to specify the dimension of examples.

**Comment by ajhepburn** [comment]
Hi, sorry for the long overdue reply. I've set both `output_hidden_states` and `output_attentions` to False but the output I have for the layer remains the same. For `LayerConductance`, I input `model.model.bert.encoder.layer[i]` which is of type `transformers.models.bert.modeling_bert.BertLayer`.

Is there a way for me to pass some sort of argument to my forward function so that this somehow returns as a tensor instead?

**Comment by NarineK** [comment]
Hi @ajhepburn, in the following PR https://github.com/pytorch/captum/pull/602 we submitted a fix based on which your layer output can be a tuple. You just need to adjust the custom forward function to return a specific element from the tuple. See:
https://github.com/pytorch/captum/pull/602/files#diff-08d4cb8594841f9402d2d7cde19a74e747dfa1dc861e65e831bd316936422572R107

Regarding to passing an element to forward function to return a tensor: You can do it with a custom forward function that wrap model's forward function. As an example see: `squad_pos_forward_func` in bert tutorial https://captum.ai/tutorials/Bert_SQUAD_Interpret

**Comment by ajhepburn** [comment]
Amazing, thanks very much!
