### ISSUE TITLE
reconstruction and latent

### ISSUE THREAD

**Issue by rojinsafavi** [pytorch/captum#585]
I am working with an autoencoder, and I wanted to see if it's possible to look at the contribution of each latent node to the reconstruction? thank you

**Comment by bilalsal** [comment]
Hi @rojinsafavi ,

have a look at Captum's [Layer Attribution algorithms](https://captum.ai/docs/algorithms#layer-attribution). In particular, `Layer Conductance`, `Layer Feature Ablation`, and `Layer Integrated Gradients` seem like a good fit for what you described.

Hope this helps
