### ISSUE TITLE
Is there support for internal_batch_size for feature permutation?

### ISSUE THREAD

**Issue by ShihengDuan** [pytorch/captum#586]
Hi,

Similar to `IntegratedGradient`, can we use `internal_batch_size` in feature permutation? 

Thanks.

**Comment by bilalsal** [comment]
Hi @ShihengDuan ,

`FeaturePermutation` must operates on a batch of samples. For a given tensor `n = x.size(0)` must be > 1.

You can use the optional `perturbations_per_eval` argument in `FeaturePermutation.attribute()` if you want to accelerate the computation (e.g. if you are using DataParallel).

Hope this helps
