### ISSUE TITLE
Explainability of models with multiple inputs and one output

### ISSUE THREAD

**Issue by loukasilias** [pytorch/captum#603]
I have created a model with multiple inputs and one single output (binary classification).
The one input is text (passing through BERT), while the other one is a feature vector (passing through dense layers).
Could I use captum with a model with multiple inputs? If yes, which explainability methods are the most suitable for this purpose?

Thank you in advance.

**Comment by bilalsal** [comment]
Hi @loukasilias,

yes there is nothing that prevents Captum from operating on heterogeneous inputs.
Assuming your model is differentiable, you could starting using [Integrated Gradients](https://captum.ai/docs/extension/integrated_gradients). You will get attributions both for your text features and for your dense features.
You can also use [Feature Ablation](https://captum.ai/api/feature_ablation.html) with suited ablation masks, for example to determine which modality is more influential for which inputs.

Hope this helps

**Comment by bilalsal** [comment]
Also answered in #665
