### ISSUE TITLE
Broken link to Titanic passengers dataset

### ISSUE THREAD

**Issue by FabianReister** [pytorch/captum#604]
## 📚 Documentation

The link http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv on page https://captum.ai/tutorials/Titanic_Basic_Interpret  is broken. It should be https://biostat.app.vumc.org/wiki/pub/Main/DataSets/titanic3.csv .

**Comment by bilalsal** [comment]
Big thanks for spotting this, @FabianReister! We will update the tutorial with the new link.
