### ISSUE TITLE
Incorrect link to pretrained model

### ISSUE THREAD

**Issue by FabianReister** [pytorch/captum#605]
## 📚 Documentation

On page https://captum.ai/tutorials/Titanic_Basic_Interpret , the link to the pretrained model ("The pretrained model can be downloaded here: https://github.com/pytorch/captum/blob/master/tutorials/models/cifar_torchvision.pt") is incorrect. It should be 
 https://github.com/pytorch/captum/blob/master/tutorials/models/titanic_model.pt as it is about the titanic dataset.

**Comment by bilalsal** [comment]
Thanks again @FabianReister! Will update the tutorial accordingly.
