### ISSUE TITLE
Captum Insights - Key Error

### ISSUE THREAD

**Issue by MCKersting12** [pytorch/captum#608]
## 🐛 Bug

~\Anaconda3\lib\site-packages\captum\insights\attr_vis\attribution_calculation.py in calculate_attribution(self, baselines, data, additional_forward_args, label, attribution_method_name, attribution_arguments, model)
    117         attribution_cls = ATTRIBUTION_NAMES_TO_METHODS[attribution_method_name]
    118         attribution_method = attribution_cls(model)
--> 119         param_config = ATTRIBUTION_METHOD_CONFIG[attribution_method_name]
    120         if param_config.post_process:
    121             for k, v in attribution_arguments.items():

KeyError: 'Deep Lift'

## To Reproduce

1. Run Captum Insights and select Deep Lift

## Environment

 - Captum / PyTorch Version (0.3.1):
 - OS (e.g., Windows):
 - How you installed Captum / PyTorch (`pip`):

## Additional context

After checking the config file in captum insights -> attr_vis I can see that there are only three attribution methods in the ATTRIBUTION_METHOD_CONFIG: Dict. Does this mean that these are the only three methods currently supported in Captum Insights? If so, can I contribute to this project by incorporating more attribution algorithms into Captum Insights?

**Comment by bilalsal** [comment]
Thank you,  @MCKersting12 , for reporting the issue and for the additional context!

You are right.
DeepLift is supposed to be part of supported methods: https://github.com/pytorch/captum/blob/3c47914748e9d6e3383aaca402c9b016f8979966/captum/insights/attr_vis/config.py#L36

However, we missed to include an entry for DeepLift in the collection of predefined configurations:
https://github.com/pytorch/captum/blob/3c47914748e9d6e3383aaca402c9b016f8979966/captum/insights/attr_vis/config.py#L67

A quick fix would be just to add such an entry in the above collection:

```python
    DeepLift.get_name(): ConfigParameters(
        params={},
        post_process={},
    ),
```

We will take care of this in the next release.
