### ISSUE TITLE
Cannot calculate infidelity for more than 1 n_perturb_samples or 1 example

### ISSUE THREAD

**Issue by burnpiro** [pytorch/captum#614]
## To Reproduce

```
import numpy as np
from torchvision import models
from captum.attr import Saliency
from captum.metrics import infidelity

model = models.resnet18(pretrained=True)
input = torch.randn(2, 3, 224, 224, requires_grad=True)
saliency = Saliency(model)
attribution = saliency.attribute(input, target=3)

def perturb_fn(inputs):
    noise = torch.tensor(np.random.normal(0, 0.003, inputs.shape)).float()
    return noise, inputs - noise

infid = infidelity(model, perturb_fn, input, attribution, n_perturb_samples=10)
```

```
RuntimeError: The size of tensor a (20) must match the size of tensor b (20000) at non-singleton dimension 0
```

Error happen here (`captum/metrics/_core/infidelity.py:L496`):
```
return torch.sum(
            torch.pow(
                attribution_times_perturb_sums - inputs_minus_perturb.view(-1), 2
            ).view(bsz, -1),
            dim=1,
        )
```

`attribution_times_perturb_sums` has dim `[20]` and `inputs_minus_perturb` `[20, 1000]` (20x num of classes in the imagenet). At this point, we cannot perform that deduction because it's basically deducting `[20000]` vector from `[2]` vector.

## Expected behavior

Calculate the correct infidelity value.

## Environment
Describe the environment used for Captum

```

 - Captum / PyTorch: 0.3.1 / 1.7.1
 - OS: Ubuntu 18.04
 - How you installed Captum / PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: GTX 1080Ti
 - Any other relevant information:
```

## Additional context

It works for an input size of `torch.Size([1, 3, 224, 224])` and `n_perturb_samples` set to **1** but only because that deduction looks like: `[1] - [1000]`.

**Comment by NarineK** [comment]
@burnpiro, I think that you need to specify the target:
```
infid = infidelity(model, perturb_fn, input, attribution, n_perturb_samples=10, target=3)
``` 
sorry, if it is unclear in the docs. We can add it in the example doc.

**Comment by burnpiro** [comment]
Thanks for the answer, now looking at it I'm feeling very stupid :P It's such an obvious thing but didn't notice it earlier and instead was looking at the end of the calculation. I don't think you have to because it's explained in the method's docs but for some reason, I've missed it. Sorry for taking your time.
