### ISSUE TITLE
LRP getting relevance score in every layers

### ISSUE THREAD

**Issue by maduc7** [pytorch/captum#615]
## ❓ Questions and Help

Hi, I am using LRP in a Resnet18, everything is working fine, but now I am trying to get the activation of the other layers (and not just the input layer).

Is there a way to have the relevance score of a specific layer of interest (for example for the last convolutional layer: model.layer4[1].conv2)?

I tried few things but I guess I just need help there...
Thanks a lot in advance!

**Comment by NarineK** [comment]
Thank you for the question, @maduc7! For layers, please try LayerLRP. Here you can provide desired layer(s). (https://github.com/pytorch/captum/blob/master/captum/attr/_core/layer/layer_lrp.py)

**Comment by maduc7** [comment]
I missed this one. Amazing thanks a lot. :)
