### ISSUE TITLE
BUG: `tests` module is included in distribution

### ISSUE THREAD

**Issue by jamesmyatt** [pytorch/captum#629]
In conda, I get the following error:

```
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/noarch::pyprojroot-0.2.0-py_0, pytorch/noarch::captum-0.3.1-0
  path: 'lib/python3.8/site-packages/tests/__init__.py'
```

This suggests that this package is distributing a module called `tests`, which is wrong.

I assume that the same problem will occur with pip too.

In my experience, the best solution is a `src` layout as described in https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure and https://hynek.me/articles/testing-packaging/#src.

It's also worth noting that the "tests outside application code" pattern usually doesn't make the `tests` directory into a module: https://docs.pytest.org/en/latest/goodpractices.html?highlight=src#tests-outside-application-code. Note that this good practice guide also **strongly** suggests a src layout.

**Comment by vivekmig** [comment]
Thanks for catching this issue @jamesmyatt and the great suggestions! You are right, we were unintentionally distributing this tests module. For now, we have tested a fix to exclude the tests module, which should resolve the issue for future releases.

**Comment by jamesmyatt** [comment]
@vivekmig , any progress on this?

**Comment by jamesmyatt** [comment]
@vivekmig , is there any chance of a 0.3.2 release with this fix?

**Comment by vivekmig** [comment]
Hi @jamesmyatt , we are planning to do the 0.4.0 release in the next few weeks, so this fix will be included there.

**Comment by jamesmyatt** [comment]
Thanks

**Comment by NarineK** [comment]
Closing this, since 0.4 release it out.
