### ISSUE TITLE
LayerConductance OOM Error for high n_steps, even when internal_batch_size is small.

### ISSUE THREAD

**Issue by yoursi20** [pytorch/captum#632]
## 🐛 Bug

I am trying to apply LayerConductance to a relatively large model but am running into out of memory errors. Following the FAQ the first thing I tried was reducing the internal_batch_size. However, I've found that the OOM error still depends on the size of n_steps - for the same internal_batch_size a small size of n_steps the attribution method runs fine, but a large n_steps leads to OOM. 

Does anyone know why this is happening? And is there any way around the OOM errors that does not involve reducing the number of steps? Any help would be much appreciated!

## To Reproduce

In my setup the problem can be reproduced using a bigger version of the ToyModel:

```
class ToyModel(nn.Module):
    def __init__(self):
        N = 1000000
        super().__init__()
        self.lin1 = nn.Linear(3, N)
        self.relu = nn.ReLU()
        self.lin2 = nn.Linear(N, 2)

        # initialize weights and biases
        #self.lin1.weight = nn.Parameter(torch.arange(-4.0, 5.0).view(3, 3))
        #self.lin1.bias = nn.Parameter(torch.zeros(1,3))
        #self.lin2.weight = nn.Parameter(torch.arange(-3.0, 3.0).view(2, 3))
        #self.lin2.bias = nn.Parameter(torch.ones(1,2))

    def forward(self, input):
        return self.lin2(self.relu(self.lin1(input)))

input = torch.rand(2, 3)
toymodel = ToyModel()
toymodel.to('cuda:0')

# Runs fine for 500 steps.
att_lc = LayerConductance(toymodel.forward, toymodel.lin1).attribute(
    input.to('cuda:0'),
    target=0,
    n_steps=500,
    internal_batch_size=10
)

# OOM for 5000 steps. 
att_lc = LayerConductance(toymodel.forward, toymodel.lin1).attribute(
    input.to('cuda:0'),
    target=0,
    n_steps=5000,
    internal_batch_size=10
)
```

## Expected behavior

LayerConductance relies on a comparison between the current and previous sample on the path from the baseline to the target input. If internal_batch_size fits inside of memory and can run for, say, n_steps=50, I would expect LayerConductance to work with an arbitrary size of n_steps. However, it appears that some of the memory is not released throughout the run, leading to OOM errors for large n_steps. 

This behaviour seems to be specific to LayerConductance only - it does not happen for IntegratedGradients. 

## Environment

```
 - Captum / PyTorch Version (0.3.1 / 1.7.0):
 - OS: Ubuntu
 - How you installed Captum / PyTorch: pip / conda
 - Python version: 3.8.5
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration:  GeForce GTX 1080 Ti (11 GB memory) 
```

**Comment by vivekmig** [comment]
Hi @yoursi20 , thanks for the detailed issue and minimal repro example! You are right, there is an issue with memory not being deallocated after intermediate steps, causing OOM's even with internal_batch_size. 

I've tested a fix in #633 which seems to resolve the issue. You should be able to install Captum from source once this fix is merged, and this should allow arbitrary number of steps without any issues. Thanks again for identifying this issue!

**Comment by bilalsal** [comment]
Great work, @vivekmig! Thank you for taking initiative.

**Comment by yoursi20** [comment]
Thanks so much for sorting this out so quickly! It works perfectly now :)

**Comment by vivekmig** [comment]
> Thanks so much for sorting this out so quickly! It works perfectly now :)

Awesome, glad that it now works!
