### ISSUE TITLE
Setting target for BERT multi-label classification 

### ISSUE THREAD

**Issue by micophilip** [pytorch/captum#634]
Hello,

Thank you for the amazing work! I need help as I'm struggling with getting a simple multi-label classification example running. Particularly, setting the `target` for the `attribute` function.

I already reviewed [this](https://github.com/pytorch/captum/issues/171) issue as well as [this](https://github.com/pytorch/captum/issues/355) one but none of the answers worked for me.

I understand from @NarineK that multi-label classification attribution is not supported out-of-the-box and that I need to attribute each class individually.

I'm using BERT to detect personal health information on i2b2 medical dataset.

The input looks as follows. I'm basically trying with one sentence only for now. Length of this particular sentence is 50
```
tensor([[  101,   100,  1012,   100,  2003,  2019,  6640, 10930,  1059,  1013,
          1044,  1013,  1051,  7087,  3560, 21877,  8737,  4048,  3995,  3593,
          1010, 11888, 14234,  4295,  1010,   100,  1010,  1040,  7274, 15000,
          5178, 10092,  1010,  1998,  3674, 12436, 28817,  4135, 15069,  3111,
         10886,  2007, 23760, 25643,  3401, 10092,  1012,   100,  4315,   102]])
```

and the output looks like

```
tensor([[ 0,  0,  0, 11,  0,  0, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])
```

Which basically indicates that element at index 3 is label 11 and index 6 is predicted as label 15. 

For the sake of a simple example, I'm only interested in attributing why index 3 in the first (and only) sentence was predicted as label 11.

Here's what I tried:
* `target=[3]` and `target=[11]` (wasn't sure if I should set the index or the label) fail with `RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`
* Returning the `logits` instead of the label predictions, fails with `RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.`. This is the `grad` call in `captum` and it's not accessible from the `LayerIntegratedGradients` constructor so I can't set that flag.
* `target = torch.zeros(50)` and `target[3] = 1` fails with AssertionError: Tensor target dimension torch.Size([2500]) is not valid. torch.Size([50, 128]) (not sure why the multiplication of 50x50 happens)

What should my target be in this case?

Thank you so much

**Comment by bilalsal** [comment]
Hi @micophilip,

I am curious, did you try `target=3 `? The target is the index of the neuron, so 3 makes sense.
If your output is multidimensional, you can pass a tuple to specify the index, e.g. (0, 3), but from what you described, for each individual input sample the output seems to be effectively a 1D vector and `target=3` should work.

Generally, PyTorch allows you to define your tensors with `requires_grad=True`, just call `.requires_grad_()` on your target tensor or set  in `torch.tensor(value, requires_grad=True)`.

It is safer to avoid `allow_unused=True`, since the error you got usually indicates some inputs were not used when computing outputs. Is it possible that the way you are returning the logits causes parts of the input to be ignored?

Hope this helps

**Comment by micophilip** [comment]
Thank you so much @bilalsal this was really helpful and my example is now running. A quick follow-up if I may:

`target = index` or `target = (0, index)` turned out to refer to the label index and not the token index. For example, in my example above I had to set the target to `(0, 11)` not `(0, 3)` since it throw an error when I pass an index larger than my label IDs length. Is this expected?

If so, is there a way to attribute a prediction to this particular token at index 3? Since an example can have same label for different tokens, I assume that the attribution is token-specific and not label specific.

Consider the example from the i2b2 named-entity recognition dataset: "Mr. Slater is an 83 yo w/ h/o bullous pemphigoid. Mr Slater's sugars were initially well controlled". The model predicted Slater in both occurrences to be "PATIENT". Isn't it the case that the attribution of the first PATIENT prediction would be different from the second PATIENT prediction? If that's the case, how can I target a specific prediction for a specific token?

**Comment by bilalsal** [comment]
Hi @micophilip ,

Captum attributes a specific output to the layer you selected when instantiating `LayerIntegratedGradients`.

Am I correct to assume that behind every label in your sequential output (e.g. label 11 at index 3), there is a logit vector?
In the case, index 11 in that vector represents possible predictions for label 11, and it makes sense to use tuple (0, 11) as a target (assuming the forward function you provide to Captum returns the logits).

Regarding your 2nd question, it seems now you want to examine different parts of your sequential output.
I am unsure about the answer I have not used Captum with seq-to-seq models.
@NarineK, @vivekmig: what is the best way to analyze sequential outputs as an attribution problem?

**Comment by micophilip** [comment]
Hey @bilalsal 

Yes you're absolutely correct, my forward function returns a `logit` vector.

As for number 2, from the documentation and the 2 links I posted it looks doable I just can't wrap my head around how to represent that for a named-entity recognition task. I guess I'll let the folks you mentioned chime in.

Surprisingly, even with the current basic `LayerIntegratedGradients` implementation, Captum highlighted attributions that made sense. For example:

![image](https://user-images.githubusercontent.com/3325832/111626196-188a7900-87c4-11eb-9962-8ef56abcc2b2.png)

Not sure if I interpreted that correctly but it would make sense if it attributed BERT's prediction of token at index 3 (`[UNK]` in this case), to "yo" (year-old), and mentions of diseases such as "chronic kidney disease" all characteristics of a patient.

**Comment by bilalsal** [comment]
Hi @micophilip,

that helps better understand how your output looks like for one token.

I am curious, how does the full output looks like?
Are you able to specify these tokens simply by index?
In that case, maybe an index tuple like `(i, 11)` would help you tell Captum to compute attribution for logit of output token `i` being of class 11?

**Comment by micophilip** [comment]
Hi @bilalsal 

That is indeed the full output, since Captum does not support multi-label classification, @NarineK's recommendation on another issue was to attribute to each class individually. (full output of two tokens in the screenshots below)

So I basically re-run with the same parameters to `attribute` but with a different target class.

I thought the first element in the tuple is the example index, not the token index. I tried both, and when I pass (example_index, label_id) I feel the predictions make more sense than (token_index, label_id). Take a look:

Hard to show in Captum's `VisualizationDataRecord` but the B-PATIENT prediction refers to token at index 3 and B-AGE is the prediction of token at index 6.

`target = (token_index, label_id)`:

<img width="1902" alt="image" src="https://user-images.githubusercontent.com/3325832/111867255-3208fd80-8949-11eb-9771-95bf84841f1b.png">

`target = (example_index, label_id)`:  example_index always 0 in this scenario since I'm providing one example. This run was using `LayerDeepLift` so the attributions are slightly different from earlier screenshot.

<img width="1894" alt="image" src="https://user-images.githubusercontent.com/3325832/111867307-7d231080-8949-11eb-92ae-03aa62de806d.png">

Unless I misunderstood and the first argument should indeed be the token index and not the example index, I find the attributions in the second screenshot more "explainable".

**Comment by micophilip** [comment]
**Update:** Maybe Captum is indeed expecting `token_index` not `example_index`. It's failing with `IndexError: index 151 is out of bounds for dimension 1 with size 128` when I pass more examples 🤔

**Comment by micophilip** [comment]
**Another update:** I think it's a matter of using DeepLift vs Integrated Gradients, here're explanations of Integrated Gradients using `(token_index, label_id)` as a target and they're much more sensible than DeepLift's.

![image](https://user-images.githubusercontent.com/3325832/111903797-4ff26300-8a1a-11eb-89cf-cdc6e851598f.png)

I think I got all my questions answered, thank you so much @bilalsal 

Closing the issue
