### ISSUE TITLE
integrated_gradients.attribute error: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by sabyasachi0212** [pytorch/captum#642]
count = 0  #initialize a counter
for x, y_ in tqdm(test_loader_new):
    
    x = x.to(device)

    # get encoding
    with torch.no_grad():
        yhat = MT_model(x)
        
        integrated_gradients = IntegratedGradients(MT_model)
        
        for outputs in yhat:
            prediction_score, pred_label_idx = torch.topk(outputs, 1)
            print('Predicted class', pred_label_idx)
            print('Prediction score', prediction_score)
            
            attributions_ig = integrated_gradients.attribute(x, target = pred_label_idx, n_steps=200)  
            default_cmap = LinearSegmentedColormap.from_list('custom blue', 
                                                     [(0, '#ffffff'),
                                                      (0.25, '#000000'),
                                                      (1, '#000000')], N=256)
            _ = viz.visualize_image_attr(np.transpose(attributions_ig.squeeze().cpu().detach().numpy(), (1,2,0)),
                                         np.transpose(x.squeeze().cpu().detach().numpy(), (1,2,0)),
                                         method='heat_map',
                                         cmap=default_cmap,
                                         show_colorbar=True,
                                         sign='positive',
                                         outlier_perc=1)
    count = count+1
    if count>10:
        break

AttributeError                            Traceback (most recent call last)
<ipython-input-51-dca996c6c942> in <module>
     15             print('Prediction score', prediction_score)
     16 
---> 17             attributions_ig = integrated_gradients.attribute(x, target = pred_label_idx, n_steps=200)
     18             default_cmap = LinearSegmentedColormap.from_list('custom blue', 
     19                                                      [(0, '#ffffff'),

~/anaconda3/envs/tf/lib/python3.7/site-packages/captum/attr/_core/integrated_gradients.py in attribute(self, inputs, baselines, target, additional_forward_args, n_steps, method, internal_batch_size, return_convergence_delta)
    282             internal_batch_size=internal_batch_size,
    283             forward_fn=self.forward_func,
--> 284             target_ind=expanded_target,
    285         )
    286 

~/anaconda3/envs/tf/lib/python3.7/site-packages/captum/attr/_utils/batching.py in _batched_operator(operator, inputs, additional_forward_args, target_ind, internal_batch_size, **kwargs)
    162         )
    163         for input, additional, target in _batched_generator(
--> 164             inputs, additional_forward_args, target_ind, internal_batch_size
    165         )
    166     ]

~/anaconda3/envs/tf/lib/python3.7/site-packages/captum/attr/_utils/batching.py in <listcomp>(.0)
    161             **kwargs
    162         )
--> 163         for input, additional, target in _batched_generator(
    164             inputs, additional_forward_args, target_ind, internal_batch_size
    165         )

~/anaconda3/envs/tf/lib/python3.7/site-packages/captum/attr/_utils/gradient.py in compute_gradients(forward_fn, inputs, target_ind, additional_forward_args)
     94     with torch.autograd.set_grad_enabled(True):
     95         # runs forward pass
---> 96         outputs = _run_forward(forward_fn, inputs, target_ind, additional_forward_args)
     97         assert outputs[0].numel() == 1, (
     98             "Target not provided when necessary, cannot"

~/anaconda3/envs/tf/lib/python3.7/site-packages/captum/attr/_utils/common.py in _run_forward(forward_func, inputs, target, additional_forward_args)
    503         else inputs
    504     )
--> 505     return _select_targets(output, target)
    506 
    507 

~/anaconda3/envs/tf/lib/python3.7/site-packages/captum/attr/_utils/common.py in _select_targets(output, target)
    449         return output
    450 
--> 451     num_examples = output.shape[0]
    452     dims = len(output.shape)
    453     if isinstance(target, (int, tuple)):

AttributeError: 'list' object has no attribute 'shape'

Note: This is a multi-task multi-class classification problem, so yhat is a list of 5 tensors. Each tensor is of size torch.Size([10]). x is a single image of shape torch.Size([1, 3, 100, 100]). I want to find attribution of each of the 5 output tensors, that's why I am running the attribution inside a for loop. 

Note: The same code works for binary classification. (only one output tensor and of size 2).

I do not understand where the 'list' is coming from. I supply only tensors to integrated_gradients.attribute function.

**Comment by bilalsal** [comment]
Hi @sabyasachi0212 ,

Captum first runs a forward pass and then attributes the output channel you select to the input features.
The current implementation does not readily account for the list-typed output your model computes.

A straightforward workaround would be to define a wrapper model that actually returns a tensor, e.g.:

```python
def single_output_forward(out_ind):
    def forward(x):
        yhat = MT_model(x)
        return yhat[out_ind]
    return forward

for i in range(5):
    fwd_fn = single_output_forward(i)
    integrated_gradients = IntegratedGradients(fwd_fn)
    prediction_score, pred_label_idx = torch.topk(fwd_fn(x), 1)
    print('Predicted class', pred_label_idx)
    print('Prediction score', prediction_score)
    attributions_ig = integrated_gradients.attribute(x, target = pred_label_idx, n_steps=200)  

```        

Hope this helps

**Comment by sabyasachi0212** [comment]
@bilalsal Thank you! That worked seamlessly. It also improved my understanding of CAPTUM!

**Comment by sabyasachi0212** [comment]
I am closing this issue.
