### ISSUE TITLE
conda recipe should use matplotlib-base

### ISSUE THREAD

**Issue by jamesmyatt** [pytorch/captum#644]
According to the conda-forge docs, the conda recipe should probably depend on the matplotlib-base package, rather than matplotlib: https://conda-forge.org/docs/maintainer/knowledge_base.html#matplotlib

Is this right? Does captum require pyqt as well or just matplotlib?

For example: https://github.com/conda-forge/geoplot-feedstock/pull/19

**Comment by vivekmig** [comment]
Thanks @jamesmyatt , this is a great catch! Captum only requires matplotlib but not pyqt, we will update the recipe to depend on matplotlib-base instead.
