### ISSUE TITLE
Loading mini batches into LinearIntegratedGradients.attribute

### ISSUE THREAD

**Issue by devpramod** [pytorch/captum#645]
I'm new to Captum.
Can anyone tell me if it's possible to compute attributions on mini-batches as opposed to a single sample. it would really speed up what I'm trying to do.

Thanks in advance.

**Comment by vivekmig** [comment]
Hi @devpramod , yes all Captum methods should work with batches as well as single-samples. The attribution methods always return attributions with shape matching the input shape (or for layer attribution methods, the layer input / output shape with first dimension = batch size), so this would contain results for all examples in the input batch.

**Comment by devpramod** [comment]
Thank you! I'm working on it now.

**Comment by rhettdsouza13** [comment]
When applying this recently, I found that I receive an OOM CUDA error when using the argument.
When I attempt to use the same batch size with an iterator and PyTorch data loader, I don't receive the error.
Is there any reason why this might be happening? Is my understanding not appropriate?
