### ISSUE TITLE
GuidedBackprop for non Tuple inputs

### ISSUE THREAD

**Issue by lukasfolle** [pytorch/captum#650]
## 🚀 Feature

As far as I can see, right now, `GuidedBackprop` and other modules only support the input in a specific way. In some cases (e.g. ensembles) a list of inputs of different shapes might be necessary for a given model.

## Pitch

A less strict handling of input data would be required to deal with those cases.

**Comment by bilalsal** [comment]
Hi @lukasfolle,

We realize that forward functions can take various forms of input. There are two ways that can hopefully help you feed your custom input:

- Using `additional_forward_args`:
Each algorithm in Captum allows defining this parameter to pass additional inputs or arguments to your forward function. E.g., an in-painting CNN typically requires a mask besides the standard image input `X`, this can simply be passed via `algorithm.attribute(X, additional_forward_args = mask)`. Note that you can pass multiple arguments of arbitrary type, as explained in the [documentation](https://captum.ai/api/guided_backprop.html#captum.attr.GuidedBackprop.attribute). 

- Wrapping your forward function with another function:
You can define a wrapper function that shapes the custom inputs into the format expected by Captum.
Here are examples of how to define wrappers: https://github.com/pytorch/captum/issues/642#issuecomment-808487575 and https://github.com/pytorch/captum/issues/377#issuecomment-625686894.

Hope this helps

**Comment by lukasfolle** [comment]
Thanks for the help!

**Comment by vivekmig** [comment]
Hi @lucasfolle, just wanted to add to @bilalsal's second solution above, this requires a small modification to work appropriately with a few methods which depend on hooks, including GuidedBackprop. You can look at the follow-up discussion in #444 for more context, which provides this example for using a wrapper function with GuidedBackprop:

```
def model_wrapper(*x):
    return model(*x)[0]

gb = GuidedBackprop(model)
gb.forward_func = model_wrapper
gb.attribute(inputs)
```
