### ISSUE TITLE
Zero Attribution Tensor using Integrated Gradient BERT

### ISSUE THREAD

**Issue by changecreator** [pytorch/captum#660]
## ❓ Questions and Help

Dear Captum Team,

I am using captum integrated gradient method to get the attributions for a single layer in a BERT transformer model. For some layers (4, 27) i am receiving a 0 tensor as attribution, which does not make sense to me as it would mean the gradients accumulated = 0 from the baseline to the input.

Can you help me please find the error or explain the reason behind the 0 attribution tensor?
Thank you

**Comment by bilalsal** [comment]
Hi @changecreator,

To think of possible reasons for 0 attribution, we need more details about your model and inputs.
Are you following the [BERT tutorial](https://captum.ai/tutorials/Bert_SQUAD_Interpret)?

**Comment by changecreator** [comment]
Hi @bilalsal ,

yes i am following the tutorial. Thank you for your help.

Model: https://github.com/agemagician/ProtTrans fine tuned to Enzyme Classification. 30 Layers, 16 Heads.
Input: Protein Sequence i.e. [CLS_Token, tokenized_input , SEP_Token] 
Baseline:  [CLS_Token, Pad_Token(0) , SEP_Token] 

captum: lig = LayerIntegratedGradients(model_wrapper, model_wrapper.ProtBertBFD.encoder.layer[layer_idx].attention.self)
