### ISSUE TITLE
UserWarning about hooks in algorithms like DeepLift or GuidedBackprop

### ISSUE THREAD

**Issue by seba-eng** [pytorch/captum#661]
The attribute function of some methods like DeepLift or GuidedBackprop issues a warning that a hook is set. As far as I can see it, this happens in any case ([here](https://github.com/pytorch/captum/blob/43acfcd320c44e8e469bf5276af9d55cf62145aa/captum/attr/_core/guided_backprop_deconvnet.py#L60) or [here](https://github.com/pytorch/captum/blob/43acfcd320c44e8e469bf5276af9d55cf62145aa/captum/attr/_core/deep_lift.py#L322) in the code).

What is the reason for this warning? Does it require any action from me or is it just an information?

**Comment by bilalsal** [comment]
Hi @seba-eng ,

yes, the warnings are informational, just to make you aware that the hooks were created.

This would be helpful In case the attribution led to a runtime error and left dangling hooks. Using a model with dangling hooks can cause mysterious behavior or obscure error messages.

Hope this helps

**Comment by seba-eng** [comment]
ok than makes sense. Thanks for the explanation.
