### ISSUE TITLE
got an unexpected keyword argument 'show_progress'

### ISSUE THREAD

**Issue by Asad-Ismail** [pytorch/captum#676]
captum.__version__ =0.3.1
attributions_occ = occlusion.attribute(normalized_inp,
                                       strides = (3, 80, 80),
                                       target=1,
                                       sliding_window_shapes=(3,70, 70),
                                       baselines=0,                  
                                       perturbations_per_eval= 1,
                                       show_progress= True
)

raises error got an unexpected keyword argument 'show_progress'

**Comment by vivekmig** [comment]
Hi @Asad-Ismail , this is a new feature that wasn't in our last release of 0.3.1. This functionality will be available soon in our 0.4 release. In the meantime, you can install Captum from source, which will be the latest and include this option.

**Comment by Asad-Ismail** [comment]
Installing from source worked thank you

**Comment by NarineK** [comment]
@Asad-Ismail, do you mind closing the issue if it got resolved ?
