### ISSUE TITLE
AttributeError: 'function' object has no attribute 'register_forward_pre_hook'

### ISSUE THREAD

**Issue by michaelgroeger** [pytorch/captum#678]
## ❓ Questions and Help

Hello folks, 

First of all, thank you very much for this great library. I am currently trying to run different explanation methods on a U-Net segmentation model using [this](https://github.com/qubvel/segmentation_models.pytorch) library. So far, thanks to your tutorial I was able to get LayerGradCam running. 

However, I would also like to use LayerDeepLift. But I run into the following two issues:

1) Using the approach written in the [documentation](https://captum.ai/api/layer.html#layer-deeplift): 
`dl = LayerDeepLift(best_model, last_decoder_layer)
input = image_gc.to(DEVICE).unsqueeze(0)
input.require_gradient = True
# Computes deeplift attribution scores 
attribution = dl.attribute(input, target=0)`

Yields the error:
`AssertionError: Target not provided when necessary, cannot take gradient with respect to multiple outputs.`

Following #389 discussion and the insights given in the [tutorial](https://captum.ai/tutorials/Segmentation_Interpret) I assume that this error pops up, because I am not passing the wrapper function instead of `best_model` in `LayerDeepLift`. 

2) After changing the `best_model` object to the wrapper function that I used and that worked in LayerGradCam which is borrowed from the tutorial I receive this error:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-73-f8f463dea81c> in <module>()
      7 input.require_gradient = True
      8 # Computes deeplift attribution scores for conv4 layer and class 3.
----> 9 attribution = dl.attribute(input, target=0)

2 frames
/usr/local/lib/python3.7/dist-packages/captum/log/__init__.py in wrapper(*args, **kwargs)
     33             @wraps(func)
     34             def wrapper(*args, **kwargs):
---> 35                 return func(*args, **kwargs)
     36 
     37             return wrapper

/usr/local/lib/python3.7/dist-packages/captum/attr/_core/layer/layer_deep_lift.py in attribute(self, inputs, baselines, target, additional_forward_args, return_convergence_delta, attribute_to_layer_input, custom_attribution_func)
    302         main_model_hooks = []
    303         try:
--> 304             main_model_hooks = self._hook_main_model()
    305 
    306             self.model.apply(

/usr/local/lib/python3.7/dist-packages/captum/attr/_core/deep_lift.py in _hook_main_model(self)
    577         else:
    578             return [
--> 579                 self.model.register_forward_pre_hook(pre_hook),  # type: ignore
    580                 self.model.register_forward_hook(forward_hook),
    581             ]  # type: ignore

AttributeError: 'function' object has no attribute 'register_forward_pre_hook'`

For reference, this is the wrapper function, I omitted the documentation since it is almost the same like it is given in the tutorial:

`def agg_segmentation_wrapper(input, model):
    model_out = model(input)
    out_max = torch.argmax(model_out, dim=1, keepdim=True)
    selected_inds = torch.zeros_like(model_out[0:1]).scatter_(1, out_max, 1)
    return (model_out * selected_inds).sum(dim=(2,3))`

It seems to me that now I am stuck between two issues. On the segmentation task, I need the wrapper function to make Deep Lift work but it also needs to have access to `best_model.register_forward_pre_hook`. Do you maybe have an idea how I can solve both problems and make LayerDeepLift work?

Thank you so much for your time and help. 

Best,

Michael

P.S.: The whole project is done in Google Colab. 

- [Discussion Forum](https://discuss.pytorch.org/c/captum)

**Comment by bilalsal** [comment]
Hi Michael,

what about creating a wrapper *class* for your model?

```python
class WrapperModel(nn.Module):
    
    def __init__(self, model):
        self.model = model
    
    def forward(...):
        return self.model(...)

dl = LayerDeepLift(WrapperModel(best_model), last_decoder_layer) // ensure last_decoder_layer is correct
```

That way, Captum should be able to define the hooks, since you are passing an `nn.Module` not a callable.

hope this help

**Comment by michaelgroeger** [comment]
Hi @bilalsal, thank you very much for your suggestion. This solved my problem.

You guys are really awesome for providing us with such a great library and being that helpful. Thank you again.
