### ISSUE TITLE
Strange import issue --> AttributeError: module 'captum' has no attribute 'attr'

### ISSUE THREAD

**Issue by adaruna3** [pytorch/captum#680]
## 🐛 AttributeError: module 'captum' has no attribute 'attr'

When importing captum with just `import captum`, the package is missing modules like attr. Running `dir(captum)` shows that the other modules, like `attr` are missing. However, if a statement like `from captum.attr._utils.input_layer_wrapper import ModelInputWrapper` is included after `import captum`, the captum package then has the missing modules. Again, verified by running a `dir(captum)`. Is this expected behavior?

## To Reproduce

1. Run the code below:
```
import captum
print(dir(captum))
print("---------------")
from captum.attr._utils.input_layer_wrapper import ModelInputWrapper
print(dir(captum))
exit()
```
1. The above should get an output of the following:
```
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__']
---------------
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_utils', 'attr', 'log']
```

## Expected behavior

I assume all modules should be available after `import captum`. If this behavior is not expected, please close and disregard.

## Environment

I installed captum using the suggested conda method. See details below. After noticing this issue in an environment I was developing in with many other packages, I made a new, clean environment that only contained captum and any dependencies conda installed. Same issue.

 - Captum / PyTorch Version (e.g., 1.0 / 0.4.0): 0.3.1
 - OS (e.g., Linux): Ubuntu 18.04.4 LTS
 - How you installed Captum / PyTorch (`conda`, `pip`, source): conda
 - command: `conda install captum -c pytorch`
 - Python version: 3.6.13

**Comment by NarineK** [comment]
Thank you for raising the issue, @adaruna3 ! We will look into it.

**Comment by vivekmig** [comment]
Hi @adaruna3 , I think this is likely expected behavior, since importing a module doesn't automatically import all submodules. This would only occur if the main captum __init__ imported the specific submodules, which is not currently the case, so you would need to either do `import captum.attr` or `from captum.attr import *` to import the attr submodule. These links also discuss similar issues ([1](https://stackoverflow.com/questions/23829845/dirpackage-not-listing-out-containing-modules-in-python?rq=1), [2](https://stackoverflow.com/questions/57461671/dir-function-not-showing-all-package-contents))

**Comment by adaruna3** [comment]
Hi Vivek, totally understand. Ultimately it depends on the design choices of the developers. I am used to importing the main package `captum`, `torch`, or `numpy` for example, and then expect to be able to access the highly utilized modules intended for public use within that package. Like with torch, I import torch but have access to `nn`, `multiprocessing`, `optim`, etc. and with numpy I have access to `random`, `linalg`, etc

I just mentioned it in case that behavior was not caught yet. But if having an import for each module in the package is intended design, that works too. Thanks!!
