### ISSUE TITLE
Ignore unused input/output

### ISSUE THREAD

**Issue by R-N** [pytorch/captum#732]
## 🚀 Feature
I want Captum to have option to just ignore unused inputs. 

## Motivation

I made options to disable use of some optional parameters, although they're still given, for ease, flexibility, and reusability in multiple model architectures. There's also LSTMCell which returns hx and cx but I don't use the last hx. Torch is fine with this, but Captum doesn't and insists to calculate grad for every input (so it must be used and be in the graph). 

## Pitch

I want Captum to just ignore unused inputs, make it return None or zeros.

## Alternatives

Making a wrapper function for the whole model that only has the used inputs as parameter works for input attribution, meanwhile for layer attribution I have to make a wrapper module. Both are inconvenient and doesn't work for LSTMCell case.

## Additional context
The main error:
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior

I tried editing captum's source and set allow_unused=True but it only brings more error since Captum insists on calculating for the unused input.

Also, LSTMCell hx input is a tuple of (hx, cx) while Captum requires the input to be a Tensor, so it throws assertion error. This can be worked around by wrapping the LSTMCell and splitting hx into two separate parameter hx and cx. The error:
AssertionError: Given input is not a torch.Tensor

**Comment by bilalsal** [comment]
Hi @R-N ,

here as well, I would propose the same response as in #733.

Hope this helps.

**Comment by R-N** [comment]
Alright, I'll just be replying there then.

**Comment by R-N** [comment]
The problem motivating this feature request has been solved (explained in #733), so I'm just gonna close this. I still hope for the feature to be implemented, though, haha.

Thanks
