### ISSUE TITLE
Ignore None input

### ISSUE THREAD

**Issue by R-N** [pytorch/captum#733]
## 🚀 Feature
I want Captum to have option to just ignore None inputs.

## Motivation

I made some module parameters optional, for ease, flexibility, and reusability in multiple model architectures. Torch is fine with this, but Captum doesn't and insists that input has to be a tensor. I have to specifically give None as argument because Captum doesn't support kwargs input.

## Pitch

I want Captum to just ignore None inputs, make it return None too. 

## Alternatives

Making a wrapper function for the whole model that only has the used inputs as parameter works for input attribution, meanwhile for layer attribution I have to make a wrapper module. Both are inconvenient since a wrapper has to be made for each combination of options.

## Additional context

The error:
AssertionError: Given input is not a torch.Tensor

**Comment by bilalsal** [comment]
Thank you, @R-N for proposing this feature.
Indeed, there are various situations where the input might not be fully compatible with the format expected by Captum.
As you correctly pointed under Alternatives, a wrapper function is for now the most convenient way to format such input.
We are monitoring commonly-requested scenarios, and might consider providing ready-to-use "adapters" instead of advising users to rely on wrappers.
For now, a wrapper does seem the best route for your scenario.

Hope his helps

**Comment by R-N** [comment]
I see. I'll be looking forward to those adapters then, since wrappers are still inconvenient for my use case as stated above. Thanks. 

It's fine for input attribution, but for layer attribution I have to make a lot of wrappers and make a class for each architecture to use the correct wrapper (currently I'm only using one general class which changes the architecture by parameters provided). Or maybe I can have it produce the correct wrapper module class in init method and use it. 

However, instead of adapters, wouldn't it be easier to just have an option to ignore None and unused inputs? I thought it would just be adding some if and try-except statements. I don't know Captum's internal working though so I may be underestimating it by a lot or it might be a bad design choice.

**Comment by NarineK** [comment]
@R-N, if I understand correctly you can just pass those arguments as `additional_forward_arg`. `additional_forward_arg` are passed to forward function but gradients w.r.t. those aren't computed.
Here is a usage of additional_forward_args `https://captum.ai/tutorials/Bert_SQUAD_Interpret`
Have you tried it ?

**Comment by R-N** [comment]
If I understand it correctly it's only for the main forward function, that is the model's. I have additional parameters and unused outputs in the modules (layers) inside my model as well. 

Also, I still have to give None for the input between inputs I want to attribute, like, (input1, input2, None, input4) (I want to attribute input4 too). Switching them isn't a solution because in another scenario I will pass (input1, input2, input3). Wrappers can work though.

**Comment by NarineK** [comment]
@R-N, for the forward function in the described , scenario you can use a wrapper as you mentioned. When you mention unused input in the layers. Which algorithm are you using that you are having an issue ? A layer attribution method ?

**Comment by R-N** [comment]
Yes, I'm already using a wrapper for input attribution. It's not much a hassle and doesn't clutter the project since it's just one part. For the layer attribution, I'm using GradCam. 

Updating this issue (#732, actually); it turns out I misunderstood the layer attribution. It's actually mainly concerned about the layer's output, not the input (non-tensor input will still raise error though). So the problem is actually unused output, not unused input, and it only happens on LSTMCell in my case. I thought it was similar to input attribution case so I thought I'd need to make a lot of wrappers, sorry, I hadn't checked all of them properly. So I actually only need to make one wrapper (for LSTMCell) and make an exception on the last iteration to only return cx instead of both hx and cx. 

Well, my issue is solved so I'm gonna close this (and the other one). I still hope to have the feature implemented though, haha. 

Thanks
