### ISSUE TITLE
Reduce unnecessary reliance and usage of numpy

### ISSUE THREAD

**Issue by aobo-y** [pytorch/captum#746]
This search gives us all the usage of `Numpy` in Captum https://github.com/pytorch/captum/search?p=1&q=numpy
Many of them are not necessary
- either empty imports
- or similar functionality can be replaced with pytorch

In order to reduce the unneeded dependency, we can investigate the current usages and remove/replace them when possible

**Comment by bilalsal** [comment]
Excellent find, @aobo-y!
Indeed, we noticed significant performance gain when we avoided numpy() while working on CCA and CKA.
You might need to pay attention to numerical precision issues, esp. to ensure that the unit tests continue to work meaningfully.

Thank you for bringing up this good proposal!

**Comment by aobo-y** [comment]
Thank you for the heads up @bilalsal ! 
I originally noticed this issue when helping @NarineK remove numpy for an internal use case (https://github.com/pytorch/captum/pull/714)
I will create a series of similar small PRs each of which contains only tightly-related changes, instead of one PR for all, so that we can review and discuss the removal/replacement case by case.

**Comment by NarineK** [comment]
@aobo-y can we close this issue since it has been addressed ?

**Comment by aobo-y** [comment]
@NarineK sure, I think we almost cleared the unnecessary cases.

However, there are still some tricky ones left. For example, 
https://github.com/pytorch/captum/blob/4faf1ea49fbff90af92b759c1f763dda1d8be705/captum/attr/_core/gradient_shap.py#L359-L363
is perfect scenario to directly apply `torch.rand(...)`.  But the change will require quite some extra efforts to fix many tests, because even with fixed seed during tests, `torch`'s random gives different values from `np`. As you can imagine, it needs update of the expected values and relaxation in many "almost-equal" asserts.
I will create separate issues dedicated for them.
