### ISSUE TITLE
Feature Importance Attribution with correlated features

### ISSUE THREAD

**Issue by aashwinmishra** [pytorch/captum#752]
## ❓ Questions and Help

Hi, I'm attempting to use Captum to interpret surrogate models for particle physics. Many of these models involve high-dimensional vector input features being mapped to numerical vector targets. Like any physics dataset, many of these features are correlated, to varying degrees. For such models, the feature attribution that I'm getting from IG, DeepLift, SHAP, Ablation, etc varies from counterintuitive to inane. 

To that end, I reduced the crux of problem to a "trivial" case, where y=3*X+epsilon, where y and X lie on the real line. As the set of input features, I created 5 copies of X with a small amount of noise.

[Linear_pairplot.pdf](https://github.com/pytorch/captum/files/7134272/Linear_pairplot.pdf)

The pytorch model is just a linear layer performing regression between these 5 input features and the target. The features were scaled so as to ensure that the baseline case of zeros was sensible.

One would expect that for this problem, the attribution methods should either assign approximately equal importance to each feature...or assign importances that reflect the weights assigned to each feature in the linear layer. However, this is not the case for any method and the attributions vary all over the place for different methods.

[Linear_Test_Attributions.pdf](https://github.com/pytorch/captum/files/7134304/Linear_Test_Attributions.pdf)

After this extended preamble, I wanted to inquire if I might be making any errors in the application of the methods...or is this a fundamental limitation across all attribution methods, such that they cant deal with correlations of features, please?

PS- Any suggestions are welcome!

**Comment by bilalsal** [comment]
Hi @aashwinmishra,

what you performed is an interesting test of attribution methods, it reminds me with how the Sanity Checks paper was conceived https://arxiv.org/abs/1810.03292
Three of the methods you used (plain IG, DeepLift, and FeatureAblation) seem to compute identical feature attributions.
While these attributions are not strictly equal to the weights / feature-scaling you assigned, however, they seem to well correlate with them, except for feature E. Looking at the way these methods work, I wouldn't expect the two set of quantities (attributions vs. weights) to be identical.

That said, I share your concern about applying feature attribution to interpret your real model operating on high-dimensional feature space. Besides co-linearity, there is high chance that your features interact in non-linear ways. This makes it hard to compute a robust attribution for individual features, as implemented in Captum. Methods to analyze feature interaction might be helpful  https://github.com/mtsang/archipelago

Hope this helps
