### ISSUE TITLE
Layer Conductance

### ISSUE THREAD

**Issue by MLAlex1** [pytorch/captum#773]
Hi,

I have a question regarding how layer conductance is calculated, basically from here:
https://github.com/pytorch/captum/blob/0435ff10a71724a788bdc54f01324f4f5c788541/captum/attr/_core/layer/layer_conductance.py#L359 
to here:
https://github.com/pytorch/captum/blob/0435ff10a71724a788bdc54f01324f4f5c788541/captum/attr/_core/layer/layer_conductance.py#L391

in the paper (https://arxiv.org/pdf/1805.12233.pdf)  it is defined as :
![image](https://user-images.githubusercontent.com/46068300/134533643-fd628273-6261-4d73-b37a-93bce7a818b4.png)

for this reason i don't understand why we are computing `grad_diffs` and so on. 
I tried to use the formula from the paper but i am not getting the same results:

`torch.mean(scaled_features[0] * layer_grad[0] * torch.autograd.grad(torch.unbind(hooks[0].output.reshape(-1,1)), scaled_features, retain_graph=True)[0], 0)`

where:
`scaled_features` : (x' - x)
`layer_grad` : dF(..)/d(y)
`torch.autograd.grad(torch.unbind(hooks[0].output.reshape(-1,1)), scaled_features, retain_graph=True)[0]` : dy/dx

Thanks in advance!

**Comment by vivekmig** [comment]
Hi @MLAlex1 , the approach used in the LayerConductance implementation follows the formulation in https://arxiv.org/pdf/1807.09946.pdf which is equivalent to the original formulation and allows more efficient computation of layer conductance. There is a reference implementation [here](https://github.com/pytorch/captum/blob/0435ff10a71724a788bdc54f01324f4f5c788541/tests/attr/helpers/conductance_reference.py#L25) matching the original paper which is used for testing only, this may be helpful to better understand the code and compare the implementations.

Hope this helps!
