### ISSUE TITLE
How do you use CAVs to explain new images?

### ISSUE THREAD

**Issue by Alex-Gregory-1** [pytorch/captum#776]
How do you use CAVs to explain new images? I have followed the [TCAV tutorial](https://captum.ai/tutorials/TCAV_Image) and have found CAVs for my data but I am unsure how to use the CAVs to interpret new images. Is there a way to pass new images into the [TCAV](https://captum.ai/api/_modules/captum/concept/_core/tcav.html#TCAV) object so you can see the importance of each concept in the new images?

As I understand, I cannot use the [interpret](https://captum.ai/api/_modules/captum/concept/_core/tcav.html#TCAV.interpret) function as this will create a new set CAVs for the new input images.

Thanks in advance.

**Comment by NarineK** [comment]
Hi @Alex-Gregory-1, you can use CAVs in combination with TCAV to explain model predictions. If you have already precomputed CAVs, TCAV will not recompute them. It will use precomputed CAVs that are stored under `save_path` directory. CAVs are generated only for the concepts they are not generated for input images. I'm curious how did you generate the CAVs, did you use `compute_cavs` method from TCAV class ?

**Comment by Alex-Gregory-1** [comment]
Ahh I think I understand now. I used the `interpret` method from the TCAV class to generate the CAVs. The `interpret` method calls the `compute_cavs` method but if CAVs for the concepts in `experimental_sets` already exist in the `save_path` directory then the precomputed CAVs are used to interpret the inputs instead of computing new CAVs. Is this correct?

**Comment by NarineK** [comment]
Yes, that's right.

**Comment by NarineK** [comment]
@Alex-Gregory-1, if this is resolved, do you mind closing it ?

**Comment by Alex-Gregory-1** [comment]
Thanks for the help @NarineK!

**Comment by charchit7** [comment]
@NarineK could you please help with one question : 
let's consider I am checking concepts for zebra images.  
One interesting twist is that set of zebra images contains some lion images too.

Once I have calculated the SCAV vector. Can we extract only those images from the set which will contain concept for lion images(say big tooth). ? 
If yes, how? could you please tell.
