### ISSUE TITLE
SHAP on Torch Based Text classifier

### ISSUE THREAD

**Issue by y12uc231** [pytorch/captum#779]
Is it possible to compute SHAP values for text classifier implemented with torch?

**Comment by bilalsal** [comment]
Hi @y12uc231,

yes it should be possible to use SHAP-based attribution algorithms on a text classifier.
The following tutorials explain how to handle text:
- Using Layer attribution algorithms (e.g. [LayerGradientShap](https://captum.ai/api/layer.html#layer-gradientshap))
Illustrated on [TorchText](https://captum.ai/tutorials/IMDB_TorchText_Interpret)
Illustrated on [BERT](https://captum.ai/tutorials/Bert_SQUAD_Interpret) 
- Using [Interpretable Embeddings](https://captum.ai/api/utilities.html#interpretable-embeddings):
Illustrated on [PyTorch VQA](https://captum.ai/tutorials/Multimodal_VQA_Interpret)
Illustrated on [BERT](https://captum.ai/tutorials/Bert_SQUAD_Interpret2)

Let me know if face any issues similar to #771

Hope this helps

**Comment by y12uc231** [comment]
Yes, I tried using LayerGradientShap with the following code. 

```
layer_grad_shap = LayerGradientShap(model, model.fc)
    baselines = torch.zeros(test_text.shape[0]).to(torch.int64)
    attribution = layer_grad_shap.attribute(test_text.to(torch.int64), baselines,
                                            additional_forward_args=(test_offsets,),
                                            target=5)
```

But I received the following error. 

`RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding_bag)`

**Comment by y12uc231** [comment]
My model code is the following :- 

```
#
class TextClassificationModel(nn.Module):
    def __init__(self, vocab_size, embed_dim, num_class):
        super(TextClassificationModel, self).__init__()
        self.embedding = nn.EmbeddingBag(vocab_size, embed_dim, sparse=True)
        self.fc = nn.Linear(embed_dim, num_class)
        self.init_weights()

    def init_weights(self):
        initrange = 0.5
        self.embedding.weight.data.uniform_(-initrange, initrange)
        self.fc.weight.data.uniform_(-initrange, initrange)
        self.fc.bias.data.zero_()

    def forward(self, text, offsets = None):
        embedded = self.embedding(text, offsets)
        return self.fc(embedded)
```

which is the same as the one provided on [torch tutorial](https://pytorch.org/tutorials/beginner/text_sentiment_ngrams_tutorial.html) .

**Comment by bilalsal** [comment]
Hi @y12uc231 ,

yes I was expecting applying LayerGradientShap to be challenging: The algorithm needs to perturb the input with Gaussian noise, however, the input is an int tensor containing the token ids (perturbing these does not make sense and does not work).

Did you try using  [Interpretable Embeddings](https://captum.ai/api/utilities.html#interpretable-embeddings)?
It should help you circumvent the above issue (the perturbation will be performed directly in the embedding space, not on token ids). [This tutorial](https://captum.ai/tutorials/Multimodal_VQA_Interpret) demonstrates how to use this solution, I hope it works for you.

Let me know if you need further support!

**Comment by y12uc231** [comment]
Yes, I got this working, but these attributions are for each embedding feature right? Whats the method to get attributions for each word?

**Comment by BinchaoPeng** [comment]
did you solve it? It seems I have the same issue in IG.
now I have use "configure_interpretable_embedding_layer", but the output demension is not same as the output of forward
my email is 646047990@qq.com, hoping your reply, thanks!
