### ISSUE TITLE
Obtaining relevance of each network layer using a single backward pass

### ISSUE THREAD

**Issue by simomagi** [pytorch/captum#790]
Hi, i am not able to understand from the documentation if it is possible to compute relevance score (e.g DeepLift relevance) of each network layer using a single backward pass. It seems that you can only evaluate relevance for a single layer. If this is correct, is there a fast way to modify the code to obtain the relevances of the entire network in a single backward pass?

**Comment by bilalsal** [comment]
Hi @simomagi,

Currently a few Captum algorithms support computing the attribution w.r.t. multiple layers in a single backward pass:
- [Layer Activation](https://captum.ai/api/layer.html#layer-activation)
- [Layer Gradient x Activation](https://captum.ai/api/layer.html#layer-gradient-x-activation)
- [Layer LRP](https://captum.ai/api/layer.html#layer-lrp)

The [base class](https://github.com/pytorch/captum/blob/master/captum/attr/_utils/attribution.py#L352) of layer attribution algorithms does support such mode of operation.

Supporting this mode in the remaining algorithms can be a bit tricky, it would need studying their source code to make sure the computation is sound.
That said, I see the benefit of supporting such mode and will be happy to review your PRs if you decide to give it a shot.

Hope this help,
Bilal
