### ISSUE TITLE
Vision Transformer - Integrated Gradients

### ISSUE THREAD

**Issue by loukasilias** [pytorch/captum#791]
Hi all,

I have trained a model with 2 inputs.
The one input is text with BERT and the other input is image with vision transformer.
I want to use the Integrated Gradients.
Regarding BERT I have seen the documentation.
Regarding Vision Transformer, how will I apply the Integrated Gradients?

Thank you.

**Comment by bilalsal** [comment]
Hi @loukasilias,

which ViT model are you using for the image modality? Is it doing dense prediction (as in [DPT](https://github.com/isl-org/DPT), e.g., for segmentation) or image classification (as in the original ViT paper)?

In theory, Captum should be able to operate on the PyTorch implementations.
There are many design decisions as to how you perform the attribution, e.g., w.r.t. the patches, or to a specific layer.
Also, you might need to write your own visualization module to map the computed attributions to the pixel space.

My recommendation is to follow the standard Captum tutorial for image modalities (e.g. this tutorial with [ResNet](https://captum.ai/tutorials/Resnet_TorchVision_Interpret)), and to tune the computation to fit the ViT pipeline.
If you could share your code (e.g. in Colab), we can have a look and try to give you more specific recommendations.

Hope this helps

**Comment by rojinakashefi** [comment]
Hey
```
    from pytorch_pretrained_vit import ViT
    model = ViT('B_16_imagenet1k', pretrained=True)
    model.eval()
    transform = transforms.Compose([
        transforms.Resize(model.image_size),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
    ])
    img = Image.open('/image.jpg')
    img = img.resize(model.image_size)
    input_tensor = transform(img).unsqueeze(0)
    output = model(input_tensor)
    output = F.softmax(output, dim=1)
    prediction_score, pred_label_idx = torch.topk(output, 1)
    pred_label_idx.squeeze_()
    predicted_label = idx_to_labels[str(pred_label_idx.item())][1]
    print('Predicted:', predicted_label, '(', prediction_score.squeeze().item(), ')')
    integrated_gradients = IntegratedGradients(model)
    attributions_ig = integrated_gradients.attribute(input, target=pred_label_idx, n_steps=200)
```
I keep getting this error: 
RuntimeError: The size of tensor a (197) must match the size of tensor b (577) at non-singleton dimension 1, as you told captum must work on the pytorch implementations, what is the problem? (i used the same steps as it is used in ResNet tutorial)
