### ISSUE TITLE
Applying Captum to Autoencoders for Multivariate Time Series (Anomaly Setting)?

### ISSUE THREAD

**Issue by anaramirli** [pytorch/captum#819]
## ❓ Questions and Help

Hello! I was wondering if any explanation method can be utilized for autoencoders in an anomaly setting for multivariate time series. I would appreciate it a lot if you please take a look. 

Let's say I want to use GradientShap. The trained model takes shape 1xAxB (here 1: a single batch, A: time steps, B: feature size) and accordingly produces an output with the shape 1xAxB. For forward_func of GradientShap, I use the modified forward function of the model, which takes a single batch with shape AxB and gets the corresponding model's output with shape AxB:

 ```python
# for tracing the recontructed output
def f1(x):
    model.eval()
    with torch.no_grad():
        out = model(x.unsqueeze(0)).squeeze()
    return out
```

2. My question is that how can we trace the whole of output to the input? What should be used for the attribution target for explainer built by ```GradientShap(forward_func=f1)```? (the attribution input has the shape AxB, instead of 1xAxB, the same goes for the attribution baseline as well.)

 ```python
explainer = GradientShap(forward_func=f1)
baseline = torch.randn(X.shape, requires_grad=True) 
attr = explainer.attribute(X, baselines=baseline, trarger=what here?)
```

In theory, since this is an autoencoder setting for an anomaly, we can also trace the input to the reconstruction loss so that attribution signifies the features that maximize the reconstruction error. 

 ```python
# for tracing the loss
def f2(x):
    model.eval()
    with torch.no_grad():
        out = model(x.unsqueeze(0)).squeeze()
        loss= mse(x, out)
    return loss
```

3. Furthermore, to my understanding, the feature attribution is computed to induce the features that contribute to the output of a given forward function. For example, utilizing ShapleyValueSampling with  ```f2()``` (the one that returns loss) would give us the desired result (i.e., feature contribution being calculated based on their effect on maximizing the loss), right?

 ```python
explainer = ShapleyValueSampling(forward_func=f2)
baseline = torch.randn(X.shape, requires_grad=True) 
attr = explainer.attribute(X, baselines=baseline)
```

4. Moreover, I also tried to cooperate the ```f2()``` into GradientShap as below, but got the error message  ```RuntimeError: The size of tensor a (50) must match the size of tensor b (10) at non-singleton dimension 1```, which can be traced back to the  ```mse``` function in ```f2()```.  And ```mse``` function is just compromised of ```torch.mean((a - b) ** 2)```. But error here is not my main question (although would appreciate any useful insight), I'm interested in how one can use GradientShap with an auxiliary forward function of f2()?

 ```python
explainer = GradientShap(forward_func=f1)
baseline = torch.randn(X.shape, requires_grad=True) 
attr = explainer.attribute(X, baselines=baseline)
```

Thank you so much for your time in advance!

Best,
Anar

**Comment by bilalsal** [comment]
Hi @anaramirli ,

what about making your model output the reconstruction loss explicitly?
It will then be straightforward to attribute this scalar output to the model's input to find out which parts of the input have significant impact on it.

You can define a wrapper of your model that computes the reconstruction loss, issue #377 shows an example of how to define a wrapper function.

Hope this helps

**Comment by anaramirli** [comment]
Hi @bilalsal,

thank you for your reply! If you mean the wrapper as below, I've done it already. 


```python
# model take input with shape Nx10x8
def wrapper(x):
    loss = nn.MSELoss()
    output = model(x)
    return loss(x, output)
```

For Occulusion I had no problem, However, for example, when I use this wrapper with IntegratedGradients I get the following error:

```python
input = X_new[1].unsqueeze(0)
explainer = IntegratedGradients(forward_func=wrapper)
attributions, approximation_error = explainer.attribute(input, return_convergence_delta=True)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_12924/4252792609.py in <module>
      6 input = X_new[1].unsqueeze(0)
      7 explainer = IntegratedGradients(forward_func=f1)
----> 8 attributions, approximation_error = explainer.attribute(input, return_convergence_delta=True)

~\.conda\envs\dynamask\lib\site-packages\captum\log\__init__.py in wrapper(*args, **kwargs)
     33             @wraps(func)
     34             def wrapper(*args, **kwargs):
---> 35                 return func(*args, **kwargs)
     36 
     37             return wrapper

~\.conda\envs\dynamask\lib\site-packages\captum\attr\_core\integrated_gradients.py in attribute(self, inputs, baselines, target, additional_forward_args, n_steps, method, internal_batch_size, return_convergence_delta)
    284             )
    285         else:
--> 286             attributions = self._attribute(
    287                 inputs=inputs,
    288                 baselines=baselines,

~\.conda\envs\dynamask\lib\site-packages\captum\attr\_core\integrated_gradients.py in _attribute(self, inputs, baselines, target, additional_forward_args, n_steps, method, step_sizes_and_alphas)
    349 
    350         # grads: dim -> (bsz * #steps x inputs[0].shape[1:], ...)
--> 351         grads = self.gradient_func(
    352             forward_fn=self.forward_func,
    353             inputs=scaled_features_tpl,

~\.conda\envs\dynamask\lib\site-packages\captum\_utils\gradient.py in compute_gradients(forward_fn, inputs, target_ind, additional_forward_args)
    117         # runs forward pass
    118         outputs = _run_forward(forward_fn, inputs, target_ind, additional_forward_args)
--> 119         assert outputs[0].numel() == 1, (
    120             "Target not provided when necessary, cannot"
    121             " take gradient with respect to multiple outputs."

IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
```


I tried to fix this by changing the wrapper from scaler to vector as:

```python
def wrapper(x):
    loss = nn.MSELoss()
    output = model(x)[1]
    return torch.tensor([loss(x, output)]).requires_grad_(True).to(device)
```

This time I get the following error:

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_12924/1729687958.py in <module>
      7 explainer = IntegratedGradients(forward_func=f1)
      8 # baseline = torch.randn(input.shape, requires_grad=True)
----> 9 attributions, approximation_error = explainer.attribute(input, return_convergence_delta=True)

~\.conda\envs\dynamask\lib\site-packages\captum\log\__init__.py in wrapper(*args, **kwargs)
     33             @wraps(func)
     34             def wrapper(*args, **kwargs):
---> 35                 return func(*args, **kwargs)
     36 
     37             return wrapper

~\.conda\envs\dynamask\lib\site-packages\captum\attr\_core\integrated_gradients.py in attribute(self, inputs, baselines, target, additional_forward_args, n_steps, method, internal_batch_size, return_convergence_delta)
    284             )
    285         else:
--> 286             attributions = self._attribute(
    287                 inputs=inputs,
    288                 baselines=baselines,

~\.conda\envs\dynamask\lib\site-packages\captum\attr\_core\integrated_gradients.py in _attribute(self, inputs, baselines, target, additional_forward_args, n_steps, method, step_sizes_and_alphas)
    349 
    350         # grads: dim -> (bsz * #steps x inputs[0].shape[1:], ...)
--> 351         grads = self.gradient_func(
    352             forward_fn=self.forward_func,
    353             inputs=scaled_features_tpl,

~\.conda\envs\dynamask\lib\site-packages\captum\_utils\gradient.py in compute_gradients(forward_fn, inputs, target_ind, additional_forward_args)
    123         # torch.unbind(forward_out) is a list of scalar tensor tuples and
    124         # contains batch_size * #steps elements
--> 125         grads = torch.autograd.grad(torch.unbind(outputs), inputs)
    126     return grads
    127 

~\.conda\envs\dynamask\lib\site-packages\torch\autograd\__init__.py in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused)
    200         retain_graph = create_graph
    201 
--> 202     return Variable._execution_engine.run_backward(
    203         outputs, grad_outputs_, retain_graph, create_graph,
    204         inputs, allow_unused)

RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behaviour.
```

I'm out of ideas on how to fix this error with IntegratedGradients. May you please take a look?

Thank you for your time.

Best,
Anar

**Comment by bilalsal** [comment]
Hi @anaramirli ,

is it possible that the error stems from using `output = model(x)[1]` instead of ` output = model(x)` in your  `wrapper(x)`?

You can try to temporarily set `allow_unused=True` to your model to debug the issue, although this is not a recommended permanently setting as it can mask an underlying issue.

Let me know if this helps!

**Comment by anaramirli** [comment]
Hey @bilalsal,

I use `output = model(x)[1]` only because the model's forward function returns both encoded and decoded layers. I think this has got nothing to do with it. I mean, even if I change it to only the encoded layer, it doesn't work. 

I get the same problem with GradientShap as well. No idea how to solve with. Can I ask how do you suggest setting allow_unused=True for the model?

**Comment by bilalsal** [comment]
Hi @anaramirli 

allow_unused=True is a parameter of `torch.autograd.grad(..)`. It is used by Captum [here](https://github.com/pytorch/captum/blob/master/captum/_utils/gradient.py). You are right, I thought it is possible to set it to the model. It seems that you might need to patch `gradient.py` to use it.

Another source of the original error might be the inclusion of the input in the loss `mse(x, out)`. Just for the sake of debugging, could you replace `x` with a constant tensor?

**Comment by anaramirli** [comment]
I got it. So, in gradient-based methods, such as GradientShap, IntegratedGradients it's important that the output is part of the graph. But problem is that when we calculate loss using a torch.functional.mse_loss or torch.MSELoss(), the output is 0-dim tensor. However, gradient-based methods in captum, unlike for example Occlusion, don't accept 0-dim tensor. So, I was doing that by `torch.tensor([mse_loss(x, output)]).requires_grad_(True).to(device)`. But when we alter the 0-dim tensor to 1-dim like that, this tensor becomes no longer part of the computational graph. So, it's important to change from 0-dim tensor to 1-dim tensor using unsqueeze(0). In general, that works good for all, including occlusion. So the right wrapper would be: 

```python
def wrapper(x):
    return mse(x, model(x)).unsqueeze(0)
```

@bilalsal thanks a lot for your time. Wouldn't figure that out without your help!

Ciao. Happy Christmas. :)
