### ISSUE TITLE
Some questions about attribution analysis

### ISSUE THREAD

**Issue by LY54** [pytorch/captum#826]
For Integrated Gradients, Input*Gradients and GradientShap, can the attributions obtained by these algorithms be used to analyze positive and negative attributions.  

Positive attribution score means that the input in that particular position positively contributed to the final prediction and negative means the opposite.

**Comment by bilalsal** [comment]
Hi @LY54 ,

yes that is right. The attributions computed by Captum can be either positive or negative, and are meant to be interpreted as you described.

**Comment by LY54** [comment]
Thank you  very much for your kind answer.
But when I input samples into the network and apply captum.attr.Saliency to conduct attribution analysis, I find only positive values in the generated attribution?  At the same time, the application of Integrated Gradients method can achieve positive and negative attribution analysis, I would like to further ask whether this situation is normal?

**Comment by hydro-alex** [comment]
I do have a question fitting in here as well. 
When I use an LSTM for Time Series Forecasting, how do I interpret negative Integraded Gradients (IG)?
In my understanding, an integrated gradient of 0.2 and -0.2 would be of equal importance for the final prediction?
Would it make sense to delete features for prediction, which have negative IG?

**Comment by bilalsal** [comment]
Hi @LY54 

> Thank you very much for your kind answer. But when I input samples into the network and apply captum.attr.Saliency to conduct attribution analysis, I find only positive values in the generated attribution? At the same time, the application of Integrated Gradients method can achieve positive and negative attribution analysis, I would like to further ask whether this situation is normal?

Yes this is normal because [Saliency](https://captum.ai/api/saliency.html) returns the absolute value by default. Set `abs=False` when calling `saliency.attribute()` if you want the method to return signed gradient as attribution result.
IntegratedGradient does not return absolute values, and hence the attributions can be positive and negative by default.

Hope this helps

**Comment by bilalsal** [comment]
Hi @hydro-alex 

> I do have a question fitting in here as well. When I use an LSTM for Time Series Forecasting, how do I interpret negative Integraded Gradients (IG)? In my understanding, an integrated gradient of 0.2 and -0.2 would be of equal importance for the final prediction? Would it make sense to delete features for prediction, which have negative IG?

Yes, 0.2 and -0.2 have equal importance, however, the negative attribution for a feature means that the target will have a higher prediction score (or output value) if the feature is _smaller_. If you delete / ablate this feature, the prediction score should be higher.

Hope this helps
