### ISSUE TITLE
NaN-value attributions when using DeepLIFT during fp16 training

### ISSUE THREAD

**Issue by aarzchan** [pytorch/captum#835]
Hi! I'm trying to compute attributions for BigBird via DeepLIFT during fp16 training, but I'm getting NaN for many of the attribution values. However, if I do fp32 training, none of the attribution values are NaN. I guess the fp16 precision is truncating some near-zero intermediate values to zero, resulting in division-by-zero. Would appreciate any ideas on how to work around this issue!

For reference, the `inputs` and `baselines` parameters for my DeepLIFT attribute function call are constructed as follows:

`inputs`
- Feed input ids into BigBird word embedding layer to get input embeddings.
- Use input embeddings as inputs for DeepLIFT.

`baselines`
- Create baseline ids by setting all non-special tokens in the input ids to PAD.
- Feed baseline ids into BigBird word embedding layer to get baseline embeddings.
- Use baseline embeddings as baselines for DeepLIFT.

**Comment by bilalsal** [comment]
Hi @aarzchan , thank you for reporting this issue!

Does it help if you use an fp16 tensor for the `baselines` parameter in `DeepLift`?

**Comment by aarzchan** [comment]
Hi @bilalsal! Thanks for your comment, and apologies for my delayed response. I was busy with some other tasks recently.

I've tried casting different combinations of `inputs` and `baselines` as `Float16` type, but I get the same output.

If I cast `inputs` and/or `baselines` as `Float32` type, then I get the error `RuntimeError: expected scalar type Double but found Float`, since the model parameters are `Float16` type.

**Comment by bilalsal** [comment]
I see. Thank you @aarzchan . Is it easy to create a minimal Colab notebook demonstrating the error? Would love to play with this further.

**Comment by aarzchan** [comment]
Hi @bilalsal, here is a [Colab notebook](https://colab.research.google.com/drive/1UN4j42EMV--6bPPgegEefhOSNWrKwzX6?usp=sharing) demonstrating the error. I shared it with your FB email.

**Comment by NarineK** [comment]
@aarzchan, @bilalsal  has this issue been addressed after we configured the eps in https://github.com/pytorch/captum/pull/854 ?

**Comment by bilalsal** [comment]
Hi @NarineK. I shared a [Colab notebook](https://colab.research.google.com/drive/12HThc6JNQTYTNZrvGm2c1pSu0m9zZoN0) with Aaron demonstrating the fix.
I think we can close this issue, unless @aarzchan has further remarks / questions.

**Comment by aarzchan** [comment]
Hi @bilalsal and @NarineK, thanks for the fix! I don't have any further remarks/questions, so I'm closing the issue.

**Comment by aygalic** [comment]
Hi, I am having the same issue when using DeepLiftShap, I noticed that changing the default value of `eps` in the DeepLift constructor solved the issue. I am also using fp16.
Could it be possible to have access to `eps` from the DeepLiftShap constructor as well ?
