### ISSUE TITLE
Gridding in Saliency Visualizations

### ISSUE THREAD

**Issue by vjoshi48** [pytorch/captum#852]
❓ Questions and Help

I have been trying to visualize saliency for a model that I created, however, I am getting some weird results. There is a lot of gridding in the images that I have gotten and I am not sure how to get rid of this gridding or what it means. Is my use of the visualization function correct? What does this gridding mean exactly? Attached is a screenshot of the gridding I am talking about.

Here is a link to the code: https://github.com/vjoshi48/CatalystGriddingIssue
Here is a link to the PTH file needed to load model: https://drive.google.com/file/d/1G_Tm6yngrB8BNfFJH3u1kseZAjUxl6W-/view?usp=sharing

Thank you.
<img width="278" alt="githubscreenshot" src="https://user-images.githubusercontent.com/77455331/151831696-e3b69426-fa02-4a21-8434-a0ed62a71259.png">

**Comment by bilalsal** [comment]
Hi @vjoshi48 ,

thank you for sharing your interesting results.

AFAIS, this is very likely an artifact of the striding choices you are making (stride 3 with kernel-size of 11, followed by stride 2 with kernel-size of 5).
Check out this interactive article to analyze how these parameters interact: https://distill.pub/2016/deconv-checkerboard/

Hope this helps

**Comment by vjoshi48** [comment]
@bilalsal Great, thank you so much. I will check out this article!
