### ISSUE TITLE
tcav.classifier.weights() doesn't work when cavs are loaded

### ISSUE THREAD

**Issue by expectopatronum** [pytorch/captum#856]
## 🐛 Bug

I ran the [TCAV_Image notebook](https://captum.ai/tutorials/TCAV_Image) and added a line to print the weights of the linear model. This works the first time when the TCAV object still holds the trained linear model, but when the notebook is executed a second time (and the cavs are loaded from `save_path`), it causes an error.

## To Reproduce

1. Create a TCAV object and interpret an example
2. Restart the kernel / session
3. Rerun the notebook script (to get a TCAV object with cavs loaded from `save_path`)
4. Call `tcav.classifier.weights()`

This causes the following error:

```
  File "/home/verena/miniconda3/envs/py38-gv/lib/python3.8/site-packages/captum/_utils/models/linear_model/model.py", line 141, in representation
    assert self.linear is not None
```
This happens because only the cavs are stored/loaded and not the trained classifier.

## Expected behavior

When the cavs are stored, the classifier (and possibly other computed things) should be stored as well and loaded when the cavs are reused.

## Additional context

A workaround could be to set `force_train=True` but this parameter is only available in `compute_cavs` and cannot be modified when calling `interpret`.

**Comment by NarineK** [comment]
Thank you for reporting this bug, @expectopatronum! We'll address it in the next release but, please, note that for each layer we train a classifier and the weights are being overridden by the next trained model.  The classifier is a skeleton definition and we use it to do cold start training for each layer hence it is probably not a good way of accessing the weights. Instead you can access the weights from tcav.cav["concepts_key"]["layer"].stats
`tcav.cav` will give you a dictionary of all those weights for given concepts and layer.

**Comment by expectopatronum** [comment]
Thanks a lot for the hint, I wasn't aware! :)

**Comment by expectopatronum** [comment]
I just tried accessing `tcav.cav["concepts_key"]["layer"].stats` (actually just `tcav.cav` to look at it) and get

```
AttributeError: 'TCAV' object has no attribute 'cav'
```
Do I have to do something else before (I am still using the TCAV_Image Jupyter notebook, with almost no changes)?

**Comment by NarineK** [comment]
@expectopatronum, I had a typo there. It is `tcav.cavs`. If you print it you'll see all stats about thee cavs. Specifically for TCAV_Image you can do for example, `tcav.cavs['0-3']['inception4c']`

**Comment by NarineK** [comment]
<img width="935" alt="Screen Shot 2022-02-11 at 9 42 01 AM" src="https://user-images.githubusercontent.com/12010601/153641689-87329455-9a93-4518-9314-0e5d6cdb93bf.png">

**Comment by NarineK** [comment]
Then you can do for example  `mytcav.cavs['0-3']['inception4c'].stats` to get the weights for layer `inception4c` and concepts with ids 0 and 3.

**Comment by NarineK** [comment]
@expectopatronum, if that answers to your question can we close this issue? I also added warning if the users tries to access the classifier the way you did.

**Comment by expectopatronum** [comment]
Thanks a lot!
