### ISSUE TITLE
Support for random forests?

### ISSUE THREAD

**Issue by y12uc231** [pytorch/captum#865]
Most of the interpretability research has been on studying uninterpretable models such as random forests. Is it possible to use captum for it?

**Comment by aobo-y** [comment]
Yes, many perturbation-based algorithms in captum do not assume the internal implementation of your model, e.g., FeatureAblation, LIME. But since captum is a PyTorch lib, you need to wrap your model to have the input & output in PyTorch Tensors if they are not.

Example if your model uses numpy
```py
def forward_wrapper(tensor):
  input = tensor.numpy()
  output = random_forests(input)
  return torch.tensor(output)

fa = FeatureAblation(forward_wrapper)
```

**Comment by y12uc231** [comment]
Yes, this was helpful, thanks !
