### ISSUE TITLE
Reinforcement Learning?

### ISSUE THREAD

**Issue by jarlva** [pytorch/captum#924]
Hello,

Can captum be used with reinforcement learning?

**Comment by bilalsal** [comment]
Hi @jarlva ,

The majority of algorithms in Captum are generic and can be applied to most PyTorch models.
The interpretation of the attribution results in the case of a RL policy should be done carefully, but I do not see a major reason not to try (e.g. starting with [IntegratedGradients](https://captum.ai/api/integrated_gradients.html) or other algorithms.

Hope this helps
