### ISSUE TITLE
More Information About the CSV concept files

### ISSUE THREAD

**Issue by basselmawzi** [pytorch/captum#931]
## ❓ Questions and Help

Hello, 

Can you please provide more information about the concept csv files provided in the tutorial? Specifically, How can we replicate such files if we want to test for our own concepts? And what does each line in the file represent?

**Comment by NarineK** [comment]
@basselmawzi, what do you mean by concept csv files ? Do you mean cv ? Computer Vision tutorials for TCAV ?

**Comment by basselmawzi** [comment]
I mean the csv files from which we loaded the "positive adjectives" concept and the "neutral" concepts in the _"Testing with Concept Activation Vectors (TCAV) on Sensitivity Classification Examples and a ConvNet model trained on IMDB DataSet"_ tutorial

**Comment by NarineK** [comment]
@basselmawzi, those files are here: https://github.com/pytorch/captum/tree/master/tutorials/data/tcav/text-sensitivity

**Comment by basselmawzi** [comment]
Hello! 

Thanks for the help. I know where the files are. My question was about the construction of these files. To be more specific, my questions are about the tutorial that used tcav for the convnet model: 

1) what does each line in the csv file represent? 
2) How did you build these CSV files?

**Comment by NarineK** [comment]
@basselmawzi, sorry, I misunderstood your question. The content of neutralX.csv files is chosen randomly from the dataset available under Gutenberg project. 
[https://github.com/google-research-datasets/poem-sentiment/blob/master/data/train.tsv](https://github.com/google-research-datasets/poem-sentiment/blob/master/data/train.tsv)
Neutral concept files in this specific tutorial meant to contain any neutral content. We used random sentences from Gutenberg project. Each line in those files is an example representing that specific concept. Neutral random sentences represent random concepts.

W.r.t. positive-adjectives.csv we used positive adjective tokens from IMDB dataset. We removed specific context around it and replaced it with dots. This way it helped us to make positive adjectives more generic and independent of the context. Each line in `positive-adjectives.csv` represents an example of positive adjective's concept.

This is one way of defining the concepts. You can define your concepts the way you want.
