### ISSUE TITLE
Applying cv2 functions in image preprocessing

### ISSUE THREAD

**Issue by reedless** [pytorch/captum#932]
## ❓ Questions and Help

Hi, I am trying to apply Captum's Integrated Gradients algorithm to an ImageNet pretrained shufflenetv2 in [this](https://github.com/RangiLyu/nanodet) nanodet library. Unfortunately, the image preprocessing is done using a Pipeline class which requires numpy array input as it uses cv2 functions [here](https://github.com/RangiLyu/nanodet/blob/main/nanodet/data/transform/warp.py#L340).

This forces me to call `.detach().cpu().numpy().astype(np.uint8)` on the input Tensors which expectedly gives the following error:
`RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.` I am also unable to use the pytorch equivalents of the cv2 functions as they produce different results and result in differing class scores.

Are there any suggested workarounds in this issue besides changing the entire image preprocessing in the training stage to avoid using cv2 and numpy arrays? I would like to avoid doing that as I am loading the pre-trained weights off the repo.

Thanks in advance!

**Comment by 99warriors** [comment]
Hi @reedless if the pre-processing eventually produces a pytorch tensor that is given to a pytorch model, would it be possible to attribute using the pytorch model, with the pytorch tensor as the input?  I might be mis-understanding your constraints.

**Comment by reedless** [comment]
Hi @99warriors, nope, you're absolutely right. Passing the preprocessed tensor as input fixed the issue. Thanks!
