### ISSUE TITLE
Function for visualising time series attribution

### ISSUE THREAD

**Issue by smaeland** [pytorch/captum#958]
## 🚀 Feature
Function for visualising time series along with attribution values, just like `captum.attr.visualization.visualize_image_attr` does for images.

## Motivation
Working with time series a lot, I often copy the same plotting function around between projects, so I think it would be great to have a basic 1D plotting method built-in. Since 1D attributions are prepared the same way as for images (normalisation and choice of sign), it would fit in nicely with the existing code. I would be happy to submit a PR with my own (adapted) plotting function, but probably best to first discuss the scope and need.

## Pitch
A built-in plotting function would simplify and speed up the model development cycle. But besides convenience, it could also be valuable to new users, since the applicability of Captum to time series is somewhat undercommunicated :smile:

## Alternatives
Users write their own custom plotting functions. This is likely to happen anyway because of the big variation in different time series' length, number of channels, etc., but in that case, a built-in function is a good starting point.

**Comment by NarineK** [comment]
@smaeland, thank you for proposing this functionality. Sure, feel free to send a PR. 
cc: [i-jones](https://github.com/i-jones)

**Comment by ic085908** [comment]
@smaeland Thank you for your helpful function for plotting time series. 
I tried to learn explainable method for time series and used your function for visualization. However, I am struggling with these processes of transferring my model to explainable method and visualization . 
Could you give a simply example to use your function of time series?  I apologize for this may disturb you, I am a green hand. 
 
In any case, thanks for your help.

**Comment by smaeland** [comment]
Hi @ic085908, here is the script I used to produce the plots shown in #980: [visualize_synthetic_data.py](https://gist.github.com/smaeland/f132ae58db4aa709d92d49bf2bf19d58) (data is randomly generated, so it won't look exactly identical). Let me know if you run into any problems or find things that could be improved

**Comment by ic085908** [comment]
Hello @smaeland, I really appreciate your help. 
The script smoothly runs as a figure below. I will apply your script to my model.
![image](https://user-images.githubusercontent.com/46443600/178116262-d8b48951-b8dc-4c54-bde0-2365c0b547e9.png)
Many thanks,

**Comment by smaeland** [comment]
Great! I'll close this then, since the corresponding PR is merged now.
