### ISSUE TITLE
target parameter in attribute for 3D segmentation 

### ISSUE THREAD

**Issue by ReemShalaata** [pytorch/captum#962]
How Can I use captum for 3D segmentation .
I have a 3D model that gets an input 5D tensor of (1,1,4,256,256) which is a four frame video and outputs a 5D tensor also of size (1,3,4,256,256) a video with 3 labels.
What should be the target in attribute?I tried to put the mask_pred but it didn't work...

 attr_lgc=lgc.attribute(inp_vid_tensor,target=?????)

**Comment by ReemShalaata** [comment]
problem solved by mistake I had the convolutional layer inside a list ,so I just removed the square brackets:)

**Comment by vivekmig** [comment]
Great, glad the issue was resolved!
