### ISSUE TITLE
About Getting CAVs

### ISSUE THREAD

**Issue by basselmawzi** [pytorch/captum#997]
Hello, 

I just have a question about getting CAVs. In the paper, they defined CAVs as being the vectors normal to the hyperplane separating the concept samples from some random samples. 

Why are taking the CAVs as being the trained classifier's weights in Captum? Why aren't we considering taking the normal to the hyperplane?

Thanks for the help. 
Best regards, 
Basel

**Comment by NarineK** [comment]
@basselmawzi, the weight vector is perpendicular to the hyperplane for the linear model by definition.
https://www.cs.cornell.edu/courses/cs4780/2018fa/lectures/lecturenote03.html

**Comment by basselmawzi** [comment]
thanks
